#lang racket/base
;; Detached UNPREMULTIPLIED float colors. No native library on import.
(require "color.rkt" "private/check.rkt")
(provide color4f? make-color4f color4f-red color4f-green color4f-blue color4f-alpha
         color4f->vector color->color4f color4f->rgba)
(struct color4f (red green blue alpha) #:transparent #:constructor-name make-color4f-record)
(define (make-color4f red green blue [alpha 1])
  (define who 'make-color4f)
  (define (component v)
    (unless (and (real? v) (<= -340282346638528859811704183484516925440 v
                                340282346638528859811704183484516925440))
      (raise-argument-error who "finite real in binary32 range" v))
    (exact->inexact v))
  (define r (component red)) (define g (component green)) (define b (component blue))
  (define a (scalar who alpha))
  (unless (<= 0 a 1) (raise-argument-error who "finite alpha in [0,1]" alpha))
  ;; Negative/extended RGB are intentional. Do not route through packed colors.
  (make-color4f-record r g b a))
(define (checked-color4f who c)
  (unless (color4f? c) (raise-argument-error who "color4f?" c))
  c)
(define (color4f->vector c)
  (checked-color4f 'color4f->vector c)
  (vector-immutable (color4f-red c) (color4f-green c) (color4f-blue c) (color4f-alpha c)))
(define (color->color4f c)
  (define v (color->rgba c))
  (make-color4f (/ (rgba-red v) 255) (/ (rgba-green v) 255) (/ (rgba-blue v) 255) (/ (rgba-alpha v) 255)))
(define (color4f->rgba c #:out-of-range [policy 'error])
  (define who 'color4f->rgba)
  (checked-color4f who c)
  (unless (memq policy '(error clip)) (raise-argument-error who "'error or 'clip" policy))
  (define (byte v)
    (when (and (eq? policy 'error) (not (<= 0 v 1)))
      (error who "extended RGB requires explicit #:out-of-range 'clip"))
    (inexact->exact (floor (+ 0.5 (* 255 (max 0 (min 1 v)))))))
  ;; Explicit numerical quantization, NOT a color-space conversion/tone mapper.
  (rgba (byte (color4f-red c)) (byte (color4f-green c))
        (byte (color4f-blue c)) (byte (color4f-alpha c))))
(module* internals #f (provide checked-color4f))
