#lang racket/base
(require ffi/unsafe racket/list racket/math racket/vector
         "color.rkt" "private/core.rkt" "private/native.rkt" "private/types.rkt"
         "private/check.rkt" "private/lifetime.rkt" "private/geometry-util.rkt"
         (submod "private/core.rkt" geometry-internals))
(provide region? make-region region-copy region-empty? region-rect? region-complex?
         region-bounds region-rectangles in-region-rectangles
         region-contains-point? region-contains-rect? region-contains-region? region-intersects?
         region-op region-union region-intersect region-difference region-xor
         region-translate path->region region->path draw-region canvas-clip-region!
         vertices? make-vertices vertices-mode vertices-positions vertices-texture-coordinates
         vertices-colors vertices-indices vertices-count draw-vertices
         image-lattice? make-image-lattice image-lattice-x-divisions image-lattice-y-divisions
         image-lattice-bounds image-lattice-cell-types image-lattice-colors
         draw-image-nine draw-image-lattice
         atlas-transform? make-atlas-transform atlas-transform-coefficients draw-atlas
         cubic-patch? make-cubic-patch cubic-patch-points cubic-patch-colors
         cubic-patch-texture-coordinates draw-patch)

;; All public snapshots are ordinary immutable data. Native buffers below are
;; temporary, have no callback, and are kept reachable through each FFI call.
(define (flat-buffer values type)
  (and (pair? values)
       (let ([p (malloc (* (length values) (ctype-sizeof type)) 'atomic)])
         (for ([v (in-list values)] [i (in-naturals)]) (ptr-set! p type i v))
         p)))
(define (vector-buffer v type) (and v (flat-buffer (vector->list v) type)))
(define (point-buffer v)
  (and v (flat-buffer (append* (for/list ([p (in-vector v)]) (vector->list p))) _float)))
(define (native-rect v)
  (make-sk-rect (vector-ref v 0) (vector-ref v 1)
                (+ (vector-ref v 0) (vector-ref v 2)) (+ (vector-ref v 1) (vector-ref v 3))))
(define (native-irect v)
  (make-sk-irect (vector-ref v 0) (vector-ref v 1)
                 (+ (vector-ref v 0) (vector-ref v 2)) (+ (vector-ref v 1) (vector-ref v 3))))
(define (irect-value r)
  (vector-immutable (sk-irect-left r) (sk-irect-top r)
                    (- (sk-irect-right r) (sk-irect-left r))
                    (- (sk-irect-bottom r) (sk-irect-top r))))
(define (region? v) (region-resource? v))
(define (region-h who r)
  (unless (region? r) (raise-argument-error who "region?" r))
  (region-resource-handle r))
(define (fresh-region who init)
  (skia-check!)
  (define r (make-region-record (new-owned who 'region sk_region_new sk_region_delete)))
  (with-handlers ([(lambda (_) #t) (lambda (e) (skia-close! r) (raise e))])
    (call-with-owned who (list (region-h who r)) init)
    r))
(define (make-region [rectangles '()])
  (define who 'make-region)
  (define xs (geometry-list who rectangles))
  (geometry-budget who (length xs) (* 16 (length xs)))
  (define boxes (map (lambda (b) (geometry-irect who b)) xs))
  (fresh-region
   who
   (lambda (rp)
     (unless (null? boxes)
       (define buf
         (flat-buffer
          (append* (for/list ([b (in-list boxes)])
                     (list (vector-ref b 0) (vector-ref b 1)
                           (+ (vector-ref b 0) (vector-ref b 2))
                           (+ (vector-ref b 1) (vector-ref b 3))))) _int32))
       ;; False means the resulting region is empty, not allocation failure.
       (sk_region_set_rects rp buf (length boxes))
       (void/reference-sink buf)))))
(define (region-copy r)
  (define who 'region-copy)
  (call-with-owned who (list (region-h who r))
    (lambda (rp) (fresh-region who (lambda (out) (sk_region_set_region out rp))))))
(define (region-empty? r)
  (call-with-owned 'region-empty? (list (region-h 'region-empty? r)) sk_region_is_empty))
(define (region-rect? r)
  (call-with-owned 'region-rect? (list (region-h 'region-rect? r)) sk_region_is_rect))
(define (region-complex? r)
  (call-with-owned 'region-complex? (list (region-h 'region-complex? r)) sk_region_is_complex))
(define (region-bounds r)
  (define b (make-sk-irect 0 0 0 0))
  (call-with-owned 'region-bounds (list (region-h 'region-bounds r))
    (lambda (rp) (sk_region_get_bounds rp b) (irect-value b))))
(define (region-contains-point? r x y)
  (define who 'region-contains-point?)
  (define ix (geometry-int who x)) (define iy (geometry-int who y))
  (call-with-owned who (list (region-h who r)) (lambda (rp) (sk_region_contains_point rp ix iy))))
(define (region-contains-rect? r rectangle)
  (define who 'region-contains-rect?)
  (define b (native-irect (geometry-irect who rectangle)))
  (call-with-owned who (list (region-h who r)) (lambda (rp) (sk_region_contains_rect rp b))))
(define (region-contains-region? a b)
  (define who 'region-contains-region?)
  (call-with-owned who (list (region-h who a) (region-h who b)) sk_region_contains))
(define (region-intersects? a b)
  (define who 'region-intersects?)
  (call-with-owned who (list (region-h who a) (region-h who b)) sk_region_intersects))
(define region-ops (hasheq 'difference 0 'intersect 1 'union 2 'xor 3 'reverse-difference 4 'replace 5))
(define (region-op a b operation)
  (define who 'region-op)
  (define op (choice who operation region-ops))
  (call-with-owned who (list (region-h who a) (region-h who b))
    (lambda (ap bp)
      (fresh-region who (lambda (rp) (sk_region_set_region rp ap) (sk_region_op rp bp op))))))
(define (region-union a b) (region-op a b 'union))
(define (region-intersect a b) (region-op a b 'intersect))
(define (region-difference a b) (region-op a b 'difference))
(define (region-xor a b) (region-op a b 'xor))
(define (region-translate r dx dy)
  (define who 'region-translate)
  (define ix (geometry-int who dx)) (define iy (geometry-int who dy))
  (call-with-owned
   who (list (region-h who r))
   (lambda (rp)
     (define b (make-sk-irect 0 0 0 0))
     (sk_region_get_bounds rp b)
     (unless (sk_region_is_empty rp)
       (for ([x (in-list (list (+ ix (sk-irect-left b)) (+ ix (sk-irect-right b))
                              (+ iy (sk-irect-top b)) (+ iy (sk-irect-bottom b))))])
         (geometry-int who x)))
     (fresh-region who (lambda (out) (sk_region_set_region out rp) (sk_region_translate out ix iy))))))
(define (path->region path clip)
  (define who 'path->region)
  (call-with-owned who (list (path-h who path) (region-h who clip))
    (lambda (pp cp) (fresh-region who (lambda (out) (sk_region_set_path out pp cp))))))
(define (region->path r)
  (define who 'region->path)
  (call-with-owned
   who (list (region-h who r))
   (lambda (rp)
     (define p (make-path))
     (with-handlers ([(lambda (_) #t) (lambda (e) (skia-close! p) (raise e))])
       (call-with-owned who (list (path-h who p)) (lambda (pp) (sk_region_get_boundary_path rp pp)))
       p))))
(define (region-rectangles r)
  (define who 'region-rectangles)
  (call-with-owned
   who (list (region-h who r))
   (lambda (rp)
     (call-with-native-temporary
      who 'region-iterator (lambda () (sk_region_iterator_new rp)) sk_region_iterator_delete
      (lambda (it)
        (define b (make-sk-irect 0 0 0 0))
        (let loop ([n 0] [out '()])
          (if (sk_region_iterator_done it)
              (reverse out)
              (begin
                (geometry-budget who (add1 n) (* 16 (add1 n)))
                (sk_region_iterator_rect it b)
                (let ([value (irect-value b)])
                  (sk_region_iterator_next it)
                  (loop (add1 n) (cons value out)))))))))))
(define (in-region-rectangles r) (in-list (region-rectangles r)))
(define (draw-region c r paint)
  (define who 'draw-region)
  (define rh (region-h who r))
  (define ph (paint-h who paint))
  ;; SkCanvas::drawRegion decomposes the region into rectangles. That is fine
  ;; for native raster/PDF devices, but SVG serializes those rectangles
  ;; independently and browsers can expose hairline seams between touching
  ;; fill bands. A filled region is exactly represented by its boundary path,
  ;; so submit that single path for fill paints. Preserve Skia's native
  ;; rectangle semantics for stroke and stroke-and-fill paints.
  (define style
    (call-with-owned who (list ph) (lambda (pp) (sk_paint_get_style pp))))
  (if (= style 0) ; FILL_SK_PAINT_STYLE
      (with-skia ([boundary (region->path r)])
        (call-on-canvas who c (list (path-h who boundary) ph) sk_canvas_draw_path))
      (call-on-canvas who c (list rh ph) sk_canvas_draw_region)))
(define (canvas-clip-region! c r #:operation [operation 'intersect])
  (define who 'canvas-clip-region!)
  (define op (choice who operation clip-values))
  ;; This intentionally matches native device-coordinate clipping; it does not
  ;; reinterpret region coordinates through the current canvas matrix.
  (call-on-canvas who c (list (region-h who r)) (lambda (cp rp) (sk_canvas_clip_region cp rp op))))

;; SkVertices is immutable and owns copies of its submitted data. These Racket
;; snapshots are independent too, including after explicit native closure.
(define (vertices? v) (vertices-resource? v))
(define (vertices-h who v)
  (unless (vertices? v) (raise-argument-error who "vertices?" v))
  (vertices-resource-handle v))
(define (checked-vertices v who getter) (vertices-h who v) (getter v))
(define (vertices-mode v) (checked-vertices v 'vertices-mode vertices-resource-mode))
(define (vertices-positions v) (checked-vertices v 'vertices-positions vertices-resource-positions))
(define (vertices-texture-coordinates v) (checked-vertices v 'vertices-texture-coordinates vertices-resource-texture))
(define (vertices-colors v) (checked-vertices v 'vertices-colors vertices-resource-colors))
(define (vertices-indices v) (checked-vertices v 'vertices-indices vertices-resource-indices))
(define (vertices-count v) (vector-length (vertices-positions v)))
(define (make-vertices mode positions #:texture-coordinates [tex #f] #:colors [colors #f] #:indices [indices #f])
  (define who 'make-vertices)
  (define-values (ps ts cs is) (geometry-vertices who mode positions tex colors indices))
  (define m (case mode [(triangles) 0] [(triangle-strip) 1] [else 2]))
  (skia-check!)
  (define pb (point-buffer ps)) (define tb (point-buffer ts))
  (define cb (vector-buffer cs _uint32)) (define ib (vector-buffer is _uint16))
  (define h
    (new-owned who 'vertices
      (lambda () (sk_vertices_make_copy m (vector-length ps) pb tb cb
                                        (if is (vector-length is) 0) ib)) sk_vertices_unref))
  (void/reference-sink pb tb cb ib)
  (make-vertices-record h mode ps ts cs is))
(define (draw-vertices c v paint #:blend-mode [blend 'modulate])
  (define who 'draw-vertices)
  (define mode (choice who blend blend-values))
  (call-on-canvas who c (list (vertices-h who v) (paint-h who paint))
    (lambda (cp vp pp) (sk_canvas_draw_vertices cp vp mode pp))))

;; Lattices are dimension-independent value specifications. Bounds/divisions
;; are checked against the actual image immediately before drawing.
(struct image-lattice (x-divisions y-divisions bounds cell-types colors)
  #:transparent #:constructor-name make-image-lattice-record)
(define cell-type-values (hasheq 'default 0 'transparent 1 'fixed-color 2))
(define (make-image-lattice x-divisions y-divisions #:bounds [bounds #f]
                             #:cell-types [cell-types #f] #:colors [colors #f])
  (define who 'make-image-lattice)
  (define xs (geometry-divisions who x-divisions))
  (define ys (geometry-divisions who y-divisions))
  (unless (> (+ (vector-length xs) (vector-length ys)) 0)
    (raise-arguments-error who "at least one axis must contain a division"))
  (define box (and bounds (geometry-irect who bounds)))
  (when (and box (or (zero? (vector-ref box 2)) (zero? (vector-ref box 3))))
    (raise-argument-error who "nonempty source bounds" bounds))
  (define n (* (add1 (vector-length xs)) (add1 (vector-length ys))))
  (geometry-budget who n (+ (* 4 (+ (vector-length xs) (vector-length ys))) (* n 5)))
  (define types
    (and cell-types
         (let ([ts (geometry-list who cell-types)])
           (unless (= n (length ts))
             (raise-arguments-error who "cell types must cover the complete grid, row-major"
                                    "expected count" n "given" (length ts)))
           (for ([t (in-list ts)]) (choice who t cell-type-values))
           (vector->immutable-vector (list->vector ts)))))
  (define cs (geometry-colors who colors n))
  (when (and cs (not types)) (raise-arguments-error who "colors require explicit cell types"))
  (when (and types (for/or ([t (in-vector types)]) (eq? t 'fixed-color)) (not cs))
    (raise-arguments-error who "fixed-color cells require one color per grid cell"))
  (when box (check-lattice-divisions who xs ys box))
  (make-image-lattice-record xs ys box types cs))
(define (check-lattice-divisions who xs ys box)
  ;; Strict interior coordinates avoid the native edge-division special case,
  ;; whose rect-type array indexing otherwise changes at the outer boundary.
  (for ([x (in-vector xs)])
    (unless (< (vector-ref box 0) x (+ (vector-ref box 0) (vector-ref box 2)))
      (raise-arguments-error who "x divisions must be strictly inside source bounds" "division" x)))
  (for ([y (in-vector ys)])
    (unless (< (vector-ref box 1) y (+ (vector-ref box 1) (vector-ref box 3)))
      (raise-arguments-error who "y divisions must be strictly inside source bounds" "division" y))))
(define (draw-image-nine c im center x y width height #:sampling [filter 'linear] #:paint [paint #f])
  (define who 'draw-image-nine)
  (define ih (image-h who im))
  (define b (geometry-source-bounds who (geometry-irect who center) (image-width im) (image-height im)))
  (define dst (rect who x y width height))
  (define f (choice who filter sampling-values))
  (define ph (and paint (paint-h who paint)))
  (call-on-canvas who c (if ph (list ih ph) (list ih))
    (lambda (cp ip . pps)
      (sk_canvas_draw_image_nine cp ip (native-irect b) dst f (if ph (car pps) #f)))))
(define (draw-image-lattice c im lattice x y width height #:sampling [filter 'linear] #:paint [paint #f])
  (define who 'draw-image-lattice)
  (define ih (image-h who im))
  (unless (image-lattice? lattice) (raise-argument-error who "image-lattice?" lattice))
  (define b (or (image-lattice-bounds lattice) (vector-immutable 0 0 (image-width im) (image-height im))))
  (geometry-source-bounds who b (image-width im) (image-height im))
  (define xs (image-lattice-x-divisions lattice))
  (define ys (image-lattice-y-divisions lattice))
  (check-lattice-divisions who xs ys b)
  (define n (* (add1 (vector-length xs)) (add1 (vector-length ys))))
  (geometry-budget who n (+ (* 4 (+ (vector-length xs) (vector-length ys))) (* n 5)))
  (define dst (rect who x y width height))
  (define f (choice who filter sampling-values))
  (define ph (and paint (paint-h who paint)))
  (call-on-canvas
   who c (if ph (list ih ph) (list ih))
   (lambda (cp ip . pps)
     (define xb (vector-buffer xs _int32)) (define yb (vector-buffer ys _int32))
     (define types (image-lattice-cell-types lattice))
     ;; The C shim reinterprets pointers without converting enum arrays. Native
     ;; SkCanvas::Lattice::RectType is uint8_t, unlike the public C enum.
     (define tb (and types (flat-buffer (for/list ([t (in-vector types)]) (hash-ref cell-type-values t)) _uint8)))
     ;; SkLatticeIter advances a color pointer alongside every cell type, even
     ;; for default/transparent cells. Supply a full zero buffer when the caller
     ;; has no fixed colors instead of relying on null-pointer arithmetic.
     (define cb (or (vector-buffer (image-lattice-colors lattice) _uint32)
                    (and types (flat-buffer (make-list n 0) _uint32))))
     (define nb (native-irect b))
     (define lat (make-sk-lattice xb yb tb (vector-length xs) (vector-length ys) nb cb))
     (sk_canvas_draw_image_lattice cp ip lat dst f (if ph (car pps) #f))
     (void/reference-sink xb yb tb cb nb lat lattice))))

;; Each transform maps a sprite's local source origin (not atlas coordinates).
(struct atlas-transform (coefficients) #:transparent #:constructor-name make-atlas-transform-record)
(define (make-atlas-transform x y #:scale [scale 1] #:rotation [degrees 0] #:anchor [anchor '(0 0)])
  (define who 'make-atlas-transform)
  (define fx (scalar who x)) (define fy (scalar who y))
  (define s (nonnegative-scalar who scale)) (define d (scalar who degrees))
  (define a (vector-ref (geometry-points who (list anchor) 1) 0))
  (define theta (* (/ d 180.0) pi))
  (define sc (scalar who (* s (cos theta)))) (define ss (scalar who (* s (sin theta))))
  (define tx (scalar who (+ fx (- (* sc (vector-ref a 0))) (* ss (vector-ref a 1)))))
  (define ty (scalar who (- fy (* ss (vector-ref a 0)) (* sc (vector-ref a 1)))))
  (make-atlas-transform-record (vector-immutable sc ss tx ty)))
(define (draw-atlas c im transforms sources #:colors [colors #f] #:blend-mode [blend 'modulate]
                   #:sampling [filter 'linear] #:cull [cull #f] #:paint [paint #f])
  (define who 'draw-atlas)
  (define ih (image-h who im))
  (define ts (geometry-list who transforms)) (define boxes (geometry-list who sources))
  (define n (length ts))
  ;; The base device expands each sprite to six vertices; protect that count too.
  (geometry-budget who (* n 6) (* n (if colors 36 32)))
  (unless (= n (length boxes)) (raise-arguments-error who "sprite transform/source counts must match"))
  (for ([t (in-list ts)]) (unless (atlas-transform? t) (raise-argument-error who "atlas-transform?" t)))
  (define bs (for/list ([b (in-list boxes)])
               (geometry-source-bounds who (geometry-rectangle who b) (image-width im) (image-height im))))
  (define cs (geometry-colors who colors n))
  (define mode (choice who blend blend-values))
  (define samp (sampling who filter))
  (define cbounds (and cull (geometry-rectangle who cull)))
  (define ph (and paint (paint-h who paint)))
  (call-on-canvas
   who c (if ph (list ih ph) (list ih))
   (lambda (cp ip . pps)
     (unless (zero? n)
       (define xb (flat-buffer (append* (map (lambda (t) (vector->list (atlas-transform-coefficients t))) ts)) _float))
       (define sb (flat-buffer (append* (for/list ([b (in-list bs)])
                                         (list (vector-ref b 0) (vector-ref b 1)
                                               (+ (vector-ref b 0) (vector-ref b 2))
                                               (+ (vector-ref b 1) (vector-ref b 3))))) _float))
       (define cb (vector-buffer cs _uint32))
       (define nb (and cbounds (native-rect cbounds)))
       (sk_canvas_draw_atlas cp ip xb sb cb n mode samp nb (if ph (car pps) #f))
       (void/reference-sink xb sb cb nb samp ts bs))))
  (void))

(struct cubic-patch (points colors texture-coordinates) #:transparent #:constructor-name make-cubic-patch-record)
(define (make-cubic-patch points #:colors [colors #f] #:texture-coordinates [tex #f])
  (define who 'make-cubic-patch)
  (define ps (geometry-points who points 12))
  (define cs (geometry-colors who colors 4))
  (define ts (and tex (geometry-points who tex 4)))
  (geometry-budget who 12 (+ 96 (if cs 16 0) (if ts 32 0)))
  (make-cubic-patch-record ps cs ts))
(define (draw-patch c patch paint #:blend-mode [blend 'modulate])
  (define who 'draw-patch)
  (unless (cubic-patch? patch) (raise-argument-error who "cubic-patch?" patch))
  (define mode (choice who blend blend-values))
  (geometry-budget who 12 (+ 96 (if (cubic-patch-colors patch) 16 0)
                               (if (cubic-patch-texture-coordinates patch) 32 0)))
  (call-on-canvas
   who c (list (paint-h who paint))
   (lambda (cp pp)
     (define pb (point-buffer (cubic-patch-points patch)))
     (define cb (vector-buffer (cubic-patch-colors patch) _uint32))
     (define tb (point-buffer (cubic-patch-texture-coordinates patch)))
     (sk_canvas_draw_patch cp pb cb tb mode pp)
     (void/reference-sink pb cb tb patch))))
