#lang racket/base
(require "../main.rkt")
(provide advanced-width advanced-height advanced-url draw-advanced-vector draw-advanced-layer
         draw-advanced-backdrop draw-advanced-initialization)
(define advanced-width 64)
(define advanced-height 48)
(define advanced-url "https://example.invalid/advanced-canvases")
(define (rectangle c x y w h color)
  (with-skia ([p (make-paint #:color color #:antialias? #f)]) (draw-rect c x y w h p)))
(define (draw-advanced-vector c)
  (rectangle c 8 8 24 24 'red) (rectangle c 36 16 20 16 'blue))
(define (draw-advanced-layer c)
  (with-skia ([p (make-paint #:color (rgba 0 0 0 128))])
    (call-with-canvas-layer-rec c (lambda () (rectangle c 8 8 24 24 'red)) #:paint p))
  (rectangle c 36 16 20 16 'blue))
(define (draw-advanced-initialization c)
  (rectangle c 8 8 24 24 'red)
  (with-skia ([p (make-paint #:blend-mode 'src)])
    (call-with-canvas-layer-rec c void #:paint p
      #:options (make-layer-options #:initialize-with-previous? #t)))
  (rectangle c 36 16 20 16 'blue))
(define (draw-advanced-backdrop c)
  (rectangle c 8 8 24 24 'red)
  (with-skia ([f (make-offset-image-filter 4 0)] [p (make-paint #:blend-mode 'src)])
    (call-with-canvas-layer-rec c void #:backdrop f #:paint p #:clip '(4 4 32 32)))
  (rectangle c 36 16 20 16 'blue))
