#lang racket/base
;; Exercise actual persistent Skia storage and the public bitmap% pixel API.
;; This suite is headless; the separate GUI suite must explicitly acquire a display.
(require rackunit racket/class racket/list
         (prefix-in rd: racket/draw) (prefix-in sk: "../main.rkt") "../dc.rkt"
         "../private/canvas-backing.rkt")
(provide canvas-dc-native-tests canvas-dc-native-test-count)

(define (with-backing proc [w 20] [h 12] [scale 1])
  (define backing (new canvas-backing% [width w] [height h] [backing-scale scale]))
  (dynamic-wind void (lambda () (proc backing (send backing get-dc))) (lambda () (send backing close))))
(define (rgba-pixel dc x y)
  (define-values (w h) (send dc get-pixel-size))
  (define bytes (send dc get-rgba-bytes #:premultiplied? #t))
  (bytes->list (subbytes bytes (* 4 (+ x (* y w))) (* 4 (+ 1 x (* y w))))))
(define (bitmap-argb-pixel bitmap x y)
  (define bytes (make-bytes 4))
  (send bitmap get-argb-pixels x y 1 1 bytes #f #t #:unscaled? #t)
  (bytes->list bytes))
(define (fill dc color [x 0] [y 0] [w 20] [h 12])
  (send dc set-pen "black" 1 'transparent) (send dc set-brush color 'solid)
  (send dc draw-rectangle x y w h))

(define canvas-dc-native-tests
  (test-suite
   "Canvas backing storage and native Skia-to-bitmap transfer (no GUI)"
   (test-case "headless backing has one real persistent Skia drawing context"
     (with-backing (lambda (backing dc)
       (check-true (skia-dc? dc)) (check-true (is-a? dc rd:dc<%>))
       (check-eq? dc (send backing get-dc))
       (check-equal? (call-with-values (lambda () (send dc get-size)) list) '(20.0 12.0))
       (check-false (with-handlers ([exn:fail? (lambda (_) #f)])
                      (module->namespace 'racket/gui/base) #t)))))
   (test-case "presentation picks up direct drawing through a previously retained DC"
     (with-backing (lambda (backing dc)
       (fill dc "red" 2 3 5 4)
       (define bitmap (send backing get-bitmap))
       (check-equal? (bitmap-argb-pixel bitmap 3 4) '(255 255 0 0))
       (check-equal? (bitmap-argb-pixel bitmap 0 0) '(0 0 0 0)))))
   (test-case "successive frames reuse the bitmap and replace old pixels"
     (with-backing (lambda (backing dc)
       (send backing paint! (lambda () (fill dc "red")))
       (define bitmap (send backing get-bitmap))
       (check-equal? (bitmap-argb-pixel bitmap 3 4) '(255 255 0 0))
       (send backing paint! (lambda () (fill dc "blue")))
       (check-eq? (send backing get-bitmap) bitmap)
       (check-equal? (bitmap-argb-pixel bitmap 3 4) '(255 0 0 255)))))
   (test-case "premultiplied partial alpha reaches bitmap channels without alpha multiplication twice"
     (with-backing (lambda (backing dc)
       (send dc set-alpha 0.5)
       (fill dc (make-object rd:color% 100 200 240 0.5) 2 3 5 4)
       (define source (rgba-pixel dc 3 4))
       (for ([actual (in-list source)] [expected '(25 50 60 64)]) (check-= actual expected 1))
       (define bitmap (send backing get-bitmap))
       (check-equal? (bitmap-argb-pixel bitmap 3 4)
                     (list (fourth source) (first source) (second source) (third source)))
       (check-equal? (bitmap-argb-pixel bitmap 0 0) '(0 0 0 0)))))
   (test-case "resize and backing scale preserve the DC and produce scaled physical pixels"
     (with-backing (lambda (backing dc)
       (check-true (send backing resize! 31 23 2))
       (check-eq? dc (send backing get-dc))
       (check-equal? (call-with-values (lambda () (send dc get-pixel-size)) list) '(62 46))
       (fill dc "red" 2 3 4 5)
       (define bitmap (send backing get-bitmap))
       (check-equal? (send bitmap get-backing-scale) 2.0)
       (check-equal? (bitmap-argb-pixel bitmap 4 6) '(255 255 0 0))
       (check-equal? (bitmap-argb-pixel bitmap 3 6) '(0 0 0 0)))))
   (test-case "resize preserves frozen clipping coordinates and the selected-region lock"
     (with-backing (lambda (backing dc)
       (send dc set-origin 3 4) (send dc set-clipping-rect 1 2 5 4)
       (define region (send dc get-clipping-region))
       (send dc set-origin 100 100)
       (send backing resize! 31 23 2)
       (check-eq? (send dc get-clipping-region) region)
       (check-exn exn:fail? (lambda () (send region set-rectangle 0 0 1 1)))
       (send dc set-background "red") (send dc clear)
       (check-equal? (rgba-pixel dc 8 12) '(255 0 0 255))
       (check-equal? (rgba-pixel dc 7 12) '(0 0 0 0))
       (check-equal? (rgba-pixel dc 18 12) '(0 0 0 0)))))
   (test-case "new storage starts transparent and retained snapshots survive resize and close"
     (define image #f)
     (with-backing (lambda (backing dc)
       (fill dc "red") (set! image (send dc snapshot))
       (send backing resize! 21 13 1)
       (check-equal? (rgba-pixel dc 3 4) '(0 0 0 0))))
     (sk:with-skia ([im image])
       (check-equal? (sk:image-width im) 20) (check-equal? (sk:image-height im) 12)
       (check-equal? (subbytes (sk:image->rgba-bytes im) 0 4) (bytes 255 0 0 255))))
   (test-case "allocation-budget rejection leaves the current frame and geometry intact"
     (with-backing (lambda (backing dc)
       (fill dc "blue")
       (define before (send dc get-rgba-bytes))
       (define bitmap (send backing get-bitmap))
       (parameterize ([sk:current-skia-byte-limit 1])
         (check-exn exn:fail? (lambda () (send backing resize! 21 13 2))))
       (check-equal? (send dc get-rgba-bytes) before)
       (check-equal? (call-with-values (lambda () (send dc get-size)) list) '(20.0 12.0))
       (check-eq? (send backing get-dc) dc) (check-eq? (send backing get-bitmap) bitmap))))
   (test-case "paint exception discards unfinished alpha children and the next paint can reuse the root"
     (with-backing (lambda (backing dc)
       (check-exn #rx"deliberate paint failure"
         (lambda () (send backing paint!
           (lambda () (send dc start-alpha 0.5) (fill dc "red")
             (error 'callback "deliberate paint failure")))))
       (check-equal? (rgba-pixel dc 3 4) '(255 255 255 255))
       (send dc end-alpha)
       (check-equal? (rgba-pixel dc 3 4) '(255 255 255 255))
       (send backing paint! (lambda () (fill dc "blue")) #f)
       (check-equal? (bitmap-argb-pixel (send backing get-bitmap) 3 4) '(255 0 0 255)))))
   (test-case "automatic frame clear covers the full target despite saved clip transform and alpha"
     (with-backing (lambda (backing dc)
       (fill dc "blue")
       (send dc set-clipping-rect 2 3 5 4) (send dc set-alpha 0.25) (send dc set-origin 100 100)
       (define region (send dc get-clipping-region))
       (send backing paint! void)
       (check-equal? (rgba-pixel dc 0 0) '(255 255 255 255))
       (check-equal? (rgba-pixel dc 3 4) '(255 255 255 255))
       (check-equal? (rgba-pixel dc 19 11) '(255 255 255 255))
       (check-eq? (send dc get-clipping-region) region) (check-equal? (send dc get-alpha) 0.25)
       (check-equal? (call-with-values (lambda () (send dc get-origin)) list) '(100.0 100.0)))))
   (test-case "manual clearing leaves previously drawn pixels available to the callback"
     (with-backing (lambda (backing dc)
       (fill dc "red")
       (send backing paint! (lambda () (fill dc "blue" 2 3 5 4)) #f)
       (define bitmap (send backing get-bitmap))
       (check-equal? (bitmap-argb-pixel bitmap 0 0) '(255 255 0 0))
       (check-equal? (bitmap-argb-pixel bitmap 3 4) '(255 0 0 255)))))
   (test-case "geometry change replaces presentation bitmap while unchanged geometry reuses it"
     (with-backing (lambda (backing dc)
       (define old (send backing get-bitmap))
       (check-false (send backing resize! 20 12 1))
       (check-eq? (send backing get-bitmap) old)
       (send backing resize! 21 13 1)
       (define next (send backing get-bitmap))
       (check-not-eq? next old) (check-eq? (send backing get-bitmap) next))))
   (test-case "fractional backing dimensions round up and transfer the last physical pixel"
     (with-backing (lambda (backing dc)
       (check-equal? (call-with-values (lambda () (send dc get-pixel-size)) list) '(47 35))
       (send dc set-background "blue") (send dc clear)
       (check-equal? (bytes-length (send dc get-rgba-bytes)) (* 4 47 35))
       (define bitmap (send backing get-bitmap))
       (check-equal? (bitmap-argb-pixel bitmap 46 34) '(255 0 0 255))) 31 23 1.5))
   (test-case "close invalidates the retained DC and releases its selected-style locks once"
     (with-backing (lambda (backing dc)
       (define pen (rd:make-pen #:immutable? #f))
       (send dc set-pen pen) (send backing close) (send backing close)
       (check-true (send backing closed?)) (check-false (send dc ok?))
       (check-not-exn (lambda () (send pen set-width 4)))
       (for ([thunk (list (lambda () (send backing get-dc)) (lambda () (send backing get-bitmap))
                          (lambda () (send backing resize! 21 13 1))
                          (lambda () (send backing paint! void)))])
         (check-exn exn:fail? thunk)))))))

(define canvas-dc-native-test-count 14)
(module+ main
  (require rackunit/text-ui)
  (sk:skia-check!)
  (define failures (run-tests canvas-dc-native-tests))
  (printf "canvas-dc-native: ~a cases, ~a failures; native Skia pixels, no GUI.\n"
          canvas-dc-native-test-count failures)
  (exit (if (zero? failures) 0 1)))
