#lang racket/base
;; Headless lifecycle tests use the production DC with a recording renderer.
;; They do not claim native pixels or initialize racket/gui/base.
(require rackunit racket/class racket/list racket/control
         (prefix-in rd: racket/draw)
         "../private/dc-class.rkt" "../private/dc-support.rkt"
         (submod "../private/dc-class.rkt" canvas)
         "../private/canvas-backing.rkt"
         (only-in "../private/check.rkt" current-skia-byte-limit))
(provide canvas-dc-pure-tests canvas-dc-pure-test-count)

(define (recording-renderer [fail-releases '()])
  (define events (box '()))
  (define fail-next (box #f))
  (define next 0)
  (define pixels (make-hasheqv))
  (define (event . xs) (set-box! events (cons xs (unbox events))) (void))
  (define renderer
    (dc-renderer/alpha
     (lambda (w h)
       (define fail (unbox fail-next)) (set-box! fail-next #f)
       (case fail
         [(exception) (error 'create "injected allocation failure")]
         [(empty) #f]
         [else (set! next (add1 next)) (hash-set! pixels next (make-bytes (* 4 w h)))
               (event 'create next w h) next]))
     (lambda (s) (event 'close s)
       (when (memv s fail-releases) (error 'close "injected retirement failure")))
     (lambda (s command) (event 'path s command))
     (lambda (s clip color erase?) (event 'clear s clip color erase?))
     values (lambda (s p?) (event 'rgba s p?) (bytes-copy (hash-ref pixels s))) (lambda (s) (bytes s))
     (lambda (_s _request) (values 10.0 20.0 3.0 1.0))
     (lambda (s . xs) (apply event 'text s xs)) (lambda (_s _font _c) #t)
     (lambda (s . xs) (apply event 'bitmap s xs))
     (lambda (s . xs) (apply event 'copy s xs))
     (lambda (parent child clip alpha) (event 'merge parent child clip alpha))))
  (values renderer events fail-next))
(define (fresh [fail-releases '()])
  (define-values (renderer events fail-next) (recording-renderer fail-releases))
  (values (new (make-skia-dc-class renderer) [width 20] [height 12]) events fail-next))
(define-syntax-rule (with-fresh (dc e fail) body ...)
  (let-values ([(dc e fail) (fresh)])
    (dynamic-wind void (lambda () body ...) (lambda () (send dc close)))))
(define (events-of events kind)
  (filter (lambda (x) (eq? (car x) kind)) (reverse (unbox events))))
(define (fill dc)
  (send dc set-pen "black" 1 'transparent)
  (send dc set-brush "red" 'solid)
  (send dc draw-rectangle 1 2 3 4))
(define (size dc) (call-with-values (lambda () (send dc get-size)) list))
(define (pixel-size dc) (call-with-values (lambda () (send dc get-pixel-size)) list))

(define canvas-dc-pure-tests
  (test-suite
   "Canvas DC ownership, resizing, paint recovery and direct pixel bridge (headless)"
   (test-case "canvas lifecycle entry points are private member identities"
     (with-fresh (dc e fail)
       (check-false (object-method-arity-includes? dc 'dc-resize-backing! 3))
       (check-false (object-method-arity-includes? dc 'call-with-dc-canvas-paint 1))
       (check-false (object-method-arity-includes? dc 'dc-clear-backing! 0))))
   (test-case "same geometry and numerically equal backing scale allocate nothing"
     (with-fresh (dc e fail)
       (check-false (dc-resize-backing! dc 20 12 1.0))
       (check-false (dc-resize-backing! dc 20 12 1))
       (check-equal? (reverse (unbox e)) '((create 1 20 12)))))
   (test-case "resize retains DC identity and retires its old target once"
     (with-fresh (dc e fail)
       (define retained dc)
       (check-true (dc-resize-backing! dc 31 23 1.5))
       (check-eq? dc retained) (check-equal? (size dc) '(31.0 23.0))
       (check-equal? (pixel-size dc) '(47 35))
       (check-equal? (send dc get-backing-scale) 1.5)
       (check-equal? (send dc snapshot) 2)
       (check-equal? (reverse (unbox e)) '((create 1 20 12) (create 2 47 35) (close 1)))))
   (test-case "logical geometry and scale update even when physical dimensions agree"
     (with-fresh (dc e fail)
       (check-true (dc-resize-backing! dc 10 6 2))
       (check-equal? (size dc) '(10.0 6.0)) (check-equal? (pixel-size dc) '(20 12))
       (check-equal? (send dc get-backing-scale) 2.0)))
   (test-case "invalid logical dimensions reject without touching the live target"
     (with-fresh (dc e fail)
       (for ([bad (list 0 -1 1/2 2.0 #f +inf.0)])
         (check-exn exn:fail? (lambda () (dc-resize-backing! dc bad 12 1)))
         (check-exn exn:fail? (lambda () (dc-resize-backing! dc 20 bad 1))))
       (check-equal? (send dc snapshot) 1)
       (check-equal? (size dc) '(20.0 12.0))
       (check-equal? (length (events-of e 'create)) 1)))
   (test-case "invalid backing scale rejects before allocation"
     (with-fresh (dc e fail)
       (for ([bad (list 0 -1 #f +nan.0 +inf.0)])
         (check-exn exn:fail? (lambda () (dc-resize-backing! dc 20 12 bad))))
       (check-equal? (send dc get-backing-scale) 1.0)
       (check-equal? (length (events-of e 'create)) 1)))
   (test-case "backed transform overflow rejects before target replacement"
     (with-fresh (dc e fail)
       (send dc set-scale 3e38 1)
       (define before (send dc get-transformation))
       (check-exn exn:fail? (lambda () (dc-resize-backing! dc 20 12 2)))
       (check-equal? (send dc get-transformation) before)
       (check-equal? (send dc get-backing-scale) 1.0)
       (check-equal? (events-of e 'close) '())))
   (test-case "frozen clip overflow rejects before target replacement"
     (with-fresh (dc e fail)
       (send dc set-clipping-rect 3e38 0 1 1)
       (define region (send dc get-clipping-region))
       (check-exn exn:fail? (lambda () (dc-resize-backing! dc 20 12 2)))
       (check-eq? region (send dc get-clipping-region))
       (check-equal? (events-of e 'close) '())))
   (test-case "replacement budget accounts for both simultaneously live roots"
     (with-fresh (dc e fail)
       (parameterize ([current-skia-byte-limit (* 4 21 12)])
         (check-exn exn:fail? (lambda () (dc-resize-backing! dc 21 12 1))))
       (check-equal? (send dc snapshot) 1)
       (check-equal? (length (events-of e 'create)) 1)
       (check-equal? (events-of e 'close) '())))
   (test-case "no-op resize is allowed after the allocation budget is lowered"
     (with-fresh (dc e fail)
       (parameterize ([current-skia-byte-limit 1])
         (check-false (dc-resize-backing! dc 20 12 1)))
       (check-equal? (length (events-of e 'create)) 1)))
   (test-case "allocator exception leaves geometry and root usable"
     (with-fresh (dc e fail)
       (set-box! fail 'exception)
       (check-exn #rx"allocation" (lambda () (dc-resize-backing! dc 22 14 2)))
       (check-equal? (size dc) '(20.0 12.0)) (check-equal? (send dc snapshot) 1)
       (fill dc) (check-equal? (second (last (events-of e 'path))) 1)
       (check-equal? (events-of e 'close) '())))
   (test-case "allocator returning no target also leaves the old target usable"
     (with-fresh (dc e fail)
       (set-box! fail 'empty)
       (check-exn exn:fail? (lambda () (dc-resize-backing! dc 22 14 1)))
       (check-equal? (send dc snapshot) 1)
       (check-equal? (events-of e 'close) '())))
   (test-case "resize preserves selected styles and the complete logical drawing state"
     (with-fresh (dc e fail)
       (define p (rd:make-pen #:color "red" #:width 3 #:immutable? #f))
       (define b (rd:make-brush #:color "blue" #:immutable? #f))
       (define f (rd:make-font #:size 17 #:family 'modern))
       (send dc set-pen p) (send dc set-brush b) (send dc set-font f)
       (send dc set-origin 3 4) (send dc set-scale 2 3) (send dc set-rotation 0.2)
       (send dc set-alpha 0.25) (send dc set-smoothing 'aligned)
       (send dc set-background "red") (send dc set-text-foreground "blue")
       (send dc set-text-background "green") (send dc set-text-mode 'solid)
       (define transformation (send dc get-transformation))
       (dc-resize-backing! dc 31 23 2)
       (check-eq? (send dc get-pen) p) (check-eq? (send dc get-brush) b) (check-eq? (send dc get-font) f)
       (check-equal? (send dc get-transformation) transformation)
       (check-equal? (send dc get-alpha) 0.25) (check-eq? (send dc get-smoothing) 'aligned)
       (check-equal? (send (send dc get-background) red) 255)
       (check-equal? (send (send dc get-text-foreground) blue) 255)
       (check-equal? (send (send dc get-text-background) green) 255)
       (check-eq? (send dc get-text-mode) 'solid)
       (check-exn exn:fail? (lambda () (send p set-width 8)))
       (check-exn exn:fail? (lambda () (send b set-color "red")))))
   (test-case "repeated resizing neither drops nor leaks selected-style locks"
     (with-fresh (dc e fail)
       (define p (rd:make-pen #:immutable? #f)) (define b (rd:make-brush #:immutable? #f))
       (send dc set-pen p) (send dc set-brush b)
       (for ([i (in-range 5)])
         (dc-resize-backing! dc (+ 21 i) 14 1)
         (check-eq? (send dc get-pen) p) (check-eq? (send dc get-brush) b)
         (check-exn exn:fail? (lambda () (send p set-width 8))))
       (send dc close)
       (check-not-exn (lambda () (send p set-width 8) (send b set-color "red")))))
   (test-case "associated clipping region retains DC identity and its selection lock"
     (with-fresh (dc e fail)
       (define region (new rd:region% [dc dc]))
       (send region set-rectangle 1 2 5 6) (send dc set-clipping-region region)
       (dc-resize-backing! dc 31 23 2)
       (check-eq? (send region get-dc) dc) (check-eq? (send dc get-clipping-region) region)
       (check-exn exn:fail? (lambda () (send region set-rectangle 0 0 1 1)))
       (send dc close)
       (check-not-exn (lambda () (send region set-rectangle 0 0 1 1)))))
   (test-case "resize scales the frozen physical clip without recapturing the current transform"
     (with-fresh (dc e fail)
       (send dc set-origin 3 4) (send dc set-clipping-rect 1 2 5 6)
       (send dc clear)
       (define first-clip (third (last (events-of e 'clear))))
       (send dc set-origin 70 80)
       (dc-resize-backing! dc 31 23 2) (send dc clear)
       (check-equal? (third (last (events-of e 'clear))) (dc-scale-clip first-clip 2))))
   (test-case "successful resize discards every unfinished alpha layer without merging"
     (with-fresh (dc e fail)
       (send dc set-alpha 0.25) (send dc start-alpha 0.5) (send dc start-alpha 0.75)
       (dc-resize-backing! dc 31 23 1)
       (check-equal? (send dc snapshot) 4) (check-equal? (send dc get-alpha) 0.25)
       (check-equal? (events-of e 'close) '((close 3) (close 2) (close 1)))
       (send dc end-alpha) (check-equal? (events-of e 'merge) '())))
   (test-case "failed resize preserves the live alpha layer and its later merge"
     (with-fresh (dc e fail)
       (send dc set-alpha 0.25) (send dc start-alpha 0.5)
       (set-box! fail 'exception)
       (check-exn #rx"allocation" (lambda () (dc-resize-backing! dc 31 23 1)))
       (fill dc) (check-equal? (second (last (events-of e 'path))) 2)
       (check-equal? (events-of e 'close) '())
       (send dc end-alpha) (check-equal? (last (car (events-of e 'merge))) 0.125)
       (check-equal? (send dc get-alpha) 0.25)))
   (test-case "lifecycle operations reject a foreign thread before native work"
     (with-fresh (dc e fail)
       (for ([operation (list (lambda () (dc-resize-backing! dc 21 12 1))
                              (lambda () (dc-clear-backing! dc))
                              (lambda () (call-with-dc-canvas-paint dc void)))])
         (define result (box #f))
         (thread-wait (thread (lambda () (with-handlers ([exn:fail? (lambda (e) (set-box! result e))]) (operation)))))
         (check-true (exn:fail? (unbox result))))
       (check-equal? (reverse (unbox e)) '((create 1 20 12)))))
   (test-case "all private lifecycle operations reject a closed DC"
     (with-fresh (dc e fail)
       (send dc close)
       (for ([operation (list (lambda () (dc-resize-backing! dc 21 12 1))
                              (lambda () (dc-clear-backing! dc))
                              (lambda () (call-with-dc-canvas-paint dc void)))])
         (check-exn #rx"closed" operation))))
   (test-case "paint scope preserves multiple return values and deliberate ordinary state changes"
     (with-fresh (dc e fail)
       (check-equal?
        (call-with-values
         (lambda () (call-with-dc-canvas-paint dc (lambda () (send dc set-alpha 0.25) (send dc set-origin 3 4) (values 'a 'b))))
         list) '(a b))
       (check-equal? (send dc get-alpha) 0.25)
       (check-equal? (call-with-values (lambda () (send dc get-origin)) list) '(3.0 4.0))))
   (test-case "normal callback exit discards unfinished groups and restores root alpha and clip"
     (with-fresh (dc e fail)
       (send dc set-alpha 0.25) (send dc set-clipping-rect 1 2 5 6) (send dc clear)
       (define clip (third (last (events-of e 'clear))))
       (call-with-dc-canvas-paint dc
         (lambda () (send dc start-alpha 0.5) (send dc start-alpha 0.5) (fill dc)))
       (check-equal? (send dc get-alpha) 0.25)
       (check-equal? (events-of e 'close) '((close 3) (close 2)))
       (check-equal? (events-of e 'merge) '())
       (send dc clear) (check-equal? (third (last (events-of e 'clear))) clip)
       (fill dc) (check-equal? (second (last (events-of e 'path))) 1)))
   (test-case "callback exception retires layers and leaves the persistent root reusable"
     (with-fresh (dc e fail)
       (check-exn #rx"paint failure"
         (lambda () (call-with-dc-canvas-paint dc
           (lambda () (send dc start-alpha 0.5) (fill dc) (error 'callback "paint failure")))))
       (check-equal? (events-of e 'close) '((close 2))) (check-equal? (events-of e 'merge) '())
       (call-with-dc-canvas-paint dc (lambda () (fill dc)))
       (check-equal? (second (last (events-of e 'path))) 1)))
   (test-case "continuation escape retires unfinished groups"
     (with-fresh (dc e fail)
       (check-eq?
        (let/ec escape
          (call-with-dc-canvas-paint dc (lambda () (send dc start-alpha 0.5) (escape 'escaped))))
        'escaped)
       (check-equal? (events-of e 'close) '((close 2)))
       (fill dc) (check-equal? (second (last (events-of e 'path))) 1)))
   (test-case "captured continuation cannot reenter a completed paint scope"
     (with-fresh (dc e fail)
       (define resume #f)
       (call-with-dc-canvas-paint dc
         (lambda () (call/cc (lambda (k) (set! resume k) (void)))))
       (check-exn exn:fail? (lambda () (resume 'reentry)))
       (call-with-dc-canvas-paint dc (lambda () (fill dc)))
       (check-equal? (length (events-of e 'path)) 1)))
   (test-case "paint cleanup attempts every child release even when retirement throws"
     (define-values (dc e fail) (fresh '(2 3)))
     (dynamic-wind void
       (lambda ()
         (check-exn #rx"retirement failure"
           (lambda () (call-with-dc-canvas-paint dc
             (lambda () (send dc start-alpha 0.5) (send dc start-alpha 0.5)))))
         (check-equal? (events-of e 'close) '((close 3) (close 2)))
         (check-equal? (events-of e 'merge) '())
         (fill dc) (check-equal? (second (last (events-of e 'path))) 1))
       (lambda () (send dc close))))
   (test-case "resize retirement failure commits the new root and attempts every old release"
     (define-values (dc e fail) (fresh '(1 2 3)))
     (dynamic-wind void
       (lambda ()
         (send dc set-alpha 0.25) (send dc start-alpha 0.5) (send dc start-alpha 0.5)
         (check-exn #rx"retirement failure" (lambda () (dc-resize-backing! dc 31 23 1)))
         (check-equal? (events-of e 'close) '((close 3) (close 2) (close 1)))
         (check-equal? (send dc snapshot) 4) (check-equal? (send dc get-alpha) 0.25)
         (check-equal? (size dc) '(31.0 23.0))
         (fill dc) (check-equal? (second (last (events-of e 'path))) 4))
       (lambda () (send dc close))))
   (test-case "paint scope discards groups left open before entry"
     (with-fresh (dc e fail)
       (send dc set-alpha 0.25) (send dc start-alpha 0.5)
       (call-with-dc-canvas-paint dc (lambda () (fill dc)))
       (check-equal? (events-of e 'close) '((close 2)))
       (check-equal? (events-of e 'merge) '())
       (check-equal? (second (last (events-of e 'path))) 1)
       (check-equal? (send dc get-alpha) 0.25)))
   (test-case "nested paint resize and close reject while a paint callback owns the target"
     (with-fresh (dc e fail)
       (call-with-dc-canvas-paint dc
         (lambda ()
           (check-exn exn:fail? (lambda () (call-with-dc-canvas-paint dc void)))
           (check-exn exn:fail? (lambda () (dc-resize-backing! dc 21 12 1)))
           (check-exn exn:fail? (lambda () (send dc close)))
           (fill dc)))
       (check-true (send dc ok?)) (check-equal? (events-of e 'close) '())))
   (test-case "canvas clear ignores transform clip and opacity while preserving their values"
     (with-fresh (dc e fail)
       (send dc set-origin 70 80) (send dc set-alpha 0.25)
       (send dc set-clipping-rect 1 2 5 6) (send dc set-background "red")
       (define region (send dc get-clipping-region))
       (define transformation (send dc get-transformation))
       (dc-clear-backing! dc)
       (define clears (events-of e 'clear))
       (check-equal? (length clears) 2)
       (check-true (last (first clears))) (check-false (last (second clears)))
       (check-false (third (first clears))) (check-false (third (second clears)))
       (check-equal? (fourth (second clears)) '#(255 0 0 1.0))
       (check-equal? (send dc get-alpha) 0.25) (check-eq? (send dc get-clipping-region) region)
       (check-equal? (send dc get-transformation) transformation)))
   (test-case "canvas clear rejects a live group without merging or clearing it"
     (with-fresh (dc e fail)
       (send dc start-alpha 0.5)
       (check-exn exn:fail? (lambda () (dc-clear-backing! dc)))
       (check-equal? (events-of e 'clear) '()) (check-equal? (events-of e 'merge) '())))
   (test-case "RGBA to ARGB bridge reorders unequal premultiplied channels exactly"
     (define rgba (bytes 17 31 47 63 100 150 200 255 0 0 0 0))
     (define before (bytes-copy rgba)) (define argb (make-bytes (bytes-length rgba) 255))
     (check-true (void? (rgba->argb! rgba argb)))
     (check-equal? argb (bytes 63 17 31 47 255 100 150 200 0 0 0 0))
     (check-equal? rgba before))
   (test-case "RGBA to ARGB bridge can safely alias its source and destination"
     (define pixel (bytes 17 31 47 63 100 150 200 255))
     (rgba->argb! pixel pixel)
     (check-equal? pixel (bytes 63 17 31 47 255 100 150 200)))
   (test-case "bridge rejects malformed input before changing destination storage"
     (define destination (make-bytes 8 91))
     (for ([source (list #f (bytes 1 2 3) (make-bytes 4) (make-bytes 12))])
       (check-exn exn:fail? (lambda () (rgba->argb! source destination)))
       (check-equal? destination (make-bytes 8 91)))
     (check-exn exn:fail? (lambda () (rgba->argb! (make-bytes 4) #"\0\0\0\0"))))
   (test-case "bridge accepts empty buffers"
     (check-true (void? (rgba->argb! #"" (make-bytes 0)))))
   (test-case "backing close records logical closure even when native retirement throws"
     (define-values (renderer e fail) (recording-renderer '(1)))
     (define backing (new canvas-backing% [width 20] [height 12] [dc-class (make-skia-dc-class renderer)]))
     (define dc (send backing get-dc))
     (send backing get-bitmap)
     (check-exn #rx"retirement failure" (lambda () (send backing close)))
     (check-true (send backing closed?)) (check-false (send dc ok?))
     (check-not-exn (lambda () (send backing close)))
     (check-equal? (events-of e 'close) '((close 1)))
     (check-exn #rx"closed" (lambda () (send backing get-bitmap))))
   (test-case "rejected backing close during paint preserves reusable presentation storage"
     (define-values (renderer e fail) (recording-renderer))
     (define backing (new canvas-backing% [width 20] [height 12] [dc-class (make-skia-dc-class renderer)]))
     (dynamic-wind void
       (lambda ()
         (define before (send backing get-bitmap))
         (send backing paint! (lambda () (check-exn exn:fail? (lambda () (send backing close)))) #f)
         (check-false (send backing closed?))
         (check-eq? (send backing get-bitmap) before)
         (check-not-exn (lambda () (send backing paint! void))))
       (lambda () (send backing close))))
   (test-case "bridge follows committed geometry after an old target retirement failure"
     (define-values (renderer e fail) (recording-renderer '(1)))
     (define backing (new canvas-backing% [width 20] [height 12] [dc-class (make-skia-dc-class renderer)]))
     (dynamic-wind void
       (lambda ()
         (define dc (send backing get-dc)) (define old (send backing get-bitmap))
         (check-exn #rx"retirement failure" (lambda () (send backing resize! 31 23 1)))
         (check-eq? (send backing get-dc) dc) (check-equal? (size dc) '(31.0 23.0))
         (define next (send backing get-bitmap))
         (check-not-eq? next old) (check-equal? (send next get-width) 31) (check-equal? (send next get-height) 23)
         (check-eq? (send backing get-bitmap) next))
       (lambda () (send backing close))))))

(define canvas-dc-pure-test-count 38)
(module+ main
  (require rackunit/text-ui)
  (define failures (run-tests canvas-dc-pure-tests))
  (printf "canvas-dc-pure: ~a cases, ~a failures; no native pixels or GUI.\n"
          canvas-dc-pure-test-count failures)
  (exit (if (zero? failures) 0 1)))
