#lang racket/base
(require rackunit rackunit/text-ui racket/list
         "../main.rkt" "codec-incremental-fixtures.rkt"
         (only-in "codec-scanline-fixtures.rkt" scanline-fixture-bmp)
         (only-in "../private/codec-incremental-source.rkt" incremental-source-count))
(provide codec-incremental-native-tests codec-incremental-native-test-count)
(define parts (incremental-fixture-parts))
(define (prefix s)
  (codec-incremental-feed! s (bytes-append (car parts) (cadr parts)))
  (codec-incremental-step! s))
(define (finish s [remaining (cddr parts)])
  (for ([p (in-list remaining)] [i (in-naturals)])
    (codec-incremental-feed! s p #:final? (= i (sub1 (length remaining))))
    (codec-incremental-step! s))
  (check-equal? (codec-incremental-state s) 'complete))
(define (complete s)
  (codec-incremental-feed! s (incremental-fixture-bytes) #:final? #t)
  (codec-incremental-step! s))
(define (snapshot-rgba s)
  (with-skia ([b (incremental-snapshot->raster-buffer (codec-incremental-snapshot s))])
    (raster-buffer->rgba-bytes b)))
(define (wrong-thread thunk)
  (define answer (box #f))
  (thread-wait (thread (lambda ()
    (set-box! answer (with-handlers ([exn:fail? values]) (thunk) 'unexpected-success)))))
  (check-pred exn:fail? (unbox answer)))
(define codec-incremental-native-tests
  (test-suite "Retained incremental codec, feed framing and pixel ownership"
    (test-case "session is an ordinary owned resource"
      (define s (make-codec-incremental))
      (check-true (skia-resource? s)) (check-true (codec-incremental-session? s))
      (check-equal? (codec-incremental-state s) 'awaiting-input)
      (skia-close! s) (check-true (skia-closed? s)) (check-equal? (codec-incremental-state s) 'closed))
    (test-case "empty nonfinal input requests more input without decoding"
      (with-skia ([s (make-codec-incremental)])
        (check-equal? (incremental-progress-state (codec-incremental-step! s)) 'needs-input)
        (check-equal? (hash-ref (codec-incremental-statistics s) 'decode-calls) 0)))
    (test-case "empty final input is terminal incomplete"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s #"" #:final? #t)
        (check-equal? (incremental-progress-state (codec-incremental-step! s)) 'incomplete)))
    (test-case "a sealed PNG decodes to independently known pixels"
      (with-skia ([s (make-codec-incremental)])
        (check-equal? (incremental-progress-state (complete s)) 'complete)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "first row is available before the remaining input"
      (with-skia ([s (make-codec-incremental)])
        (define p (prefix s))
        (check-equal? (incremental-progress-state p) 'needs-input)
        (check-equal? (incremental-progress-initialized-rows p) 1)
        (define bytes (incremental-snapshot-bytes (codec-incremental-snapshot s)))
        (check-equal? (subbytes bytes 0 32) (subbytes (incremental-fixture-pixels) 0 32))
        (check-equal? (subbytes bytes 32) (make-bytes (* 32 5) 0))))
    (test-case "one decoder start and one destination survive all row chunks"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (finish s)
        (define stats (codec-incremental-statistics s))
        (check-equal? (hash-ref stats 'header-attempts) 1)
        (check-equal? (hash-ref stats 'start-calls) 1)
        (check-equal? (hash-ref stats 'decode-calls) 6)
        (check-equal? (hash-ref stats 'pixel-allocations) 1)
        (check-false (hash-ref stats 'decoder-retained?))
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "repeating step without new visible bytes does not call native code"
      (with-skia ([s (make-codec-incremental)])
        (define p (prefix s)) (define before (codec-incremental-statistics s))
        (check-equal? (codec-incremental-step! s) p)
        (check-equal? (codec-incremental-statistics s) before)))
    (test-case "partial next IDAT cannot desynchronize the decoder"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (define next (caddr parts))
        (codec-incremental-feed! s (subbytes next 0 15))
        (check-equal? (incremental-progress-initialized-rows (codec-incremental-step! s)) 1)
        (check-equal? (hash-ref (codec-incremental-statistics s) 'decode-calls) 1)
        (codec-incremental-feed! s (subbytes next 15))
        (check-equal? (incremental-progress-initialized-rows (codec-incremental-step! s)) 2)
        (finish s (cdddr parts))))
    (test-case "three-byte fragment feeding reaches genuine native completion"
      (with-skia ([s (make-codec-incremental)])
        (define data (incremental-fixture-bytes))
        (let loop ([at 0])
          (when (and (< at (bytes-length data)) (not (eq? (codec-incremental-state s) 'complete)))
            (define end (min (bytes-length data) (+ at 3)))
            (codec-incremental-feed! s (subbytes data at end) #:final? (= end (bytes-length data)))
            (codec-incremental-step! s) (loop end)))
        (check-equal? (codec-incremental-state s) 'complete)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))
        (check-equal? (hash-ref (codec-incremental-statistics s) 'start-calls) 1)))
    (test-case "mutating supplied bytes cannot corrupt the retained input"
      (with-skia ([s (make-codec-incremental)])
        (define data (bytes-copy (incremental-fixture-bytes)))
        (codec-incremental-feed! s data #:final? #t) (bytes-fill! data 0)
        (check-equal? (incremental-progress-state (codec-incremental-step! s)) 'complete)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "source header can be retried without restarting a pixel decode"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s (car parts))
        (check-equal? (incremental-progress-state (codec-incremental-step! s)) 'needs-input)
        (codec-incremental-feed! s (cadr parts)) (codec-incremental-step! s)
        (finish s)
        (define stats (codec-incremental-statistics s))
        (check-equal? (hash-ref stats 'header-attempts) 2)
        (check-equal? (hash-ref stats 'start-calls) 1)
        (check-equal? (hash-ref stats 'stream-creations) (hash-ref stats 'stream-destructions))))
    (test-case "partial snapshots remain immutable as later rows decode"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (define earlier (codec-incremental-snapshot s))
        (check-true (immutable? (incremental-snapshot-bytes earlier)))
        (finish s)
        (check-equal? (incremental-progress-state (incremental-snapshot-progress earlier)) 'needs-input)
        (check-equal? (subbytes (incremental-snapshot-bytes earlier) 32) (make-bytes 160 0))))
    (test-case "complete snapshot outlives session closure"
      (define s (make-codec-incremental)) (complete s)
      (define image (codec-incremental-snapshot s)) (skia-close! s) (collect-garbage)
      (with-skia ([b (incremental-snapshot->raster-buffer image)])
        (check-equal? (raster-buffer->rgba-bytes b) (incremental-fixture-pixels))))
    (test-case "row padding stays initialized and unmodified"
      (with-skia ([s (make-codec-incremental #:row-bytes 44)])
        (prefix s) (finish s)
        (define snap (codec-incremental-snapshot s))
        (check-equal? (incremental-snapshot-row-bytes snap) 44)
        (for ([y (in-range 6)])
          (check-equal? (subbytes (incremental-snapshot-bytes snap) (+ (* y 44) 32) (* (add1 y) 44)) (make-bytes 12 0)))
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "BGRA destination is explicit and preserved"
      (with-skia ([s (make-codec-incremental #:color-type 'bgra-8888)])
        (complete s)
        (check-equal? (image-info-color-type (codec-incremental-info s)) 'bgra-8888)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "premultiplied destination uses the requested description"
      (with-skia ([s (make-codec-incremental #:alpha-type 'premul)])
        (complete s) (check-equal? (image-info-alpha-type (codec-incremental-info s)) 'premul)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "detached sRGB metadata is preserved"
      (with-skia ([s (make-codec-incremental)])
        (complete s) (check-equal? (image-info-color-space (codec-incremental-info s)) 'srgb)
        (check-equal? (codec-incremental-origin s) 'top-left)))
    (test-case "interlaced initialized rows are not mistaken for completion"
      (with-skia ([s (make-codec-incremental)])
        (define chunks (incremental-fixture-parts #:interlaced? #t))
        (codec-incremental-feed! s (bytes-append (car chunks) (cadr chunks)))
        (check-equal? (incremental-progress-state (codec-incremental-step! s)) 'needs-input)
        (for ([p (in-list (cddr chunks))] [i (in-naturals)])
          (codec-incremental-feed! s p #:final? (= i (- (length chunks) 3)))
          (codec-incremental-step! s))
        (check-equal? (codec-incremental-state s) 'complete)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels 8 8))
        (check-equal? (hash-ref (codec-incremental-statistics s) 'start-calls) 1)))
    (test-case "truncated final input is terminal but keeps a labelled partial snapshot"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (codec-incremental-feed! s #"" #:final? #t)
        (define p (codec-incremental-step! s))
        (check-equal? (incremental-progress-state p) 'incomplete)
        (check-equal? (incremental-progress-initialized-rows p) 1)
        (check-false (hash-ref (codec-incremental-statistics s) 'decoder-retained?))
        (check-equal? (incremental-progress-state (incremental-snapshot-progress (codec-incremental-snapshot s))) 'incomplete)))
    (test-case "final partial IDAT is never reported as complete"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s (bytes-append (car parts) (subbytes (cadr parts) 0 20)) #:final? #t)
        (check-not-equal? (incremental-progress-state (codec-incremental-step! s)) 'complete)))
    (test-case "corrupt input cannot acquire success"
      (with-skia ([s (make-codec-incremental)])
        (define data (bytes-copy (incremental-fixture-bytes)))
        ;; Corrupt the first stored DEFLATE block header in the first IDAT.
        (bytes-set! data 43 #xff)
        (codec-incremental-feed! s data #:final? #t)
        (check-not-equal? (incremental-progress-state (codec-incremental-step! s)) 'complete)))
    (test-case "native unsupported incremental BMP is explicit; no scanline fallback"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s (scanline-fixture-bmp) #:final? #t)
        (define p (codec-incremental-step! s))
        (check-equal? (incremental-progress-state p) 'failed)
        (check-equal? (incremental-progress-result p) 'unimplemented)
        (check-equal? (hash-ref (codec-incremental-statistics s) 'decode-calls) 0)))
    (test-case "invalid sealed data is terminal"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s #"not a supported image at all" #:final? #t)
        (check-not-false (memq (incremental-progress-state (codec-incremental-step! s)) '(failed incomplete)))))
    (test-case "completed step is idempotent and feed is rejected"
      (with-skia ([s (make-codec-incremental)])
        (define p (complete s)) (define stats (codec-incremental-statistics s))
        (check-equal? (codec-incremental-step! s) p)
        (check-equal? (codec-incremental-statistics s) stats)
        (check-exn exn:fail? (lambda () (codec-incremental-feed! s #"x")))))
    (test-case "explicit cancellation releases decoder and pixels"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (codec-incremental-cancel! s)
        (check-equal? (codec-incremental-state s) 'cancelled)
        (define stats (codec-incremental-statistics s))
        (check-false (hash-ref stats 'decoder-retained?)) (check-equal? (hash-ref stats 'pixel-bytes) 0)
        (check-exn exn:fail? (lambda () (codec-incremental-snapshot s)))))
    (test-case "ready cancellation event is handled before native advance"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (define calls (hash-ref (codec-incremental-statistics s) 'decode-calls))
        (check-equal? (incremental-progress-state (codec-incremental-step! s #:cancel-evt always-evt)) 'cancelled)
        (check-equal? (hash-ref (codec-incremental-statistics s) 'decode-calls) calls)))
    (test-case "invalid cancellation does not mutate the session"
      (with-skia ([s (make-codec-incremental)])
        (check-exn exn:fail? (lambda () (codec-incremental-step! s #:cancel-evt 1)))
        (check-equal? (codec-incremental-state s) 'awaiting-input)))
    (test-case "input limit rejects before changing prefix"
      (with-skia ([s (make-codec-incremental #:limit 40)])
        (check-exn exn:fail? (lambda () (codec-incremental-feed! s (incremental-fixture-bytes))))
        (check-equal? (hash-ref (codec-incremental-statistics s) 'input-bytes) 0)))
    (test-case "destination stride is checked before pixel allocation"
      (with-skia ([s (make-codec-incremental #:row-bytes 4)])
        (codec-incremental-feed! s (incremental-fixture-bytes) #:final? #t)
        (check-exn exn:fail? (lambda () (codec-incremental-step! s)))
        (check-equal? (codec-incremental-state s) 'failed)
        (check-equal? (hash-ref (codec-incremental-statistics s) 'pixel-allocations) 0)))
    (test-case "lower current limit rejects without resuming"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (codec-incremental-feed! s (caddr parts))
        (parameterize ([current-skia-byte-limit 64])
          (check-exn exn:fail? (lambda () (codec-incremental-step! s))))
        (check-equal? (codec-incremental-state s) 'needs-input)))
    (test-case "other Racket threads cannot use or close a session"
      (with-skia ([s (make-codec-incremental)])
        (wrong-thread (lambda () (codec-incremental-feed! s #"")))
        (wrong-thread (lambda () (codec-incremental-step! s)))
        (wrong-thread (lambda () (skia-close! s))) (check-false (skia-closed? s))))
    (test-case "closed sessions reject metadata and snapshots"
      (define s (make-codec-incremental)) (complete s) (skia-close! s) (skia-close! s)
      (for ([operation (in-list (list codec-incremental-info codec-incremental-statistics codec-incremental-snapshot codec-incremental-step!))])
        (check-exn exn:fail? (lambda () (operation s)))))
    (test-case "GC between steps preserves source and destination"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (collect-garbage) (collect-garbage) (finish s)
        (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "two suspended sessions keep independent stream contexts"
      (with-skia ([a (make-codec-incremental)] [b (make-codec-incremental #:color-type 'bgra-8888)])
        (prefix a) (prefix b) (finish a) (finish b)
        (check-equal? (snapshot-rgba a) (incremental-fixture-pixels))
        (check-equal? (snapshot-rgba b) (incremental-fixture-pixels))))
    (test-case "live-port callbacks still work while a memory decoder is suspended"
      (with-skia ([s (make-codec-incremental)])
        (prefix s) (define out (open-output-bytes))
        (copy-port/streaming (open-input-bytes #"coexistence") out)
        (check-equal? (get-output-bytes out) #"coexistence")
        (finish s) (check-equal? (snapshot-rgba s) (incremental-fixture-pixels))))
    (test-case "exceptional with-skia cleanup removes input registrations"
      (define before (incremental-source-count))
      (check-exn exn:fail? (lambda ()
        (with-skia ([s (make-codec-incremental)]) (prefix s) (error 'test "leave"))))
      (check-equal? (incremental-source-count) before))
    (test-case "abandoned session can be finalized; registry does not root it"
      (define before (incremental-source-count))
      (let ([s (make-codec-incremental)]) (prefix s) (void))
      (let loop ([n 10])
        (collect-garbage) (sleep 0)
        (when (and (positive? n) (> (incremental-source-count) before)) (loop (sub1 n))))
      (check-equal? (incremental-source-count) before))
    (test-case "old one-shot and scanline paths remain usable after an incremental failure"
      (with-skia ([s (make-codec-incremental)])
        (codec-incremental-feed! s #"bad input" #:final? #t) (codec-incremental-step! s))
      (with-skia ([c (codec-from-bytes (incremental-fixture-bytes))] [image (codec->image c)])
        (check-equal? (image->rgba-bytes image) (incremental-fixture-pixels))))))
(define codec-incremental-native-test-count 38)
(module+ main
  (define failures (run-tests codec-incremental-native-tests))
  (printf "codec-incremental-native: ~a cases, ~a failures\n" codec-incremental-native-test-count failures)
  (exit (if (zero? failures) 0 1)))
