#lang racket/base
;; Original tiny fixtures, authored for this suite. No network, font, or
;; runtime image encoder is needed to load them. Canvas size is 3 by 2.
(provide animated-gif animated-webp truncated-gif gif-expected-frames
         webp-expected-frames jpeg-with-origin orientation-orders)

(define animated-gif
  (bytes
   #x47 #x49 #x46 #x38 #x39 #x61 #x03 #x00 #x02 #x00 #x81 #x00 #x00 #x00 #x00 #x00
   #xff #x00 #x00 #x00 #xff #x00 #x00 #x00 #xff #x21 #xff #x0b #x4e #x45 #x54 #x53
   #x43 #x41 #x50 #x45 #x32 #x2e #x30 #x03 #x01 #x02 #x00 #x00 #x21 #xf9 #x04 #x05
   #x04 #x00 #x00 #x00 #x2c #x00 #x00 #x00 #x00 #x03 #x00 #x02 #x00 #x00 #x02 #x05
   #x0c #xc3 #x30 #x0c #x53 #x00 #x21 #xf9 #x04 #x0d #x07 #x00 #x00 #x00 #x2c #x01
   #x00 #x00 #x00 #x01 #x00 #x01 #x00 #x00 #x02 #x02 #x54 #x01 #x00 #x21 #xf9 #x04
   #x09 #x09 #x00 #x00 #x00 #x2c #x02 #x00 #x01 #x00 #x01 #x00 #x01 #x00 #x00 #x02
   #x02 #x5c #x01 #x00 #x21 #xf9 #x04 #x05 #x0b #x00 #x00 #x00 #x2c #x00 #x00 #x01
   #x00 #x01 #x00 #x01 #x00 #x00 #x02 #x02 #x54 #x01 #x00 #x21 #xf9 #x04 #x05 #x0d
   #x00 #x00 #x00 #x2c #x00 #x00 #x00 #x00 #x03 #x00 #x01 #x00 #x00 #x02 #x03 #x04
   #x45 #x14 #x00 #x3b))

(define animated-webp
  (bytes
   #x52 #x49 #x46 #x46 #xac #x00 #x00 #x00 #x57 #x45 #x42 #x50 #x56 #x50 #x38 #x58
   #x0a #x00 #x00 #x00 #x12 #x00 #x00 #x00 #x02 #x00 #x00 #x01 #x00 #x00 #x41 #x4e
   #x49 #x4d #x06 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x41 #x4e #x4d #x46
   #x26 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x02 #x00 #x00 #x01 #x00 #x00
   #x28 #x00 #x00 #x02 #x56 #x50 #x38 #x4c #x0e #x00 #x00 #x00 #x2f #x02 #x40 #x00
   #x00 #xb9 #x8c #xe8 #x7f #x20 #xe6 #x3f #x22 #x02 #x41 #x4e #x4d #x46 #x24 #x00
   #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x01 #x00 #x00 #x00 #x00 #x00 #x46 #x00
   #x00 #x00 #x56 #x50 #x38 #x4c #x0b #x00 #x00 #x00 #x2f #x01 #x00 #x00 #x10 #x98
   #xff #x88 #xf9 #x0f #x06 #x00 #x41 #x4e #x4d #x46 #x26 #x00 #x00 #x00 #x00 #x00
   #x00 #x00 #x00 #x00 #x02 #x00 #x00 #x01 #x00 #x00 #x5a #x00 #x00 #x00 #x56 #x50
   #x38 #x4c #x0e #x00 #x00 #x00 #x2f #x02 #x40 #x00 #x10 #x88 #xf9 #x9f #xff #xf9
   #x0f #x14 #x80 #x01))

(define truncated-gif
  (bytes
   #x47 #x49 #x46 #x38 #x39 #x61 #x03 #x00 #x02 #x00 #x81 #x00 #x00 #x00 #x00 #x00
   #xff #x00 #x00 #x00 #xff #x00 #x00 #x00 #xff #x21 #xff #x0b #x4e #x45 #x54 #x53
   #x43 #x41 #x50 #x45 #x32 #x2e #x30 #x03 #x01 #x02 #x00 #x00 #x21 #xf9 #x04 #x05
   #x04 #x00 #x00 #x00 #x2c #x00 #x00 #x00 #x00 #x03 #x00 #x02 #x00 #x00 #x02 #x05
   #x0c))

(define gif-frame-0
  (bytes
   #xff #x00 #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff
   #xff #x00 #x00 #xff #xff #x00 #x00 #xff))
(define gif-frame-1
  (bytes
   #xff #x00 #x00 #xff #x00 #xff #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff
   #xff #x00 #x00 #xff #xff #x00 #x00 #xff))
(define gif-frame-2
  (bytes
   #xff #x00 #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff
   #xff #x00 #x00 #xff #x00 #x00 #xff #xff))
(define gif-frame-3
  (bytes
   #xff #x00 #x00 #xff #xff #x00 #x00 #xff #xff #x00 #x00 #xff #x00 #xff #x00 #xff
   #xff #x00 #x00 #xff #x00 #x00 #x00 #x00))
(define gif-frame-4
  (bytes
   #xff #x00 #x00 #xff #x00 #xff #x00 #xff #xff #x00 #x00 #xff #x00 #xff #x00 #xff
   #xff #x00 #x00 #xff #x00 #x00 #x00 #x00))

(define gif-expected-frames (vector-immutable gif-frame-0 gif-frame-1 gif-frame-2 gif-frame-3 gif-frame-4))
(define webp-expected-frames (vector-immutable gif-frame-0 gif-frame-1 gif-frame-2))

;; Expected source-pixel orders for the asymmetric 3x2 raster [A B C; D E F].
;; These hand-written permutations are independent of the orientation code.
(define orientation-orders
  '#(#(0 1 2 3 4 5) #(2 1 0 5 4 3) #(5 4 3 2 1 0) #(3 4 5 0 1 2)
     #(0 3 1 4 2 5) #(3 0 4 1 5 2) #(5 2 4 1 3 0) #(2 5 1 4 0 3)))

;; Insert a little-endian TIFF Orientation tag in an APP1 segment immediately
;; after JPEG's SOI. The input generated by our tests has no existing EXIF.
(define (jpeg-with-origin jpeg origin)
  (unless (and (bytes? jpeg) (>= (bytes-length jpeg) 2)
               (= (bytes-ref jpeg 0) 255) (= (bytes-ref jpeg 1) 216))
    (raise-argument-error 'jpeg-with-origin "JPEG bytes beginning with SOI" jpeg))
  (unless (and (exact-integer? origin) (<= 1 origin 8))
    (raise-argument-error 'jpeg-with-origin "integer from 1 through 8" origin))
  (bytes-append
   (subbytes jpeg 0 2)
   (bytes 255 225 0 34)
   (bytes 69 120 105 102 0 0 73 73 42 0 8 0 0 0 1 0 18 1 3 0 1 0 0 0)
   (bytes origin 0 0 0 0 0 0 0)
   (subbytes jpeg 2)))
