#lang racket/base
(require rackunit rackunit/text-ui ffi/unsafe
         "../codec-queries.rkt" "../private/codec-query-util.rkt"
         "../private/check.rkt" "../private/types.rkt")
(provide codec-query-pure-tests codec-query-pure-test-count)
(define (size-list . args)
  (call-with-values (lambda () (apply codec-query-scaled-result 'test args)) list))
(define codec-query-pure-tests
  (test-suite "0.76a codec query arguments and detached results"
    (test-case "public query arities" (check-true (procedure-arity-includes? codec-scaled-dimensions 2)) (check-true (procedure-arity-includes? codec-supported-subset 5)))
    (test-case "invalid codec needs no native library" (check-exn exn:fail:contract? (lambda () (codec-scaled-dimensions #f 1))) (check-exn exn:fail:contract? (lambda () (codec-supported-subset #f 0 0 1 1))))
    (test-case "scale one" (check-equal? (codec-query-scale 'test 1) 1.0))
    (test-case "exact rational scale" (check-equal? (codec-query-scale 'test 1/2) 0.5))
    (test-case "upscale remains a legal query" (check-equal? (codec-query-scale 'test 4) 4.0))
    (test-case "scale is rounded to C float" (check-equal? (codec-query-scale 'test 0.1) (floating-point-bytes->real (real->floating-point-bytes 0.1 4))))
    (test-case "zero and negative scale reject" (for ([x '(0 -1 -0.0)]) (check-exn exn:fail:contract? (lambda () (codec-query-scale 'test x)))))
    (test-case "nonfinite scale rejects" (for ([x (list +inf.0 -inf.0 +nan.0)]) (check-exn exn:fail:contract? (lambda () (codec-query-scale 'test x)))))
    (test-case "float overflow rejects" (check-exn exn:fail:contract? (lambda () (codec-query-scale 'test 1e100))))
    (test-case "positive float underflow rejects" (check-exn exn:fail:contract? (lambda () (codec-query-scale 'test 1e-100))))
    (test-case "nonreal scale rejects" (for ([x (list 'half #f 1+2i)]) (check-exn exn:fail:contract? (lambda () (codec-query-scale 'test x)))))
    (test-case "rectangle uses exclusive endpoints" (check-equal? (codec-query-rect 'test 1 3 6 5) '#(1 3 7 8)))
    (test-case "rectangle snapshot is immutable" (check-true (immutable? (codec-query-rect 'test 0 0 1 1))))
    (test-case "negative origin rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test -1 0 1 1))))
    (test-case "inexact origin rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test 1.0 0 1 1))))
    (test-case "zero extent rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test 0 0 0 1))))
    (test-case "negative extent rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test 0 0 1 -1))))
    (test-case "fractional extent rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test 0 0 1 1/2))))
    (test-case "endpoint overflow rejects" (check-exn exn:fail:contract? (lambda () (codec-query-rect 'test #x7fffffff 0 1 1))))
    (test-case "last legal int32 endpoint" (check-equal? (codec-query-rect 'test #x7ffffffe 0 1 1) '#(2147483646 0 2147483647 1)))
    (test-case "bounds allow last pixel" (check-not-exn (lambda () (codec-query-check-bounds 'test '#(15 11 16 12) 16 12))))
    (test-case "bounds reject overhang" (check-exn exn:fail:contract? (lambda () (codec-query-check-bounds 'test '#(15 11 17 12) 16 12))))
    (test-case "source dimensions reject zero" (check-exn exn:fail? (lambda () (codec-query-source-size 'test 0 12))))
    (test-case "metadata does not allocate a raster" (parameterize ([current-skia-byte-limit 1]) (check-equal? (call-with-values (lambda () (codec-query-source-size 'test 100000 100000)) list) '(100000 100000))))
    (test-case "scaled result is two exact dimensions" (check-equal? (size-list 16 12 8 6) '(8 6)))
    (test-case "invalid native upscale rejects" (check-exn exn:fail? (lambda () (size-list 16 12 17 6))))
    (test-case "invalid native empty size rejects" (check-exn exn:fail? (lambda () (size-list 16 12 0 6))))
    (test-case "subset converts endpoints to extents" (check-equal? (codec-query-subset-result 'test 16 12 0 2 7 8) '#(0 2 7 6)))
    (test-case "subset result is immutable" (check-true (immutable? (codec-query-subset-result 'test 16 12 0 0 16 12))))
    (test-case "invalid native subset rejects" (for ([r '((-1 0 3 3) (0 0 0 3) (0 0 17 3) (0 0 3 13))]) (check-exn exn:fail? (lambda () (apply codec-query-subset-result 'test 16 12 r)))))
    (test-case "reuses established native layouts" (check-equal? (ctype-sizeof _sk-isize) 8) (check-equal? (ctype-sizeof _sk-irect) 16))))
(define codec-query-pure-test-count 31)
(module+ main
  (define failures (run-tests codec-query-pure-tests))
  (printf "codec-query-pure: ~a cases, ~a failures\n" codec-query-pure-test-count failures)
  (exit (if (zero? failures) 0 1)))
