#lang racket/base
;; Test-only independent native producer/consumer. The runtime library never
;; imports this file or builds/loads this DLL.
(require ffi/unsafe "../gpu.rkt" "../unsafe/gpu-d3d12.rkt")
(provide load-interop-fixture make-fixture fixture-texture fixture-fence close-fixture
         drop-fixture-texture fixture-description fixture-readback fixture-unsignaled
         fixture-release fixture-foreign fixture-foreign-live fixture-foreign-desc-calls)
(define library #f)
(define (load-interop-fixture path)
  (set! library (ffi-lib path))
  (unless (= ((get-ffi-obj "interop_fixture_kind" library (_fun -> _uint32))) 1)
    (error 'interop-fixture "requires the real Windows SDK build")))
(define (function name type)
  (unless library (error 'interop-fixture "fixture is not loaded"))
  (get-ffi-obj name library type))
(define (checked code)
  (unless (zero? code) (error 'interop-fixture "HRESULT 0x~a" (number->string (bitwise-and code #xffffffff) 16))))
(define (out-pointer call)
  (define out (malloc _pointer 'atomic)) (ptr-set! out _pointer #f)
  (checked (call out)) (or (ptr-ref out _pointer) (error 'interop-fixture "null result")))
(define (make-fixture c [w 37] [h 29] [kind 0])
  (call-with-gpu-d3d12-device c
    (lambda (device) (out-pointer (lambda (out)
      ((function "interop_fixture_create" (_fun _pointer _uint32 _uint32 _uint32 _pointer -> _int32))
       device w h kind out))))))
(define (fixture-texture f) ((function "interop_fixture_texture" (_fun _pointer -> _pointer)) f))
(define (fixture-fence f) ((function "interop_fixture_fence" (_fun _pointer -> _pointer)) f))
(define (close-fixture f) (checked ((function "interop_fixture_close" (_fun _pointer -> _int32)) f)))
(define (drop-fixture-texture f) (checked ((function "interop_fixture_drop_texture" (_fun _pointer -> _int32)) f)))
(define (fixture-description f)
  (define p (malloc (* 9 8) 'atomic))
  (checked ((function "interop_fixture_descriptor" (_fun _pointer _pointer _size -> _int32)) f p 9))
  (for/list ([i (in-range 9)]) (ptr-ref p _uint64 i)))
(define (fixture-readback f state w h)
  (define bytes (make-bytes (* w h 4)))
  (checked ((function "interop_fixture_readback" (_fun _pointer _uint32 _bytes _size -> _int32))
            f state bytes (bytes-length bytes))) bytes)
(define (fixture-unsignaled f)
  (out-pointer (lambda (out) ((function "interop_fixture_unsignaled_fence" (_fun _pointer _pointer -> _int32)) f out))))
(define (fixture-release p) ((function "interop_fixture_release" (_fun _pointer -> _void)) p))
(define (fixture-foreign) ((function "interop_fixture_foreign_resource" (_fun -> _pointer))))
(define (fixture-foreign-live) ((function "interop_fixture_foreign_live" (_fun -> _uint32))))
(define (fixture-foreign-desc-calls) ((function "interop_fixture_foreign_desc_calls" (_fun -> _uint32))))
