#lang racket/base
(require rackunit racket/class racket/list
         (prefix-in rd: racket/draw)
         "../private/dc-class.rkt" "../private/dc-support.rkt"
         (only-in "../private/check.rkt" current-skia-byte-limit)
         "../examples/dc-replay.rkt" "dc-alpha-test.rkt")
(provide dc-replay-pure-tests dc-replay-pure-test-count)
(define (fresh #:fail-create [fail-create #f] #:fail-compose [fail-compose #f])
  (define events (box '())) (define next 0)
  (define (event . xs) (set-box! events (cons xs (unbox events))) (void))
  (define r
    (dc-renderer/alpha
     (lambda (w h) (set! next (add1 next))
       (when (equal? next fail-create) (error 'create "injected allocation failure"))
       (event 'create next w h) next)
     (lambda (s) (event 'close s))
     (lambda (s command) (event 'path s command))
     (lambda (s . xs) (apply event 'clear s xs))
     values (lambda (s p?) (bytes s)) (lambda (s) (bytes s))
     (lambda (_s _request) (values 10.0 20.0 3.0 1.0))
     (lambda (s . xs) (apply event 'text s xs)) (lambda (_s _font _c) #t)
     (lambda (s . xs) (apply event 'bitmap s xs))
     (lambda (s . xs) (apply event 'copy s xs))
     (lambda (parent child clip a)
       (event 'merge parent child clip a)
       (when fail-compose (error 'merge "injected composition failure")))))
  (values (new (make-skia-dc-class r) [width 64] [height 48]) events))
(define-syntax-rule (with-fresh (dc e) body ...)
  (let-values ([(dc e) (fresh)])
    (dynamic-wind void (lambda () body ...) (lambda () (send dc close)))))
(define (events-of e kind) (filter (lambda (x) (eq? (car x) kind)) (reverse (unbox e))))
(define (simple dc)
  (send dc set-pen "black" 1 'transparent) (send dc set-brush "red" 'solid)
  (send dc draw-rectangle 2 3 8 9))
(define dc-replay-pure-tests
  (test-suite
   "DC replay, locking and alpha protocol (recording renderer; no Skia pixels)"
   (test-case "upstream recorded procedure uses actual local-member bridge"
     (with-fresh (dc e)
       (define-values (procedure datum) (make-dc-recording simple))
       (procedure dc) (check-equal? (length (events-of e 'path)) 1)))
   (test-case "upstream recorded datum uses actual local-member bridge"
     (with-fresh (dc e)
       (define-values (procedure datum) (make-dc-recording simple))
       (datum dc) (check-equal? (length (events-of e 'path)) 1)))
   (test-case "both replay forms restore pen and brush identity"
     (with-fresh (dc e)
       (define p (rd:make-pen #:width 3 #:immutable? #f))
       (define b (rd:make-brush #:color "blue" #:immutable? #f))
       (send dc set-pen p) (send dc set-brush b)
       (define-values (proc datum) (make-dc-recording simple))
       (for ([draw (list proc datum)]) (draw dc)
         (check-eq? (send dc get-pen) p) (check-eq? (send dc get-brush) b)
         (check-exn exn:fail? (lambda () (send p set-width 9)))
         (check-exn exn:fail? (lambda () (send b set-color "red"))))))
   (test-case "both replay forms preserve destination transformation"
     (with-fresh (dc e)
       (send dc set-origin 2 3) (send dc set-scale 2 3)
       (send dc set-rotation 0.1) (send dc set-smoothing 'smoothed)
       (define before (send dc get-transformation))
       (define-values (proc datum) (make-dc-recording (lambda (d) (send d set-smoothing 'smoothed) (simple d))))
       (for ([draw (list proc datum)]) (draw dc) (check-equal? (send dc get-transformation) before))))
   (test-case "both replay forms preserve selected region and alpha"
     (with-fresh (dc e)
       (send dc set-clipping-rect 1 1 20 20) (send dc set-alpha 0.25)
       (define region (send dc get-clipping-region))
       (define-values (proc datum) (make-dc-recording simple))
       (for ([draw (list proc datum)]) (draw dc)
         (check-eq? (send dc get-clipping-region) region) (check-= (send dc get-alpha) 0.25 0))))
   (test-case "replay restores font text mode colors and smoothing"
     (with-fresh (dc e)
       (define f (rd:make-font #:face "Arial" #:size 18)) (send dc set-font f)
       (send dc set-text-mode 'solid) (send dc set-text-foreground "blue")
       (send dc set-background "red") (send dc set-smoothing 'aligned)
       (define-values (proc datum) (make-dc-recording simple))
       (for ([draw (list proc datum)]) (draw dc)
         (check-eq? (send dc get-font) f) (check-eq? (send dc get-text-mode) 'solid)
         (check-eq? (send dc get-smoothing) 'aligned)
         (check-equal? (send (send dc get-background) red) 255)
         (check-equal? (send (send dc get-text-foreground) blue) 255))))
   (test-case "selected mutable pen is locked"
     (with-fresh (dc e)
       (define p (rd:make-pen #:immutable? #f)) (send dc set-pen p)
       (check-eq? p (send dc get-pen)) (check-exn exn:fail? (lambda () (send p set-width 3)))))
   (test-case "selected mutable brush is locked"
     (with-fresh (dc e)
       (define b (rd:make-brush #:immutable? #f)) (send dc set-brush b)
       (check-eq? b (send dc get-brush)) (check-exn exn:fail? (lambda () (send b set-color "red")))))
   (test-case "pen shared across DCs stays locked until both release"
     (with-fresh (dc e) (with-fresh (other f)
       (define p (rd:make-pen #:immutable? #f)) (send dc set-pen p) (send other set-pen p)
       (send dc close) (check-exn exn:fail? (lambda () (send p set-width 3)))
       (send other close) (check-not-exn (lambda () (send p set-width 3))))))
   (test-case "brush shared across DCs stays locked until both release"
     (with-fresh (dc e) (with-fresh (other f)
       (define b (rd:make-brush #:immutable? #f)) (send dc set-brush b) (send other set-brush b)
       (send dc close) (check-exn exn:fail? (lambda () (send b set-color "red")))
       (send other close) (check-not-exn (lambda () (send b set-color "red"))))))
   (test-case "reselection does not leak lock counts"
     (with-fresh (dc e)
       (define p (rd:make-pen #:immutable? #f)) (define b (rd:make-brush #:immutable? #f))
       (for ([_ (in-range 10)]) (send dc set-pen p) (send dc set-brush b))
       (send dc close) (check-not-exn (lambda () (send p set-width 4) (send b set-color "red")))))
   (test-case "replacement releases previous selections"
     (with-fresh (dc e)
       (define p (rd:make-pen #:immutable? #f)) (define b (rd:make-brush #:immutable? #f))
       (send dc set-pen p) (send dc set-brush b) (simple dc)
       (check-not-exn (lambda () (send p set-width 4) (send b set-color "red")))))
   (test-case "rejected selection preserves old lock and leaves candidate unlocked"
     (with-fresh (dc e)
       (define p (rd:make-pen #:immutable? #f)) (send dc set-pen p)
       (define bad (rd:make-pen #:style 'xor #:immutable? #f))
       (check-exn exn:fail:skia-dc:unsupported? (lambda () (send dc set-pen bad)))
       (check-eq? p (send dc get-pen)) (check-not-exn (lambda () (send bad set-width 3)))
       (check-exn exn:fail? (lambda () (send p set-width 4)))))
   (test-case "wrong-thread alpha call is rejected before allocation"
     (with-fresh (dc e)
       (define answer (box #f))
       (thread-wait (thread (lambda () (with-handlers ([exn:fail? (lambda (x) (set-box! answer x))]) (send dc start-alpha 0.5)))))
       (check-true (exn:fail? (unbox answer))) (check-equal? (length (events-of e 'create)) 1)))
   (test-case "close discards nested groups and releases all surfaces"
     (with-fresh (dc e)
       (send dc start-alpha 0.5) (send dc start-alpha 0.5) (send dc close)
       (check-equal? (events-of e 'close) '((close 3) (close 2) (close 1)))
       (check-equal? (events-of e 'merge) '())))
   (test-case "nested alpha restores explicit per-draw opacity"
     (with-fresh (dc e)
       (send dc set-alpha 0.25) (send dc start-alpha 0.5) (check-= (send dc get-alpha) 1 0)
       (send dc set-alpha 0.75) (send dc start-alpha 0.5) (send dc end-alpha)
       (check-= (send dc get-alpha) 0.75 0) (send dc end-alpha) (check-= (send dc get-alpha) 0.25 0)
       (check-equal? (map last (events-of e 'merge)) '(0.375 0.125))))
   (test-case "all output methods use root while alpha is open"
     (with-fresh (dc e)
       (send dc start-alpha 0.5)
       (check-equal? (send dc snapshot) 1) (check-equal? (send dc get-rgba-bytes) (bytes 1))
       (check-equal? (send dc get-png-bytes) (bytes 1))))
   (test-case "parent clip is not applied twice inside alpha"
     (with-fresh (dc e)
       (send dc set-clipping-rect 1 2 10 11) (send dc start-alpha 0.5) (simple dc)
       (define path (third (car (events-of e 'path)))) (check-false (dc-draw-clip path))
       (send dc end-alpha) (check-true (dc-clip? (fourth (car (events-of e 'merge)))))))
   (test-case "inner clipping keeps selection locking"
     (with-fresh (dc e)
       (send dc start-alpha 0.5) (send dc set-clipping-rect 1 2 10 11)
       (define region (send dc get-clipping-region))
       (check-exn exn:fail? (lambda () (send region set-rectangle 0 0 1 1)))
       (send dc end-alpha) (send dc set-clipping-region #f)
       (check-not-exn (lambda () (send region set-rectangle 0 0 1 1)))))
   (test-case "invalid alpha has no allocation or state change"
     (with-fresh (dc e)
       (send dc set-alpha 0.25)
       (for ([a '(-1 2 +nan.0 +inf.0 #f)]) (check-exn exn:fail? (lambda () (send dc start-alpha a))))
       (check-= (send dc get-alpha) 0.25 0) (check-equal? (length (events-of e 'create)) 1)))
   (test-case "alpha memory rejection is transactional"
     (with-fresh (dc e)
       (parameterize ([current-skia-byte-limit (* 4 64 48)])
         (check-exn exn:fail? (lambda () (send dc start-alpha 0.5))))
       (check-= (send dc get-alpha) 1 0) (check-equal? (send dc snapshot) 1)))
   (test-case "unmatched end-alpha performs no native work"
     (with-fresh (dc e) (define before (unbox e)) (send dc end-alpha) (check-equal? (unbox e) before)))
   (test-case "allocation failure preserves usable root"
     (define-values (dc e) (fresh #:fail-create 2))
     (dynamic-wind void (lambda ()
       (send dc set-alpha 0.25) (check-exn #rx"allocation" (lambda () (send dc start-alpha 0.5)))
       (check-= (send dc get-alpha) 0.25 0) (simple dc)
       (check-equal? (second (car (events-of e 'path))) 1)) (lambda () (send dc close))))
   (test-case "compositing failure restores target and alpha and retires child"
     (define-values (dc e) (fresh #:fail-compose #t))
     (dynamic-wind void (lambda ()
       (send dc set-alpha 0.25) (send dc start-alpha 0.5)
       (check-exn #rx"composition" (lambda () (send dc end-alpha)))
       (check-= (send dc get-alpha) 0.25 0) (simple dc)
       (check-equal? (second (car (events-of e 'path))) 1)
       (check-equal? (events-of e 'close) '((close 2)))) (lambda () (send dc close))))
   (test-case "unsupported recorded styles raise instead of falling back"
     (with-fresh (dc e)
       (define-values (proc datum) (make-dc-recording (lambda (d) (send d set-brush "red" 'cross-hatch))))
       (check-exn exn:fail:skia-dc:unsupported? (lambda () (proc dc)))
       (check-exn exn:fail:skia-dc:unsupported? (lambda () (datum dc)))))
   (test-case "repeated replay does not lose destination identity or locks"
     (with-fresh (dc e)
       (define p (rd:make-pen #:immutable? #f)) (send dc set-pen p)
       (define-values (proc datum) (make-dc-recording simple))
       (for ([_ (in-range 8)]) (proc dc) (datum dc) (check-eq? p (send dc get-pen)))
       (send dc close) (check-not-exn (lambda () (send p set-width 9)))))
   (test-case "private replay members are not public symbol lookalikes"
     (with-fresh (dc e) (check-false (object-method-arity-includes? dc 'do-set-pen! 1))
                       (check-false (object-method-arity-includes? dc 'do-set-brush! 1))))
   (test-case "production alpha controller adversarial suite"
     (check-equal? (run-dc-alpha-tests) dc-alpha-test-count))))
(define dc-replay-pure-test-count 28)
