#lang racket/base
;; Standalone executable tests of production math; no draw-lib, Skia or
;; RackUnit is needed. The RackUnit style suite invokes this same entry point.
(require racket/list racket/math "../private/dc-style-math.rkt" "../private/dc-support.rkt")
(provide run-dc-style-math-tests)
(define (run-dc-style-math-tests)
  (define count 0)
  (define (yes label v)
    (set! count (add1 count))
    (unless v (error 'dc-style-math-test "failed: ~a" label)))
  (define (equal label a b) (yes label (equal? a b)))
  (define (near label a b) (yes label (< (abs (- a b)) 1e-8)))
  (define (reject label thunk) (yes label (with-handlers ([exn:fail? (lambda (_) #t)]) (thunk) #f)))
  (equal 'identity (dc-inverse 'test dc-identity) dc-identity)
  (for ([m (list '#(2.0 0.0 0.0 3.0 7.0 -4.0) '#(-1.0 0.0 0.0 1.0 20.0 0.0)
                '#(1.0 0.5 0.25 1.0 2.0 3.0) '#(0.0 -1.0 1.0 0.0 0.0 0.0))])
    (define product (dc-multiply m (dc-inverse 'test m)))
    (yes 'inverse (for/and ([x (in-vector product)] [y (in-vector dc-identity)]) (< (abs (- x y)) 1e-8))))
  (reject 'singular (lambda () (dc-inverse 'test '#(1 2 2 4 0 0))))
  (reject 'nonfinite (lambda () (dc-inverse 'test (vector +nan.0 0 0 1 0 0))))
  (equal 'source-backing (dc-style-local-matrix '#(2 0 0 2 7 8) #f 2) '#(0.5 0.0 0.0 0.5 0.0 0.0))
  (define t '#(#(1 0 0 1 0 0) 3 4 1 1 0))
  (equal 'override (dc-style-local-matrix '#(2 0 0 2 7 8) t 1) '#(0.5 0.0 0.0 0.5 -2.0 -2.0))
  (reject 'zero-backing (lambda () (dc-style-local-matrix dc-identity #f 0)))
  (for ([style '(dot long-dash short-dash dot-dash)]
        [pattern '((1.0 4.0) (4.0 4.0) (2.0 4.0) (1.0 4.0 4.0 4.0))])
    (define-values (d p) (dc-dash-spec style 1))
    (equal 'dash d pattern)
    (near 'phase p (if (eq? style 'dot-dash) 4.0 2.0)))
  (define-values (wide wp) (dc-dash-spec 'long-dash 3))
  (equal 'wide wide '(12.0 6.0)) (near 'wide-phase wp 2.0)
  (define-values (none np) (dc-dash-spec 'dot 3 #t))
  (equal 'stipple-dash none '(3.0 6.0))
  (for ([style '(xor xor-dot xor-long-dash xor-short-dash xor-dot-dash)])
    (define-values (d p) (dc-dash-spec style 2)) (equal 'legacy-solid d '()))
  (for ([style dc-hatch-styles] [n '(3 3 6 5 5 10)]) (equal 'hatch-count (length (dc-hatch-lines style)) n))
  (reject 'bad-hatch (lambda () (dc-hatch-lines 'solid)))
  (define stops (dc-gradient-stops 'test '((1 #(0 0 255 1)) (0.5 #(0 255 0 1))
                                          (0.5 #(255 0 0 1)) (0 #(0 0 0 0))) 1000))
  (equal 'sorted (map car stops) '(0.0 0.5 0.5 1.0))
  (equal 'stable (cadr (second stops)) '#(0 255 0 1.0))
  (equal 'empty (dc-gradient-stops 'test '() 0) '())
  (reject 'stop-budget (lambda () (dc-gradient-stops 'test '((0 #(0 0 0 1))) 39)))
  (reject 'bad-offset (lambda () (dc-gradient-stops 'test '((2 #(0 0 0 1))) 100)))
  (reject 'bad-alpha (lambda () (dc-gradient-stops 'test '((0 #(0 0 0 +nan.0))) 100)))
  (define-values (ax ay ux uy) (dc-alignment-functions 'test dc-identity 1 1 'aligned))
  (near 'snap-x (ax 1.2) 1.5) (near 'snap-y (ay -1.2) -1.5) (near 'inset ux 1.0)
  (define-values (bx by vx vy) (dc-alignment-functions 'test '#(-1 0.2 0.3 1 20 0) 2 1 'unsmoothed))
  (yes 'affine (and (rational? (bx 3.2)) (rational? (by 2.8)) (> vx 0) (> vy 0)))
  (define-values (cx cy wx wy) (dc-alignment-functions 'test dc-identity 3 2 'smoothed))
  (near 'smooth (cx 1.21) 1.21) (near 'smooth-inset wx 0)
  count)
(module+ main (printf "~a production style-math checks passed\n" (run-dc-style-math-tests)))
