#lang racket/base
(require ffi/unsafe racket/list "../gpu.rkt" "../gpu-gl-interop.rkt"
         "../private/gpu-gl-queries.rkt" "../private/gpu-context.rkt"
         (submod "../private/gpu-domain.rkt" gl-interop-internals))
(provide make-gl-fixture delete-gl-fixture! gl-fixture-pixels gl-fixture-fill!
         gl-fixture-alive? gl-pattern-bytes (struct-out gl-fixture))
(struct gl-fixture (context queries texture framebuffer stencil width height [closed? #:mutable]))
(define (gl-pattern-bytes w h)
  (apply bytes
    (for*/list ([y (in-range h)] [x (in-range w)] [k (in-range 4)])
      (list-ref (cond [(< y (quotient h 2)) (if (< x (quotient w 2)) '(255 0 0 255) '(0 255 0 255))]
                     [else (if (< x (quotient w 2)) '(0 0 255 255) '(255 255 0 255))]) k))))
(define (raw-bind fixture name type) ((gl-queries-bind (gl-fixture-queries fixture)) name type))
(define (make-gl-fixture context [w 8] [h 8])
  (define queries (make-gl-queries (domain-gl-resolver (context-domain 'test context))))
  (define bind (gl-queries-bind queries))
  (define (gen name)
    (define p (malloc _uint32 'atomic)) (ptr-set! p _uint32 0)
    ((bind name (_fun _int _pointer -> _void)) 1 p) (ptr-ref p _uint32))
  (define fixture #f)
  (call-with-gpu-external-gl context
    (lambda ()
      (define tex 0) (define fbo 0) (define rb 0) (define success? #f)
      (dynamic-wind void
        (lambda ()
          (set! tex (gen "glGenTextures"))
          (set! fbo (gen "glGenFramebuffers"))
          (set! rb (gen "glGenRenderbuffers"))
          (set! fixture (gl-fixture context queries tex fbo rb w h #f))
          ((bind "glActiveTexture" (_fun _uint32 -> _void)) #x84C0)
          ((bind "glBindTexture" (_fun _uint32 _uint32 -> _void)) #x0DE1 tex)
          ((bind "glTexParameteri" (_fun _uint32 _uint32 _int -> _void)) #x0DE1 #x2801 #x2600)
          ((bind "glTexParameteri" (_fun _uint32 _uint32 _int -> _void)) #x0DE1 #x2800 #x2600)
          ((bind "glBindBuffer" (_fun _uint32 _uint32 -> _void)) #x88EC 0)
          (for ([pair (in-list '((#x0CF5 1) (#x0CF2 0) (#x0CF3 0) (#x0CF4 0)))])
            ((bind "glPixelStorei" (_fun _uint32 _int -> _void)) (car pair) (cadr pair)))
          (define pixels (gl-pattern-bytes w h))
          ((bind "glTexImage2D" (_fun _uint32 _int _int _int _int _int _uint32 _uint32 _bytes -> _void))
           #x0DE1 0 #x8058 w h 0 #x1908 #x1401 pixels)
          ((bind "glBindRenderbuffer" (_fun _uint32 _uint32 -> _void)) #x8D41 rb)
          ((bind "glRenderbufferStorage" (_fun _uint32 _uint32 _int _int -> _void)) #x8D41 #x88F0 w h)
          ((bind "glBindFramebuffer" (_fun _uint32 _uint32 -> _void)) #x8D40 fbo)
          ((bind "glFramebufferTexture2D" (_fun _uint32 _uint32 _uint32 _uint32 _int -> _void))
           #x8D40 #x8CE0 #x0DE1 tex 0)
          ((bind "glFramebufferRenderbuffer" (_fun _uint32 _uint32 _uint32 _uint32 -> _void))
           #x8D40 #x821A #x8D41 rb)
          ((bind "glDrawBuffer" (_fun _uint32 -> _void)) #x8CE0)
          ((bind "glReadBuffer" (_fun _uint32 -> _void)) #x8CE0)
          ((gl-queries-framebuffer queries) fbo w h)
          (set! success? #t)
          fixture)
        (lambda ()
          (unless success?
            (for ([name (in-list '("glDeleteFramebuffers" "glDeleteRenderbuffers" "glDeleteTextures"))]
                  [id (in-list (list fbo rb tex))] #:when (positive? id))
              (define p (malloc _uint32 'atomic)) (ptr-set! p _uint32 id)
              ((bind name (_fun _int _pointer -> _void)) 1 p))))))))
(define (delete-gl-fixture! f)
  (unless (gl-fixture-closed? f)
    (call-with-gpu-external-gl (gl-fixture-context f)
      (lambda ()
        (for ([name (in-list '("glDeleteFramebuffers" "glDeleteRenderbuffers" "glDeleteTextures"))]
              [id (in-list (list (gl-fixture-framebuffer f) (gl-fixture-stencil f) (gl-fixture-texture f)))])
          (define p (malloc _uint32 'atomic)) (ptr-set! p _uint32 id)
          ((raw-bind f name (_fun _int _pointer -> _void)) 1 p))
        (set-gl-fixture-closed?! f #t)) #:wait? #t)))
(define (gl-fixture-alive? f)
  (call-with-gpu-external-gl (gl-fixture-context f)
    (lambda ()
      (and ((raw-bind f "glIsTexture" (_fun _uint32 -> _stdbool)) (gl-fixture-texture f))
           ((raw-bind f "glIsFramebuffer" (_fun _uint32 -> _stdbool)) (gl-fixture-framebuffer f))
           ((raw-bind f "glIsRenderbuffer" (_fun _uint32 -> _stdbool)) (gl-fixture-stencil f))))))
(define (gl-fixture-fill! f red green blue alpha)
  (call-with-gpu-external-gl (gl-fixture-context f)
    (lambda ()
      ((raw-bind f "glBindFramebuffer" (_fun _uint32 _uint32 -> _void)) #x8D40 (gl-fixture-framebuffer f))
      ((raw-bind f "glDisable" (_fun _uint32 -> _void)) #x0C11)
      ((raw-bind f "glDisable" (_fun _uint32 -> _void)) #x8DB9)
      ((raw-bind f "glColorMask" (_fun _stdbool _stdbool _stdbool _stdbool -> _void)) #t #t #t #t)
      ((raw-bind f "glClearColor" (_fun _float _float _float _float -> _void)) red green blue alpha)
      ((raw-bind f "glClear" (_fun _uint32 -> _void)) #x4000))))
(define (gl-fixture-pixels f)
  (call-with-gpu-external-gl (gl-fixture-context f)
    (lambda ()
      ((raw-bind f "glBindFramebuffer" (_fun _uint32 _uint32 -> _void)) #x8CA8 (gl-fixture-framebuffer f))
      ((raw-bind f "glReadBuffer" (_fun _uint32 -> _void)) #x8CE0)
      ((raw-bind f "glBindBuffer" (_fun _uint32 _uint32 -> _void)) #x88EB 0)
      (for ([pair (in-list '((#x0D05 1) (#x0D02 0) (#x0D03 0) (#x0D04 0)))])
        ((raw-bind f "glPixelStorei" (_fun _uint32 _int -> _void)) (car pair) (cadr pair)))
      (define data (make-bytes (* 4 (gl-fixture-width f) (gl-fixture-height f))))
      ((raw-bind f "glReadPixels" (_fun _int _int _int _int _uint32 _uint32 _bytes -> _void))
       0 0 (gl-fixture-width f) (gl-fixture-height f) #x1908 #x1401 data)
      data) #:wait? #t))
