#lang racket/base
;; Required selected Ganesh test; never a software-raster fallback. The adapter
;; supplies a real GPU final target, not a physical window. GUI acceptance is
;; separately inherited from 0.61 by the 0.62 validator.
(require rackunit racket/class racket/list racket/cmdline json
         (prefix-in sk: "../main.rkt") (prefix-in gpu: "../gpu.rkt")
         "../gpu-egl.rkt" "../gpu-dc.rkt" "gpu-dc-consumer-fixtures.rkt"
         "../private/gpu-frame-target-cache.rkt" "../private/gpu-io-trace.rkt"
         (submod "../private/gpu-presenter.rkt" adapter-internals))
(provide gpu-frame-target-native-tests gpu-frame-target-native-test-count)
(define backend (make-parameter 'auto))
(define adapter (make-parameter 'hardware))
(define measurements (box '()))
(define (selected)
  (if (eq? (backend) 'auto)
      (case (system-type 'os) [(macosx) 'metal] [(windows) 'direct3d] [else 'egl])
      (backend)))
(struct fixture (context presenter target render resize presents) #:transparent)
(define (with-fixture proc)
  (define ctx
    (case (selected)
      [(egl) (make-egl-gpu-context)]
      [(metal) (gpu:make-gpu-context #:backend 'metal)]
      [(direct3d) (gpu:make-gpu-context #:backend 'direct3d #:adapter (adapter))]
      [else (error 'gpu-frame-target-native "unsupported backend")]))
  (define target #f) (define presenter #f) (define presents 0) (define acquisitions 0)
  (define metrics (presentation-metrics 64 48 32 24))
  (define (close-adapter)
    (when target (sk:skia-close! target) (set! target #f))
    (gpu:gpu-context-close! ctx))
  (dynamic-wind
   void
   (lambda ()
     (define native-backend (gpu:gpu-context-backend ctx))
     (define ad
       (presentation-adapter native-backend ctx (lambda () metrics)
         (lambda (m receive)
           (gpu:call-with-gpu-context ctx
             (lambda ()
               (define w (hash-ref m 'pixel_width)) (define h (hash-ref m 'pixel_height))
               (unless (and target (= w (sk:surface-width target)) (= h (sk:surface-height target)))
                 (when target (sk:skia-close! target))
                 (set! target (gpu:make-gpu-surface ctx w h)))
               (set! acquisitions (add1 acquisitions))
               ;; Rotating drawable identities must NOT churn the staging pool.
               (receive (sk:surface-canvas target)
                        (hasheq 'backend (symbol->string native-backend)
                                'target_identity (format "slot-~a" (modulo acquisitions 2)))
                        (lambda () (gpu:gpu-flush-and-submit! ctx) (set! presents (add1 presents)))))))
         (lambda (_thunk) (void)) close-adapter
         (lambda () (hasheq 'fixture "real GPU final surface; no GUI"))))
     (set! presenter (make-presenter ad void raise))
     (proc
      (fixture ctx presenter (lambda () target)
        (lambda (paint)
          (gpu:gpu-presenter-set-render! presenter paint)
          (gpu:gpu-presenter-render! presenter))
        (lambda (pw ph lw lh [visible? #t])
          (set! metrics (presentation-metrics pw ph lw lh #:visible? visible?)))
        (lambda () presents))))
   (lambda () (if presenter (gpu:gpu-presenter-close! presenter) (close-adapter)))))
(define (draw f proc)
  ((fixture-render f) (lambda (frame) (call-with-gpu-frame-dc frame proc))))
(define (size! f pw ph lw lh [visible? #t]) ((fixture-resize f) pw ph lw lh visible?))
(define (stats f) (hash-ref (gpu:gpu-presenter-info (fixture-presenter f)) 'frame_target_cache))
(define (stat f key) (hash-ref (stats f) key))
(define (read-target f)
  (gpu:call-with-gpu-context (fixture-context f)
    (lambda () (gpu:gpu-surface->rgba-bytes ((fixture-target f)) #:premultiplied? #t))))
(define (pixel data width x y)
  (define i (* 4 (+ x (* width y)))) (bytes->list (subbytes data i (+ i 4))))
(define (fill dc color [x 2] [y 2] [w 8] [h 6])
  (send dc set-pen "black" 1 'transparent) (send dc set-brush color 'solid)
  (send dc draw-rectangle x y w h))
(define (kind-count events name)
  (count (lambda (e) (equal? (hash-ref e 'kind) name)) events))
(define (measure-steady reuse?)
  (define result #f) (define saved-fixture #f)
  (with-fixture
   (lambda (f)
     (set! saved-fixture f)
     (define ledger (box '())) (define previous #f)
     (parameterize ([current-frame-target-reuse? reuse?] [current-gpu-io-ledger ledger])
       (for ([i (in-range 32)])
         (check-eq? (draw f (lambda (dc)
           (when previous (check-false (eq? previous dc)) (check-false (send previous ok?)))
           (set! previous dc) (fill dc (if (even? i) "red" "blue")))) 'present-requested)
         (check-false (send previous ok?))))
     (check-equal? (kind-count (unbox ledger) "readback") 0)
     (check-false (ormap (lambda (e) (hash-ref e 'wait_requested #f)) (unbox ledger)))
     (check-equal? (stat f 'creations) (if reuse? 1 32))
     (check-equal? (stat f 'reuses) (if reuse? 31 0))
     (check-equal? ((fixture-presents f)) 32)
     (check-equal? (pixel (read-target f) 64 8 8) '(0 0 255 255))
     (set! result (hash-set* (stats f) 'frames 32 'readbacks 0
                            'mode (if reuse? "reuse" "fresh") 'backend (symbol->string (selected))))))
  ;; The adapter actually closes the context, after cached staging retirement.
  (check-true (stat saved-fixture 'closed)) (check-equal? (stat saved-fixture 'live_targets) 0)
  (check-equal? (stat saved-fixture 'retirements) (stat saved-fixture 'creations))
  (set-box! measurements (cons (hash-set* result 'context_closed #t
                           'retirements_after_close (stat saved-fixture 'retirements)
                           'live_targets_after_close (stat saved-fixture 'live_targets)) (unbox measurements))))
(define gpu-frame-target-native-tests
  (test-suite
   "Cached GPU frame staging: constructor reduction, pixels and retirement"
   (test-case "32 frames reuse one staging surface with fresh expired DCs"
     (measure-steady #t))
   (test-case "fresh reference path constructs and retires 32 staging surfaces"
     (measure-steady #f))
   (test-case "all real consumers match the fresh reference on final GPU pixels"
     (define workloads (make-consumer-workloads))
     (define (captures reuse?)
       (with-fixture (lambda (f)
         (size! f 320 240 320 240)
         (parameterize ([current-frame-target-reuse? reuse?])
           (for/list ([workload (in-list workloads)])
             (draw f (lambda (dc) (exercise-consumer! workload dc)))
             (read-target f))))))
     (define reference (captures #f)) (define cached (captures #t))
     (check-equal? (length cached) 12)
     (for ([a (in-list reference)] [b (in-list cached)])
       (check-equal? (bytes-length a) (bytes-length b))
       (check-true (for/and ([x (in-bytes a)] [y (in-bytes b)]) (<= (abs (- x y)) 2)))))
   (test-case "physical resize retires once and does not accumulate size variants"
     (with-fixture (lambda (f)
       (for ([e '((64 48 32 24) (80 60 40 30) (64 48 32 24))])
         (apply (fixture-resize f) e)
         (draw f (lambda (dc) (fill dc "red"))) (draw f (lambda (dc) (fill dc "blue"))))
       (check-equal? (stat f 'creations) 3) (check-equal? (stat f 'reuses) 3)
       (check-equal? (stat f 'retirements) 2) (check-equal? (stat f 'live_targets) 1))))
   (test-case "logical-only and fractional scale changes reuse physical storage"
     (with-fixture (lambda (f)
       (for ([logical '((32 24) (32 16) (32.5 24.5))])
         (size! f 64 48 (car logical) (cadr logical))
         (draw f (lambda (dc)
           (define-values (w h) (send dc get-size))
           (check-= w (car logical) 1e-9) (check-= h (cadr logical) 1e-9)
           (fill dc "red")))
         (define x (inexact->exact (floor (* 4 (/ 64 (car logical))))))
         (define y (inexact->exact (floor (* 4 (/ 48 (cadr logical))))))
         (check-equal? (pixel (read-target f) 64 x y) '(255 0 0 255)))
       (check-equal? (stat f 'creations) 1) (check-equal? (stat f 'reuses) 2))))
   (test-case "rotating drawable identities do not evict compatible staging"
     (with-fixture (lambda (f)
       (draw f void) (draw f void)
       (check-true (> (hash-ref (gpu:gpu-presenter-info (fixture-presenter f)) 'target_generation) 1))
       (check-equal? (stat f 'creations) 1) (check-equal? (stat f 'reuses) 1))))
   (test-case "exception cancels commit, discards staging and recovers cleanly"
     (with-fixture (lambda (f)
       (draw f (lambda (dc) (fill dc "red")))
       (define before (read-target f)) (define saved #f)
       (check-exn #rx"intentional-cached-error"
         (lambda () (draw f (lambda (dc)
           (set! saved dc) (fill dc "blue") (send dc start-alpha 0.5)
           (error 'test "intentional-cached-error")))))
       (check-false (send saved ok?)) (check-equal? ((fixture-presents f)) 1)
       (check-equal? (read-target f) before)
       (check-equal? (stat f 'live_targets) 0)
       (draw f (lambda (dc) (fill dc "blue")))
       (check-equal? (stat f 'creations) 2)
       (check-equal? (pixel (read-target f) 64 8 8) '(0 0 255 255)))))
   (test-case "continuation escape expires the DC and discards its staging"
     (with-fixture (lambda (f)
       (define saved #f)
       (check-eq? (let/ec out (draw f (lambda (dc) (set! saved dc) (out 'escaped)))) 'escaped)
       (check-false (send saved ok?)) (check-equal? ((fixture-presents f)) 0)
       (check-equal? (stat f 'live_targets) 0)
       (draw f void) (check-equal? (stat f 'creations) 2))))
   (test-case "close inside a callback retires staging before actual context close"
     (with-fixture (lambda (f)
       (define saved #f)
       (draw f (lambda (dc) (set! saved dc) (fill dc "red")
         (gpu:gpu-presenter-close! (fixture-presenter f))))
       (check-false (send saved ok?)) (check-equal? ((fixture-presents f)) 0)
       (check-eq? (gpu:gpu-presenter-state (fixture-presenter f)) 'closed)
       (check-equal? (stat f 'retirements) 1) (check-equal? (stat f 'live_targets) 0))))
   (test-case "explicit CPU snapshot survives resize, reuse and context closure"
     (define image #f)
     (dynamic-wind void
       (lambda ()
         (with-fixture (lambda (f)
           (draw f (lambda (dc) (fill dc "red") (set! image (send dc snapshot))))
           (draw f (lambda (dc) (fill dc "blue")))
           (size! f 80 60 40 30) (draw f void)))
         (check-false (gpu:gpu-image? image))
         (check-equal? (pixel (sk:image->rgba-bytes image) 64 8 8) '(255 0 0 255)))
       (lambda () (when image (sk:skia-close! image)))))
   (test-case "fresh DC state and root clearing prevent previous frame leakage"
     (with-fixture (lambda (f)
       (draw f (lambda (dc)
         (send dc set-background "red") (send dc clear)
         (send dc set-origin 3 3) (send dc set-clipping-rect 0 0 2 2)
         (send dc set-alpha 0.2)))
       (draw f (lambda (dc)
         (check-= (send dc get-alpha) 1 1e-9)
         (check-false (send dc get-clipping-region))
         (define-values (x y) (send dc get-origin))
         (check-= x 0 1e-9) (check-= y 0 1e-9)))
       (check-equal? (pixel (read-target f) 64 8 8) '(255 255 255 255))
       (check-equal? (stat f 'creations) 1))))
   (test-case "independent presenters keep independent targets and lifetimes"
     (with-fixture (lambda (a)
       (with-fixture (lambda (b)
         (draw a (lambda (dc) (fill dc "red")))
         (draw b (lambda (dc) (fill dc "blue")))
         (check-equal? (stat a 'creations) 1) (check-equal? (stat b 'creations) 1)
         (gpu:gpu-presenter-close! (fixture-presenter a))
         (draw b (lambda (dc) (fill dc "blue")))
         (check-equal? (stat b 'reuses) 1)
         (check-equal? (pixel (read-target b) 64 8 8) '(0 0 255 255)))))))
   (test-case "nondrawable frames allocate nothing and can resume"
     (with-fixture (lambda (f)
       (size! f 64 48 32 24 #f)
       (check-eq? (draw f (lambda (_) (error 'test "unexpected callback"))) 'skipped)
       (check-equal? (stat f 'creations) 0)
       (size! f 64 48 32 24) (draw f void)
       (size! f 64 48 32 24 #f) (draw f void)
       (size! f 64 48 32 24) (draw f void)
       (check-equal? (stat f 'creations) 1) (check-equal? (stat f 'reuses) 1))))
   (test-case "borrowed GPU surface API does not become a presenter-owned cache"
     (with-fixture (lambda (f)
       (gpu:call-with-gpu-context (fixture-context f)
         (lambda ()
           (sk:with-skia ([surface (gpu:make-gpu-surface (fixture-context f) 16 16)])
             (call-with-gpu-surface-dc surface (lambda (dc) (fill dc "red")))
             (check-false (sk:skia-closed? surface)))))
       (check-equal? (stat f 'creations) 0) (draw f void)
       (check-equal? (stat f 'creations) 1))))))
(define gpu-frame-target-native-test-count 14)
(module+ main
  (require rackunit/text-ui)
  (command-line #:once-each
    [("--backend") value "auto, egl, metal or direct3d" (backend (string->symbol value))]
    [("--adapter") value "hardware or warp (Direct3D)" (adapter (string->symbol value))]
    #:args () (void))
  (define failures (run-tests gpu-frame-target-native-tests))
  (when (zero? failures)
    (for ([m (in-list (reverse (unbox measurements)))])
      (display "gpu-frame-target-measurement: ") (write-json m) (newline)))
  (printf "gpu-frame-target-native: ~a cases, ~a failures; actual Ganesh final targets, no GUI.\n"
          gpu-frame-target-native-test-count failures)
  (exit (if (zero? failures) 0 1)))
