#lang racket/base
(require rackunit rackunit/text-ui racket/port "../private/live-port-util.rkt" "../private/check.rkt" "../private/live-native-lease.rkt")
(provide live-stream-pure-tests live-stream-pure-test-count)
(define live-stream-pure-test-count 26)
(define (options in out #:length [n #f] #:seekable? [seek? #f] #:limit [limit 1024] #:cancel [cancel #f])
  (live-port-options 'test in out n seek? #f #f limit cancel))
(define (short-input bs)
  (define at 0)
  (make-input-port 'short (lambda (buffer)
    (if (= at (bytes-length bs)) eof
        (begin (bytes-set! buffer 0 (bytes-ref bs at)) (set! at (add1 at)) 1))) #f void))
(define live-stream-pure-tests
 (test-suite "Live port utilities; no native execution"
  (test-case "pin denies access until released"
    (define owner (gensym)) (define pin (pin-live-output! 'test owner #f))
    (check-exn #rx"exclusively leased" (lambda () (check-live-pin! 'test owner)))
    (release-live-pin! pin) (check-not-exn (lambda () (check-live-pin! 'test owner))))
  (test-case "double lease is rejected"
    (define owner (gensym)) (define pin (pin-live-output! 'test owner #f))
    (check-exn exn:fail? (lambda () (pin-live-output! 'test owner #f)))
    (release-live-pin! pin))
  (test-case "release is idempotent"
    (define owner (gensym)) (define pin (pin-live-output! 'test owner #f))
    (release-live-pin! pin) (release-live-pin! pin)
    (check-not-exn (lambda () (check-live-pin! 'test owner))))
  (test-case "failed stream remains poisoned after unpin"
    (define owner (gensym)) (define pin (pin-live-output! 'test owner #f))
    (poison-live-pin! pin) (release-live-pin! pin)
    (check-not-exn (lambda () (check-live-pin! 'test owner)))
    (check-exn #rx"native output failed" (lambda () (check-live-fault! 'test owner)))
    (check-exn exn:fail? (lambda () (pin-live-output! 'test owner #f))))
  (test-case "invalid limit" (for ([n '(0 -1 1.0 #f)]) (check-exn exn:fail? (lambda () (options (open-input-bytes #"") #f #:limit n)))))
  (test-case "length is bounded" (check-exn exn:fail? (lambda () (options (open-input-bytes #"") #f #:length 20 #:limit 10))))
  (test-case "seekable requires length" (check-exn exn:fail? (lambda () (options (open-input-bytes #"") #f #:seekable? #t))))
  (test-case "seek base is current position" (define p (open-input-bytes #"abcdef")) (read-bytes 2 p) (check-equal? (options p #f #:length 4 #:seekable? #t) 2))
  (test-case "closed input" (define p (open-input-bytes #"")) (close-input-port p) (check-exn exn:fail? (lambda () (options p #f))))
  (test-case "closed output" (define p (open-output-bytes)) (close-output-port p) (check-exn exn:fail? (lambda () (options #f p))))
  (test-case "invalid event" (check-exn exn:fail? (lambda () (options (open-input-bytes #"") #f #:cancel 'bad))))
  (test-case "no callback reentry" (parameterize ([current-live-port-operation 'outer]) (check-exn #rx"re-enter" (lambda () (options (open-input-bytes #"") #f)))))
  (test-case "zero sized request" (check-equal? (call-with-values (lambda () (live-read-chunk 'test (open-input-bytes #"a") 0 #f #f)) list) '(#"" #f)))
  (test-case "short reads accumulate" (check-equal? (call-with-values (lambda () (live-read-chunk 'test (short-input #"abcdef") 6 #f #f)) list) '(#"abcdef" #f)))
  (test-case "EOF separate from data" (check-equal? (call-with-values (lambda () (live-read-chunk 'test (open-input-bytes #"ab") 3 #f #f)) list) '(#"ab" #t)))
  (test-case "peek preserves cursor" (define p (open-input-bytes #"abcdef")) (check-equal? (call-with-values (lambda () (live-read-chunk 'test p 4 #t #f)) list) '(#"abcd" #f)) (check-equal? (read-bytes 6 p) #"abcdef"))
  (test-case "cancel consumes nothing" (define p (open-input-bytes #"abc")) (check-exn #rx"cancelled" (lambda () (live-read-chunk 'test p 3 #f always-evt))) (check-equal? (read-byte p) 97))
  (test-case "64 KiB bound" (check-exn exn:fail? (lambda () (live-read-chunk 'test (open-input-bytes #"") 65537 #f #f))))
  (test-case "output counter" (define p (open-output-bytes)) (define count (box 0)) (live-write-all 'test p #"abc" count 10 #f) (check-equal? (unbox count) 3) (check-equal? (get-output-bytes p) #"abc"))
  (test-case "quota before chunk" (define p (open-output-bytes)) (check-exn exn:fail? (lambda () (live-write-all 'test p #"abc" (box 0) 2 #f))) (check-equal? (get-output-bytes p) #""))
  (test-case "SVG physical dimensions" (define-values (f end) (make-svg-header-filter 'test 64 48)) (define r (f #"<svg width=\"64\" height=\"48\"><rect/></svg>")) (end) (check-true (regexp-match? #rx#"width=\"64pt\"" r)) (check-true (regexp-match? #rx#"viewBox=\"0 0 64 48\"" r)))
  (test-case "split SVG header" (define-values (f end) (make-svg-header-filter 'test 64 48)) (check-equal? (f #"<?xml version=\"1.0\"?><sv") #"") (check-true (regexp-match? #rx#"<svg" (f #"g width=\"64\" height=\"48\">"))) (check-equal? (f #"<rect/></svg>") #"<rect/></svg>") (end))
  (test-case "duplicate SVG dimensions" (define-values (f end) (make-svg-header-filter 'test 64 48)) (check-exn exn:fail? (lambda () (f #"<svg width=\"1\" width=\"2\" height=\"3\">"))))
  (test-case "missing SVG dimensions" (define-values (f end) (make-svg-header-filter 'test 64 48)) (check-exn exn:fail? (lambda () (f #"<svg width=\"1\">"))))
  (test-case "incomplete SVG cannot finish" (define-values (f end) (make-svg-header-filter 'test 64 48)) (f #"<svg ") (check-exn exn:fail? end))
  (test-case "SVG header bound" (define-values (f end) (make-svg-header-filter 'test 64 48)) (check-exn exn:fail? (lambda () (f (make-bytes 16385 32)))))))
(module+ main
  (define failures (run-tests live-stream-pure-tests))
  (printf "live-stream-pure: ~a cases, ~a failures\n" live-stream-pure-test-count failures)
  (exit (if (zero? failures) 0 1)))
