#lang racket/base
(require ffi/unsafe "../unsafe/gpu-metal.rkt")
(provide load-metal-fixture! make-metal-fixture close-metal-fixture!
         metal-fixture-texture metal-fixture-producer metal-fixture-description
         metal-fixture-readback metal-fixture-unblock!)
(define library #f)
(define (load-metal-fixture! path) (set! library (ffi-lib path)))
(define-syntax-rule (define-call name type)
  (define (name . args)
    (unless library (error 'metal-fixture "fixture library was not explicitly loaded"))
    (apply (get-ffi-obj 'name library type) args)))
(define-call smi_new (_fun _pointer _int -> _pointer))
(define-call smi_texture (_fun _pointer -> _pointer))
(define-call smi_producer (_fun _pointer -> _pointer))
(define-call smi_describe (_fun _pointer _pointer _size -> _int))
(define-call smi_read (_fun _pointer _bytes _size -> _int))
(define-call smi_unblock (_fun _pointer -> _int))
(define-call smi_close (_fun _pointer -> _int))
(define-call smi_error (_fun -> _string/utf-8))
(struct fixture ([pointer #:mutable]))
(define (check result)
  (unless (equal? result 1) (error 'metal-fixture "~a" (smi_error))))
(define (live f) (or (fixture-pointer f) (error 'metal-fixture "fixture is closed")))
(define (make-metal-fixture context [variant 0])
  (define p (call-with-gpu-metal-device context (lambda (device) (smi_new device variant))))
  (unless p (error 'metal-fixture "~a" (smi_error)))
  (fixture p))
(define (close-metal-fixture! f)
  (when (fixture-pointer f)
    (define p (fixture-pointer f)) (set-fixture-pointer! f #f)
    (check (smi_close p))))
(define (metal-fixture-texture f) (smi_texture (live f)))
(define (metal-fixture-producer f) (smi_producer (live f)))
(define (metal-fixture-description f)
  (define buf (malloc _uint64 19))
  (check (smi_describe (live f) buf 19))
  (for/list ([i (in-range 19)]) (ptr-ref buf _uint64 i)))
(define (metal-fixture-readback f)
  (define bytes (make-bytes (* 37 29 4)))
  (check (smi_read (live f) bytes (bytes-length bytes))) bytes)
(define (metal-fixture-unblock! f) (check (smi_unblock (live f))))
