#lang racket/base
(require rackunit rackunit/text-ui racket/file racket/class racket/draw
         "../main.rkt" "../bitmap.rkt")
(provide native-tests)

(define white (rgb 255 255 255))
(define red (rgb 255 0 0))
(define blue (rgb 0 0 255))
(define transparent (rgba 0 0 0 0))

(define native-tests
  (test-suite
   "Live Skia rendering (requires the pinned native library)"
   (test-case "load and preflight every native symbol"
     (check-not-exn skia-check!)
     (check-regexp-match #rx"^119[.]" (skia-native-version)))
   (test-case "clear and channel order on an odd-width surface"
     (with-skia ([s (make-surface 7 3 #:background "#12AB34")])
       (check-equal? (surface-pixel s 6 2) (rgb 18 171 52))
       (check-equal? (bytes-length (surface->rgba-bytes s)) 84)))
   (test-case "transparent initial pixels"
     (with-skia ([s (make-surface 2 2)])
       (check-equal? (surface->rgba-bytes s) (make-bytes 16))))
   (test-case "straight and premultiplied pixel output"
     (with-skia ([s (make-surface 1 1 #:background (rgba 255 0 0 128))])
       (check-equal? (surface->rgba-bytes s) (bytes 255 0 0 128))
       (check-equal? (surface->rgba-bytes s #:premultiplied? #t) (bytes 128 0 0 128))))
   (test-case "pixel bounds checked"
     (with-skia ([s (make-surface 2 2)])
       (for ([xy '((-1 0) (0 -1) (2 0) (0 2) (0.5 0))])
         (check-exn exn:fail:contract? (lambda () (apply surface-pixel s xy))))))
   (test-case "rectangle fill and exact interior pixels"
     (with-skia ([s (make-surface 20 20 #:background 'white)]
                 [p (make-paint #:color 'red #:antialias? #f)])
       (draw-rect (surface-canvas s) 3 4 6 7 p)
       (check-equal? (surface-pixel s 5 6) red)
       (check-equal? (surface-pixel s 1 1) white)
       (check-equal? (surface-pixel s 9 6) white)))
   (test-case "circle, oval and rounded rectangle"
     (with-skia ([s (make-surface 80 30)] [p (make-paint #:color 'blue)])
       (define c (surface-canvas s))
       (draw-circle c 10 15 7 p)
       (draw-oval c 25 8 20 14 p)
       (draw-rounded-rect c 50 5 20 20 5 5 p)
       (for ([x '(10 35 60)]) (check-equal? (surface-pixel s x 15) blue))
       (check-equal? (surface-pixel s 0 0) transparent)))
   (test-case "stroke and line endpoints"
     (with-skia ([s (make-surface 20 20 #:background 'white)]
                 [p (make-paint #:color 'red #:style 'stroke #:stroke-width 4 #:antialias? #f)])
       (draw-line (surface-canvas s) 4 10 16 10 p)
       (check-equal? (surface-pixel s 10 10) red)
       (check-equal? (surface-pixel s 1 10) white)))
   (test-case "source-over composition"
     (with-skia ([s (make-surface 3 3 #:background 'white)]
                 [p (make-paint #:color (rgba 255 0 0 128))])
       (draw-paint (surface-canvas s) p)
       (define c (surface-pixel s 1 1))
       (check-equal? (rgba-red c) 255)
       (check-= (rgba-green c) 127 1)
       (check-= (rgba-blue c) 127 1)
       (check-equal? (rgba-alpha c) 255)))
   (test-case "paint copy and setters"
     (with-skia ([p (make-paint #:color 'red)] [q (paint-copy p)])
       (paint-set-color! p 'blue)
       (check-equal? (paint-color q) red)
       (check-equal? (paint-color p) blue)
       (paint-set-style! p 'stroke)
       (paint-set-stroke-width! p 2)
       (paint-set-antialias! p #f)
       (paint-set-cap! p 'round)
       (paint-set-join! p 'bevel)
       (paint-set-miter-limit! p 3)
       (paint-set-blend-mode! p 'multiply)))
   (test-case "path bounds versus tight cubic bounds"
     (with-skia ([p (make-path '((move 0 0) (cubic 0 100 100 100 100 0)))])
       (check-equal? (call-with-values (lambda () (path-bounds p)) list) '(0.0 0.0 100.0 100.0))
       (define bounds (call-with-values (lambda () (path-tight-bounds p)) list))
       (check-= (list-ref bounds 3) 75 0.001)))
   (test-case "imperative quadratic and cubic paths"
     (with-skia ([s (make-surface 32 32)] [p (make-paint #:color 'red)] [path (make-path)])
       (path-move-to! path 4 4)
       (path-quad-to! path 16 0 28 4)
       (path-cubic-to! path 30 16 30 24 28 28)
       (path-line-to! path 4 28)
       (path-close! path)
       (draw-path (surface-canvas s) path p)
       (check-equal? (surface-pixel s 16 16) red)))
   (test-case "even-odd fill creates a hole"
     (with-skia ([s (make-surface 30 30)] [p (make-paint #:color 'red)]
                 [path (make-path #:fill-rule 'even-odd)])
       (path-add-rect! path 2 2 26 26)
       (path-add-rect! path 10 10 10 10)
       (draw-path (surface-canvas s) path p)
       (check-equal? (surface-pixel s 5 5) red)
       (check-equal? (surface-pixel s 15 15) transparent)))
   (test-case "winding fill respects opposite contour directions"
     (with-skia ([path (make-path)])
       (path-add-rect! path 0 0 30 30 #:direction 'cw)
       (path-add-rect! path 10 10 10 10 #:direction 'ccw)
       (check-true (path-contains? path 5 5))
       (check-false (path-contains? path 15 15))))
   (test-case "path copies, fill rules and resets"
     (with-skia ([p (make-path)])
       (path-add-circle! p 10 10 4)
       (with-skia ([q (path-copy p)])
         (path-set-fill-rule! q 'even-odd)
         (path-reset! p)
         (check-false (path-contains? p 10 10))
         (check-true (path-contains? q 10 10))
         (check-eq? (path-fill-rule q) 'even-odd)
         (path-reset! q)
         (check-eq? (path-fill-rule q) 'winding))))
   (test-case "path oval and polygon drawing"
     (with-skia ([s (make-surface 30 30)] [p (make-paint #:color 'blue)] [path (make-path)])
       (path-add-oval! path 10 10 10 10)
       (check-true (path-contains? path 15 15))
       (draw-polygon (surface-canvas s) '((2 2) (8 2) (8 8) (2 8)) p)
       (check-equal? (surface-pixel s 5 5) blue)))
   (test-case "translation and scaling compose"
     (with-skia ([s (make-surface 30 30)] [p (make-paint #:color 'red #:antialias? #f)])
       (define c (surface-canvas s))
       (canvas-translate! c 10 10)
       (canvas-scale! c 2)
       (draw-rect c 1 1 3 3 p)
       (check-equal? (surface-pixel s 14 14) red)
       (check-equal? (surface-pixel s 5 5) transparent)))
   (test-case "positive rotation is clockwise in default coordinates"
     (with-skia ([s (make-surface 20 20)] [p (make-paint #:color 'red #:antialias? #f)])
       (define c (surface-canvas s))
       (canvas-translate! c 10 10)
       (canvas-rotate! c 90)
       (draw-rect c 0 0 4 2 p)
       (check-equal? (surface-pixel s 9 11) red)
       (check-equal? (surface-pixel s 11 9) transparent)))
   (test-case "radians, skew and reset are callable"
     (with-skia ([s (make-surface 20 20)] [p (make-paint #:color 'red)])
       (define c (surface-canvas s))
       (canvas-rotate-radians! c 1/3)
       (canvas-skew! c 1/2 0)
       (canvas-reset-transform! c)
       (draw-rect c 2 2 4 4 p)
       (check-equal? (surface-pixel s 3 3) red)))
   (test-case "rectangle clipping and difference"
     (with-skia ([s (make-surface 20 20)] [p (make-paint #:color 'red)])
       (define c (surface-canvas s))
       (canvas-clip-rect! c 2 2 16 16)
       (canvas-clip-rect! c 7 7 6 6 #:operation 'difference)
       (draw-paint c p)
       (check-equal? (surface-pixel s 3 3) red)
       (check-equal? (surface-pixel s 10 10) transparent)
       (check-equal? (surface-pixel s 0 0) transparent)))
   (test-case "path clipping"
     (with-skia ([s (make-surface 20 20)] [p (make-paint #:color 'red)] [path (make-path)])
       (path-add-circle! path 10 10 5)
       (canvas-clip-path! (surface-canvas s) path #:antialias? #t)
       (draw-paint (surface-canvas s) p)
       (check-equal? (surface-pixel s 10 10) red)
       (check-equal? (surface-pixel s 1 1) transparent)))
   (test-case "save and restore counts"
     (with-skia ([s (make-surface 4 4)])
       (define c (surface-canvas s))
       (check-equal? (canvas-save-count c) 1)
       (check-equal? (canvas-save! c) 1)
       (check-equal? (canvas-save! c) 2)
       (canvas-restore-to-count! c 2)
       (canvas-restore! c)
       (check-equal? (canvas-save-count c) 1)
       (check-exn #rx"base" (lambda () (canvas-restore! c)))))
   (test-case "scoped state restores transform and clip after an exception"
     (with-skia ([s (make-surface 20 20)] [p (make-paint #:color 'red)])
       (define c (surface-canvas s))
       (check-exn #rx"deliberate"
         (lambda ()
           (with-canvas-state c
             (canvas-translate! c 10 10)
             (canvas-clip-rect! c 0 0 1 1)
             (canvas-save! c)
             (error 'test "deliberate"))))
       (check-equal? (canvas-save-count c) 1)
       (draw-rect c 2 2 5 5 p)
       (check-equal? (surface-pixel s 3 3) red)))
   (test-case "protected state cannot be popped through another canvas alias"
     (with-skia ([s (make-surface 4 4)])
       (define c (surface-canvas s))
       (define alias (surface-canvas s))
       (with-canvas-state c
         (check-exn #rx"protected" (lambda () (canvas-restore! alias)))
         (check-exn #rx"protected" (lambda () (canvas-restore-to-count! alias 1))))
       (check-equal? (canvas-save-count c) 1)))
   (test-case "nested state scopes"
     (with-skia ([s (make-surface 4 4)])
       (define c (surface-canvas s))
       (with-canvas-state c
         (check-equal? (canvas-save-count c) 2)
         (with-canvas-state c (check-equal? (canvas-save-count c) 3))
         (check-equal? (canvas-save-count c) 2))
       (check-equal? (canvas-save-count c) 1)))
   (test-case "closing a surface inside a state scope is safe"
     (define s (make-surface 4 4))
     (define c (surface-canvas s))
     (check-not-exn (lambda () (with-canvas-state c (skia-close! s))))
     (check-true (skia-closed? c))
     (skia-close! s))
   (test-case "borrowed canvas keeps its surface alive across GC"
     (define-values (c weak)
       (let ([s (make-surface 4 4)])
         (values (surface-canvas s) (make-weak-box s))))
     (collect-garbage)
     (collect-garbage)
     (check-not-exn (lambda () (canvas-clear! c 'blue)))
     (check-not-false (weak-box-value weak))
     (skia-close! (weak-box-value weak)))
   (test-case "explicit closure invalidates borrowed canvases and is idempotent"
     (define s (make-surface 4 4))
     (define c (surface-canvas s))
     (skia-close! s)
     (skia-close! s)
     (check-exn #rx"closed" (lambda () (canvas-clear! c 'red)))
     (check-exn exn:fail:contract? (lambda () (skia-close! c))))
   (test-case "scoped resources close on exception and constructor failure"
     (define saved #f)
     (check-exn #rx"deliberate"
       (lambda ()
         (with-skia ([p (make-paint)])
           (set! saved p)
           (error 'test "deliberate"))))
     (check-true (skia-closed? saved))
     (define first #f)
     (check-exn exn:fail:contract?
       (lambda ()
         (with-skia ([p (let ([p (make-paint)]) (set! first p) p)]
                     [q (make-paint #:stroke-width -1)])
           (void))))
     (check-true (skia-closed? first)))
   (test-case "image snapshot survives source mutation and closure"
     (define s (make-surface 2 2 #:background 'red))
     (with-skia ([im (surface-snapshot s)] [dest (make-surface 4 4)])
       (canvas-clear! (surface-canvas s) 'blue)
       (skia-close! s)
       (draw-image (surface-canvas dest) im 1 1)
       (check-equal? (surface-pixel dest 1 1) red)
       (check-equal? (image->rgba-bytes im) (apply bytes (make-list-of-red-pixels 4)))))
   (test-case "RGBA input is copied, not borrowed"
     (define pixels (bytes 255 0 0 255 0 0 255 255))
     (with-skia ([im (rgba-bytes->image 2 1 pixels)] [s (make-surface 4 2)])
       (bytes-fill! pixels 0)
       (draw-image-rect (surface-canvas s) im 0 0 4 2 #:sampling 'nearest)
       (check-equal? (surface-pixel s 0 0) red)
       (check-equal? (surface-pixel s 3 1) blue)
       (check-equal? (image->rgba-bytes im) (bytes 255 0 0 255 0 0 255 255))))
   (test-case "native PNG signature, dimensions, decoding and repeatability"
     (with-skia ([s (make-surface 7 3 #:background 'red)])
       (define png (surface->png-bytes s))
       (check-equal? (subbytes png 0 8) #"\211PNG\r\n\032\n")
       (check-equal? (integer-bytes->integer png #f #t 16 20) 7)
       (check-equal? (integer-bytes->integer png #f #t 20 24) 3)
       (check-equal? png (surface->png-bytes s))
       (define bm (read-bitmap (open-input-bytes png) 'png/alpha))
       (check-true (send bm ok?))
       (define pixel (make-bytes 4))
       (send bm get-argb-pixels 0 0 1 1 pixel)
       (check-equal? pixel (bytes 255 255 0 0))))
   (test-case "PNG save refuses overwrite by default"
     (define file (make-temporary-file "racket-skia-test-~a.png"))
     (dynamic-wind void
       (lambda ()
         (with-skia ([s (make-surface 2 2)])
           (check-exn exn:fail:filesystem? (lambda () (save-png s file)))
           (save-png s file #:exists 'replace)
           (check-equal? (subbytes (file->bytes file) 0 8) #"\211PNG\r\n\032\n")))
       (lambda () (delete-file file))))
   (test-case "bitmap bridge preserves channel order and premultiplied alpha"
     (with-skia ([s (make-surface 1 1 #:background (rgba 255 0 0 128))])
       (define bm (surface->bitmap s))
       (define argb (make-bytes 4))
       (send bm get-argb-pixels 0 0 1 1 argb #f #t)
       (check-equal? argb (bytes 128 128 0 0))))
   (test-case "invalid coordinates and options do not reach native drawing"
     (with-skia ([s (make-surface 8 8)] [p (make-paint)])
       (define c (surface-canvas s))
       (check-exn exn:fail:contract? (lambda () (draw-circle c 1 1 -1 p)))
       (check-exn exn:fail:contract? (lambda () (draw-rect c +nan.0 0 1 1 p)))
       (check-exn exn:fail:contract? (lambda () (draw-rect c 0 0 -1 1 p)))
       (check-exn exn:fail:contract? (lambda () (canvas-clip-rect! c 0 0 1 1 #:antialias? 1)))
       (check-exn exn:fail:contract? (lambda () (surface->png-bytes s #:compression 10)))))
   (test-case "closed paints, paths and images reject use"
     (with-skia ([s (make-surface 8 8)] [p (make-paint)] [path (make-path)]
                 [im (rgba-bytes->image 1 1 (bytes 255 0 0 255))])
       (define c (surface-canvas s))
       (skia-close! p)
       (skia-close! path)
       (skia-close! im)
       (check-exn #rx"closed" (lambda () (draw-circle c 2 2 1 p)))
       (check-exn #rx"closed" (lambda () (path-line-to! path 1 1)))
       (check-exn #rx"closed" (lambda () (draw-image c im 0 0)))))
   (test-case "cross-thread surface access is rejected before FFI"
     (with-skia ([s (make-surface 4 4)])
       (define results (make-channel))
       (define worker
         (thread
          (lambda ()
            (channel-put results
              (with-handlers ([exn:fail? exn-message])
                (surface-pixel s 0 0))))))
       (check-regexp-match #rx"another Racket thread" (channel-get results))
       (thread-wait worker)))
   (test-case "default typeface introspection"
     (with-skia ([tf (make-typeface)])
       (check-true (string? (typeface-family-name tf)))
       (check-true (<= 0 (typeface-weight tf) 1000))
       (check-true (<= 1 (typeface-width tf) 9))
       (check-not-false (memq (typeface-slant tf) '(upright italic oblique)))))
   (test-case "family typeface creation with style"
     (with-skia ([base (make-typeface)])
       (define family (typeface-family-name base))
       (unless (string=? family "")
         (with-skia ([tf (typeface-from-family family #:weight 'bold #:slant 'italic)])
           (check-true (typeface? tf))
           (check-true (string? (typeface-family-name tf)))
           (check-true (<= 0 (typeface-weight tf) 1000))
           (check-true (<= 1 (typeface-width tf) 9))))))
   (test-case "font constructor, getters and setters"
     (with-skia ([f (make-font #:size 24 #:scale-x 1.25 #:skew-x 0.1
                               #:edging 'antialias #:hinting 'normal)])
       (check-= (font-size f) 24.0 0.001)
       (check-= (font-scale-x f) 1.25 0.001)
       (check-= (font-skew-x f) 0.1 0.001)
       (check-equal? (font-edging f) 'antialias)
       (check-equal? (font-hinting f) 'normal)
       (font-set-size! f 31)
       (font-set-scale-x! f 0.9)
       (font-set-skew-x! f -0.2)
       (font-set-edging! f 'alias)
       (font-set-hinting! f 'slight)
       (font-set-subpixel! f #t)
       (font-set-linear-metrics! f #t)
       (font-set-embolden! f #t)
       (check-= (font-size f) 31.0 0.001)
       (check-= (font-scale-x f) 0.9 0.001)
       (check-= (font-skew-x f) -0.2 0.001)
       (check-equal? (font-edging f) 'alias)
       (check-equal? (font-hinting f) 'slight)
       (check-true (font-subpixel? f))
       (check-true (font-linear-metrics? f))
       (check-true (font-embolden? f))))
   (test-case "font metrics have a usable line spacing"
     (with-skia ([f (make-font #:size 32)])
       (define m (font-get-metrics f))
       (check-true (font-metrics? m))
       (check-true (real? (font-metrics-top m)))
       (check-true (<= (font-metrics-ascent m) 0))
       (check-true (>= (font-metrics-descent m) 0))
       (check-true (> (font-metrics-spacing m) 0))))
   (test-case "simple text measurement and bounds"
     (with-skia ([f (make-font #:size 32)] [p (make-paint #:style 'stroke #:stroke-width 2)])
       (check-true (> (measure-simple-text f "Hello") 0))
       (check-true (> (measure-simple-text f "Hello" #:paint p) 0))
       (define-values (x y w h) (simple-text-bounds f "Hello"))
       (for ([v (in-list (list x y w h))]) (check-true (real? v)))
       (check-true (> w 0))
       (check-true (> h 0))))
   (test-case "UTF-8 text maps to glyph ids"
     (with-skia ([f (make-font #:size 32)])
       (define glyphs (font-text->glyphs f "Hello"))
       (check-true (vector? glyphs))
       (check-equal? (vector-length glyphs) 5)
       (for ([g (in-vector glyphs)])
         (check-true (<= 0 g #xffff)))
       (check-equal? (font-char->glyph f #\H) (vector-ref glyphs 0))
       (check-equal? (vector-length (font-text->glyphs f "")) 0)))
   (test-case "glyph and simple-text outline paths are exposed"
     (with-skia ([f (make-font #:size 48)])
       (define gid (font-char->glyph f #\A))
       (define gp (font-glyph-path f gid))
       (when gp
         (define-values (_x _y w h) (path-tight-bounds gp))
         (check-true (> w 0))
         (check-true (> h 0))
         (skia-close! gp))
       (with-skia ([tp (simple-text-path f "ABC" 10 60)])
         (define-values (_x _y w h) (path-tight-bounds tp))
         (check-true (>= w 0))
         (check-true (>= h 0)))))
   (test-case "simple text drawing changes raster pixels"
     (with-skia ([s (make-surface 240 80 #:background 'white)]
                 [f (make-font #:size 40)]
                 [p (make-paint #:color 'black)])
       (draw-simple-text (surface-canvas s) "Skia" 12 55 f p)
       (define bs (surface->rgba-bytes s))
       (check-true
        (for/or ([i (in-range 0 (bytes-length bs) 4)])
          (or (< (bytes-ref bs i) 250)
              (< (bytes-ref bs (+ i 1)) 250)
              (< (bytes-ref bs (+ i 2)) 250))))))
   (test-case "font retains a user typeface after wrapper closure"
     (define tf (make-typeface))
     (define f (make-font tf #:size 28))
     (skia-close! tf)
     (check-true (> (measure-simple-text f "Hi") 0))
     (skia-close! f))
   (test-case "closed font and typeface reject use"
     (define tf (make-typeface))
     (define f (make-font tf))
     (skia-close! tf)
     (skia-close! f)
     (check-exn #rx"closed" (lambda () (typeface-family-name tf)))
     (check-exn #rx"closed" (lambda () (font-size f))))
   (test-case "repeated allocation, PNG encoding and deterministic cleanup"
     (for ([i (in-range 32)])
       (with-skia ([s (make-surface 16 16)] [p (make-paint #:color 'red)])
         (draw-circle (surface-canvas s) 8 8 5 p)
         (check-true (> (bytes-length (surface->png-bytes s)) 40)))))))

(define (make-list-of-red-pixels count)
  (if (zero? count) '() (append '(255 0 0 255) (make-list-of-red-pixels (sub1 count)))))

(module+ test
  (skia-check!)
  (define failures (run-tests native-tests))
  (unless (zero? failures) (error 'native-tests "~a failures" failures)))
