#lang racket/base
(require rackunit rackunit/text-ui racket/list ffi/unsafe "../main.rkt" "../private/types.rkt"
         (submod "../canvas-matrix.rkt" testing))
(provide projective-native-tests)
(define (check-matrix-close a b)
  (for ([x (in-vector (matrix4->vector a))] [y (in-vector (matrix4->vector b))]) (check-= x y 1e-5)))
(define (page f) (make-output-page 100 80 f))
(define (has-feature? report feature status)
  (for/or ([e (in-list (output-audit-report-events report))])
    (and (eq? (output-audit-event-feature e) feature) (eq? (output-audit-event-status e) status))))
(define (projective-drawing c)
  (canvas-concat-matrix3! c (matrix3-perspective 1/32 0))
  (with-skia ([p (make-paint #:color 'red)]) (draw-rect c 16 16 32 32 p)))
(define projective-native-tests
  (test-suite "General canvas matrices: native storage, lifetime, and document policies"
   (test-case "row-major public data crosses the column-major ABI"
     (check-equal? (ctype-sizeof _sk-m44) 64)
     (define m (apply make-matrix4 (range 1 17)))
     (define native (native-matrix4 'test m))
     (check-equal? (for/list ([i (in-range 16)]) (ptr-ref native _float i))
                   '(1.0 5.0 9.0 13.0 2.0 6.0 10.0 14.0 3.0 7.0 11.0 15.0 4.0 8.0 12.0 16.0))
     (check-equal? (from-native-matrix4 native) m)
   )
   (test-case "existing native translation independently verifies readback"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-translate! c 17 23)
       (check-equal? (canvas-matrix4 c) (matrix4-translate 17 23)))
   )
   (test-case "existing native skew independently verifies off-diagonal entries"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-skew! c 2 3)
       (check-equal? (matrix4-ref (canvas-matrix4 c) 0 1) 2.0)
       (check-equal? (matrix4-ref (canvas-matrix4 c) 1 0) 3.0))
   )
   (test-case "set and read preserve all sixteen coefficients"
     (with-skia ([s (make-surface 80 80)])
       (define m (apply make-matrix4 (range 1 17)))
       (canvas-set-matrix4! (surface-canvas s) m)
       (check-equal? (canvas-matrix4 (surface-canvas s)) m))
   )
   (test-case "legacy affine inspection refuses a retained 3D matrix"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-set-matrix4! c (matrix4-translate 3 4 5))
       (check-exn exn:fail? (lambda () (canvas-transform c)))
       (check-equal? (matrix4-ref (canvas-matrix4 c) 2 3) 5.0))
   )
   (test-case "legacy affine replacement clears depth explicitly"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-set-matrix4! c (matrix4-translate 3 4 5))
       (canvas-set-transform! c (matrix-translate 7 8))
       (check-equal? (canvas-matrix4 c) (matrix4-translate 7 8))
       (check-equal? (canvas-transform c) (matrix-translate 7 8)))
   )
   (test-case "concatenation uses current times local"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-translate! c 10 20)
       (canvas-concat-matrix4! c (matrix4-scale 2 3))
       (check-equal? (matrix4-map-point (canvas-matrix4 c) 4 5) #(18.0 35.0 0.0)))
   )
   (test-case "3x3 concatenation embeds without losing existing z state"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define before (matrix4-translate 1 2 3))
       (canvas-set-matrix4! c before)
       (define local (matrix3-perspective 1/32 1/64))
       (canvas-concat-matrix3! c local)
       (check-matrix-close (canvas-matrix4 c) (matrix4-compose before (matrix3->matrix4 local))))
   )
   (test-case "3x3 replacement creates a complete new embedded matrix"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-set-matrix4! c (matrix4-translate 20 30 40))
       (define local (matrix3-perspective 1/32 0))
       (canvas-set-matrix3! c local)
       (check-equal? (canvas-matrix4 c) (matrix3->matrix4 local)))
   )
   (test-case "perspective affects raster coverage rather than just readback"
     (with-skia ([s (make-surface 64 64)] [p (make-paint #:color 'red #:antialias? #f)])
       (define c (surface-canvas s)) (canvas-set-matrix3! c (matrix3-perspective 1/32 0))
       (draw-rect c 16 16 32 32 p)
       (check-equal? (surface-pixel s 15 15) (rgb 255 0 0))
       (check-equal? (rgba-alpha (surface-pixel s 30 15)) 0))
   )
   (test-case "native concatenation retains the depth used by later projection"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s))
       (define a (matrix4-perspective 128)) (define b (matrix4-rotate-x-degrees 90))
       (define d (matrix4-translate 5 6 7))
       (canvas-concat-matrix4! c a) (canvas-concat-matrix4! c b) (canvas-concat-matrix4! c d)
       (check-matrix-close (canvas-matrix4 c) (matrix4-compose a b d))
       (check-false (matrix4->matrix3 (canvas-matrix4 c))))
   )
   (test-case "early projection is not substituted by the native bridge"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s))
       (define a (matrix4-perspective 128)) (define b (matrix4-rotate-y-degrees 45))
       (canvas-concat-matrix4! c a) (canvas-concat-matrix4! c b)
       (define p (matrix3-map-point (matrix4-project-xy (canvas-matrix4 c)) 20 10))
       (define q (matrix3-map-point (matrix3-compose (matrix4-project-xy a) (matrix4-project-xy b)) 20 10))
       (check-true (> (abs (- (vector-ref p 0) (vector-ref q 0))) 1)))
   )
   (test-case "matrix replacement does not replace the existing device clip"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-clip-rect! c 10 15 30 35)
       (define bounds (canvas-device-clip-bounds c))
       (canvas-set-matrix4! c (matrix4-compose (matrix4-perspective 100) (matrix4-rotate-y-degrees 30)))
       (check-equal? (canvas-device-clip-bounds c) bounds))
   )
   (test-case "matrix scope composes and returns multiple values"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-translate! c 3 4)
       (define before (canvas-matrix4 c))
       (define-values (a b) (call-with-canvas-matrix c (matrix4-translate 5 6)
         (lambda () (check-equal? (canvas-matrix4 c) (matrix4-translate 8 10)) (values 7 9))))
       (check-equal? (list a b) '(7 9)) (check-equal? (canvas-matrix4 c) before))
   )
   (test-case "replacement matrix scope restores all sixteen coefficients"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define before (matrix4-rotate-y-degrees 30))
       (canvas-set-matrix4! c before)
       (with-canvas-matrix c matrix3-identity #:replace? #t
         (check-equal? (canvas-matrix4 c) matrix4-identity))
       (check-equal? (canvas-matrix4 c) before))
   )
   (test-case "scope accepts the existing affine values"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s))
       (with-canvas-matrix c (matrix-translate 10 20)
         (check-equal? (canvas-transform c) (matrix-translate 10 20)))
       (check-equal? (canvas-transform c) matrix-identity))
   )
   (test-case "exception cleanup restores matrix and clip"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-set-matrix4! c (matrix4-rotate-y-degrees 20))
       (define before (canvas-matrix4 c)) (define clip (canvas-device-clip-bounds c))
       (check-exn exn:fail? (lambda () (with-canvas-matrix c (matrix4-translate 40 50)
         (canvas-clip-rect! c 0 0 1 1) (error 'probe "expected"))))
       (check-equal? (canvas-matrix4 c) before) (check-equal? (canvas-device-clip-bounds c) clip))
   )
   (test-case "extra saves are unwound by the protected scope"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define count (canvas-save-count c))
       (with-canvas-matrix c (matrix4-translate 4 5)
         (canvas-save! c) (canvas-save! c) (canvas-translate! c 40 50))
       (check-equal? (canvas-save-count c) count) (check-equal? (canvas-matrix4 c) matrix4-identity))
   )
   (test-case "restore cannot cross the scope save floor"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define count (canvas-save-count c))
       (with-canvas-matrix c matrix4-identity
         (check-exn exn:fail? (lambda () (canvas-restore-to-count! c count))))
       (check-equal? (canvas-save-count c) count))
   )
   (test-case "bad inputs reject without modifying canvas state"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define before (canvas-matrix4 c))
       (check-exn exn:fail:contract? (lambda () (canvas-set-matrix4! c matrix3-identity)))
       (check-exn exn:fail:contract? (lambda () (canvas-concat-matrix3! c matrix4-identity)))
       (check-equal? (canvas-matrix4 c) before))
   )
   (test-case "scope contracts reject before saving"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define count (canvas-save-count c))
       (check-exn exn:fail:contract? (lambda () (call-with-canvas-matrix c matrix4-identity void #:replace? 'yes)))
       (check-exn exn:fail:contract? (lambda () (call-with-canvas-matrix c matrix4-identity (lambda (x) x))))
       (check-exn exn:fail:contract? (lambda () (call-with-canvas-matrix c matrix4-identity (lambda (#:x x) x))))
       (check-equal? (canvas-save-count c) count))
   )
   (test-case "concatenation overflow rejects before native state changes"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define before (matrix4-scale 1e30))
       (canvas-set-matrix4! c before)
       (check-exn exn:fail:contract? (lambda () (canvas-concat-matrix4! c (matrix4-scale 1e30))))
       (check-equal? (canvas-matrix4 c) before))
   )
   (test-case "closed surface canvases reject matrix queries and updates"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (skia-close! s)
       (check-exn exn:fail? (lambda () (canvas-matrix4 c)))
       (check-exn exn:fail? (lambda () (canvas-set-matrix3! c matrix3-identity)))
       (check-exn exn:fail? (lambda () (canvas-concat-matrix4! c matrix4-identity))))
   )
   (test-case "expired PDF page canvases reject general matrices"
     (with-skia ([d (make-pdf-document)])
       (define c (document-begin-page! d 80 80)) (document-end-page! d)
       (check-exn exn:fail? (lambda () (canvas-matrix4 c)))
       (check-exn exn:fail? (lambda () (canvas-concat-matrix3! c matrix3-identity))))
   )
   (test-case "expired SVG callback canvas rejects matrix readback"
     (define saved #f)
     (output->bytes (page (lambda (c) (set! saved c))) 'svg)
     (check-exn exn:fail? (lambda () (canvas-matrix4 saved)))
   )
   (test-case "cross-thread matrix queries and updates reject"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (define ch (make-channel))
       (define worker (thread (lambda ()
         (for ([f (in-list (list (lambda () (canvas-matrix4 c))
                                 (lambda () (canvas-set-matrix4! c matrix4-identity))
                                 (lambda () (canvas-concat-matrix3! c matrix3-identity))))])
           (channel-put ch (with-handlers ([exn:fail? (lambda (_) #t)]) (f) #f))))))
       (for ([i (in-range 3)]) (check-true (channel-get ch))) (thread-wait worker))
   )
   (test-case "readback snapshots survive later mutation and closure"
     (with-skia ([s (make-surface 80 80)])
       (define c (surface-canvas s)) (canvas-set-matrix4! c (matrix4-translate 1 2 3))
       (define saved (canvas-matrix4 c)) (canvas-set-matrix4! c matrix4-identity) (skia-close! s)
       (check-equal? saved (matrix4-translate 1 2 3))
       (check-true (immutable? (matrix4->vector saved))))
   )
   (test-case "preflight records general matrices for each document backend"
     (for ([backend '(pdf svg)])
       (define r (analyze-output-page (page projective-drawing) backend))
       (check-true (has-feature? r 'projective-transform 'needs-raster))
       (check-true (output-audit-report-blocking? r)))
   )
   (test-case "strict export rejects before the drawing body follows the matrix"
     (for ([backend '(pdf svg)])
       (define ran? #f)
       (check-exn exn:fail:output-audit?
         (lambda () (output->bytes/audit
           (page (lambda (c) (canvas-concat-matrix3! c (matrix3-perspective 1/32 0)) (set! ran? #t)))
           backend #:policy 'error)))
       (check-false ran?))
   )
   (test-case "explicit document raster groups resolve perspective"
     (for ([backend '(pdf svg)])
       (define-values (bs r) (output->bytes/audit
         (page (lambda (c) (draw-rasterized c 0 0 64 64 projective-drawing #:scale 2))) backend #:policy 'error))
       (check-true (has-feature? r 'projective-transform 'rasterized))
       (check-false (output-audit-report-blocking? r))
       (check-true (positive? (bytes-length bs)))
       (when (eq? backend 'svg) (check-true (regexp-match? #rx#"data:image/png;base64," bs))))
   )
   (test-case "canonical affine matrices pass strict vector-only export"
     (for ([backend '(pdf svg)])
       (define-values (_bs r) (output->bytes/audit
         (page (lambda (c) (with-canvas-matrix c (matrix4-translate 10 20)
           (with-skia ([p (make-paint #:color 'red)]) (draw-rect c 0 0 20 20 p))))) backend #:policy 'vector-only))
       (check-true (output-audit-report-vector-only? r)))
   )
   (test-case "pre-recorded perspective content keeps its provenance"
     (with-skia ([pic (call-with-picture 64 64 projective-drawing)])
       (for ([backend '(pdf svg)])
         (define r (analyze-output-page (page (lambda (c) (draw-picture c pic))) backend))
         (check-true (has-feature? r 'projective-transform 'needs-raster))))
   )
   (test-case "pre-recorded perspective content works inside explicit fallback"
     (with-skia ([pic (call-with-picture 64 64 projective-drawing)])
       (define-values (_bs r) (output->bytes/audit
         (page (lambda (c) (draw-rasterized c 0 0 64 64 (lambda (r) (draw-picture r pic)) #:scale 2))) 'svg #:policy 'error))
       (check-true (has-feature? r 'projective-transform 'rasterized)))
   )
   (test-case "concatenation retains exporter physical units and margins"
     (for ([backend '(pdf svg)])
       (define-values (_bs r) (output->bytes/audit
         (make-output-page 40 30 (lambda (c)
           (define before (canvas-matrix4 c))
           (canvas-concat-matrix4! c (matrix4-translate 2 3))
           (check-matrix-close (canvas-matrix4 c) (matrix4-compose before (matrix4-translate 2 3))))
           #:unit 'mm #:margins 4) backend #:policy 'vector-only))
       (check-true (output-audit-report-vector-only? r)))
   )
   (test-case "matrix scopes use the existing page lifetime guard"
     (with-skia ([d (make-pdf-document)])
       (define c (document-begin-page! d 80 80))
       (with-canvas-matrix c (matrix4-translate 1 2)
         (check-exn exn:fail? (lambda () (document-end-page! d))))
       (document-end-page! d) (check-equal? (document-page-count d) 1))
   )
   (test-case "a raster group does not fix an outer general matrix"
     (for ([backend '(pdf svg)])
       (define r (analyze-output-page
         (page (lambda (c) (canvas-concat-matrix3! c (matrix3-perspective 1/32 0))
           (draw-rasterized c 0 0 30 30 (lambda (r) (with-skia ([p (make-paint)]) (draw-rect r 0 0 20 20 p)))))) backend))
       (check-true (has-feature? r 'projective-transform 'needs-raster)))
   )
))
(module+ test
  (unless (zero? (run-tests projective-native-tests)) (error 'projective-native-tests "test failure")))
