#lang racket/base
(require rackunit racket/list racket/vector "../main.rkt" "typeface-fixtures.rkt"
         "text-blob-fixtures.rkt" "../private/text-run-data.rkt"
         (submod "../private/core.rkt" text-blob-internals))
(provide text-blob-native-tests)
(define-syntax-rule (with-fixture (f face) body ...)
  (with-skia ([face (typeface-from-bytes (fixture-font-bytes))]
              [f (make-font face #:size 20 #:hinting 'none #:linear-metrics? #t
                            #:subpixel? #t #:baseline-snap? #f #:edging 'alias)]) body ...))
(define-syntax-rule (with-layout-fixture (f sh) body ...)
  (with-skia ([face (typeface-from-bytes (text-blob-fixture-font-bytes))]
              [f (make-font face #:size 20 #:hinting 'none #:linear-metrics? #t
                            #:subpixel? #t #:baseline-snap? #f)]
              [sh (make-shaper f)]) body ...))
(define (near xs ys)
  (check-equal? (length xs) (length ys))
  (for ([x (in-list xs)] [y (in-list ys)]) (check-= x y 0.005)))
(define (render blob [mode 'native])
  (with-skia ([surface (make-surface 192 128 #:background 'white)]
              [ink (make-paint #:color 'black #:antialias? #f)])
    (parameterize ([current-text-output-mode mode]) (draw-text-blob (surface-canvas surface) blob 0 0 ink))
    (surface->rgba-bytes surface)))
(define (rectangle p) (call-with-values (lambda () (path-bounds p)) list))
(define (one-blob f [positions '((10 40) (30 40))])
  (with-skia ([b (make-text-blob-builder)])
    (text-blob-builder-add-positioned-run! b f '(2 3) positions)
    (text-blob-builder-finish! b)))
(define (one-info blob) (vector-ref (text-blob-runs blob) 0))
(define text-blob-native-tests
  (test-suite
   "Multi-run text blobs (native)"
   (test-case "empty finish returns false and consumes the builder"
     (with-skia ([b (make-text-blob-builder)])
       (check-equal? (text-blob-builder-run-count b) 0)
       (check-false (text-blob-builder-finish! b)) (check-true (skia-closed? b))
       (check-exn exn:fail? (lambda () (text-blob-builder-finish! b)))))
   (test-case "empty appends validate inputs without creating native runs"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f #())
         (text-blob-builder-add-horizontal-run! b f #() #())
         (text-blob-builder-add-positioned-run! b f #() #() #:text "" #:clusters #())
         (text-blob-builder-add-transformed-run! b f #() #())
         (check-equal? (text-blob-builder-run-count b) 0)
         (skia-close! f)
         (check-exn exn:fail? (lambda () (text-blob-builder-add-run! b f #()))))))
   (test-case "all four positioning families coexist in one retained blob"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2) #:origin '(10 30))
         (text-blob-builder-add-horizontal-run! b f '(3) '(30) #:y 40)
         (text-blob-builder-add-positioned-run! b f '(2) '((50 50)))
         (text-blob-builder-add-transformed-run! b f '(3) '((0 1 70 40)))
         (check-equal? (text-blob-builder-run-count b) 4)
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-true (text-blob? blob)) (check-true (skia-resource? blob))
           (check-equal? (map text-run-info-positioning (vector->list (text-blob-runs blob)))
                         '(default horizontal positioned transformed))
           (check-not-equal? (render blob) (make-bytes (* 192 128 4) 255))))))
   (test-case "different fonts and closed source owners retain independent runs"
     (with-fixture (f face)
       (with-skia ([other-face (typeface-from-bytes (fixture-font-bytes #:bold? #t))]
                   [other (make-font other-face #:size 30)] [b (make-text-blob-builder)])
         (text-blob-builder-add-positioned-run! b f '(2) '((10 40)))
         (text-blob-builder-add-positioned-run! b other '(3) '((40 60)))
         (skia-close! f) (skia-close! face) (skia-close! other) (skia-close! other-face)
         (with-skia ([blob (text-blob-builder-finish! b)] [a (text-blob-run-font blob 0)] [v (text-blob-run-font blob 1)])
           (check-= (font-size a) 20 0.001) (check-= (font-size v) 30 0.001)
           (with-skia ([af (font-typeface a)] [vf (font-typeface v)])
             (check-equal? (typeface-postscript-name af) (fixture-postscript))
             (check-equal? (typeface-postscript-name vf) (fixture-postscript #t)))
           (check-true (bytes? (render blob)))))))
   (test-case "source font mutation does not alter saved blob pixels or flags"
     (with-fixture (f face)
       (font-set-embedded-bitmaps! f #t) (font-set-force-auto-hinting! f #t)
       (with-skia ([blob (one-blob f)])
         (define pixels (render blob))
         (font-set-size! f 60) (font-set-baseline-snap! f #t)
         (font-set-embedded-bitmaps! f #f) (font-set-force-auto-hinting! f #f)
         (skia-close! f) (skia-close! face)
         (check-equal? (render blob) pixels)
         (with-skia ([snapshot (text-blob-run-font blob 0)])
           (check-= (font-size snapshot) 20 0.001)
           (check-true (font-embedded-bitmaps? snapshot)) (check-true (font-force-auto-hinting? snapshot))
           (check-false (font-baseline-snap? snapshot))))))
   (test-case "builder close deterministically releases untransferred private fonts"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2))
         (define saved (map retained-text-run-font (unbox (text-blob-builder-resource-runs b))))
         (skia-close! b)
         (check-true (andmap skia-closed? saved)) (check-false (skia-closed? f)))))
   (test-case "finish transfers snapshots so closing builder does not close blob fonts"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2))
         (define snapshot (retained-text-run-font (car (unbox (text-blob-builder-resource-runs b)))))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-true (skia-closed? b)) (check-false (skia-closed? snapshot))
           (skia-close! blob) (check-true (skia-closed? snapshot))))))
   (test-case "invalid append leaves prior builder state usable"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2))
         (check-exn exn:fail? (lambda () (text-blob-builder-add-positioned-run! b f '(2 3) '((1 2)))))
         (check-equal? (text-blob-builder-run-count b) 1)
         (with-skia ([blob (text-blob-builder-finish! b)]) (check-equal? (text-blob-run-count blob) 1)))))
   (test-case "cumulative builder limit rejects before modifying native run state"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (parameterize ([current-skia-byte-limit 400])
           (text-blob-builder-add-run! b f '(2))
           (check-exn exn:fail? (lambda () (text-blob-builder-add-run! b f '(3)))))
         (check-equal? (text-blob-builder-run-count b) 1)
         (with-skia ([blob (text-blob-builder-finish! b)]) (check-equal? (text-blob-run-count blob) 1)))))
   (test-case "glyph IDs are checked against each current source face"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (check-exn exn:fail? (lambda () (text-blob-builder-add-run! b f '(4))))
         (check-exn exn:fail? (lambda () (positioned-glyphs->path f '(65535) '((0 0)))))
         (check-equal? (text-blob-builder-run-count b) 0))))
   (test-case "builder operations preserve resource thread affinity"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (define c (make-channel))
         (define worker (thread (lambda () (channel-put c (with-handlers ([exn:fail? (lambda (_) 'rejected)])
                                                           (text-blob-builder-add-run! b f '(2)) 'unexpected)))))
         (check-eq? (channel-get c) 'rejected) (thread-wait worker)
         (check-equal? (text-blob-builder-run-count b) 0))))
   (test-case "default run snapshots native unshaped positions including origin"
     (with-fixture (f face)
       (define expected (font-glyph-positions f '(2 3) #:origin '(10 40)))
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2 3) #:origin '(10 40))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (for ([p (in-vector (text-run-info-positions (one-info blob)))] [q (in-vector expected)]) (near p q))))))
   (test-case "metadata and position inputs are copied into immutable detached records"
     (with-fixture (f face)
       (define text (bytes 65 86)) (define cs (vector 0 1))
       (define p0 (vector 10 40)) (define positions (vector p0 (vector 30 40)))
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-positioned-run! b f '(2 3) positions #:text text #:clusters cs)
         (bytes-fill! text 0) (vector-set! cs 0 1) (vector-set! p0 0 100)
         (with-skia ([blob (text-blob-builder-finish! b)])
           (define infos (text-blob-runs blob)) (define info (vector-ref infos 0))
           (skia-close! blob)
           (check-true (immutable? infos)) (check-true (immutable? (text-run-info-glyphs info)))
           (check-true (immutable? (text-run-info-positions info)))
           (check-equal? (text-run-info-utf8 info) #"AV")
           (check-equal? (text-run-info-clusters info) '#(0 1))
           (near (vector-ref (text-run-info-positions info) 0) '(10 40))))))
   (test-case "run font getters return independently owned font copies"
     (with-fixture (f face)
       (with-skia ([blob (one-blob f)] [a (text-blob-run-font blob 0)] [b (text-blob-run-font blob 0)])
         (font-set-size! a 50) (skia-close! blob)
         (check-= (font-size b) 20 0.001)
         (check-true (positive? (measure-simple-text a "AV")))
         (check-true (positive? (measure-simple-text b "AV"))))))
   (test-case "legacy positioned blobs participate in the new inspection API"
     (with-fixture (f face)
       (with-skia ([old (make-positioned-text-blob f '(2 3) '((10 40) (30 40)))] [new (one-blob f)])
         (check-equal? (text-blob-run-count old) 1)
         (check-equal? (text-blob-runs old) (text-blob-runs new))
         (check-equal? (render old) (render new)))))
   (test-case "run indexing rejects out-of-range and closed blobs"
     (with-fixture (f face)
       (with-skia ([blob (one-blob f)])
         (check-exn exn:fail? (lambda () (text-blob-run-font blob 1)))
         (skia-close! blob)
         (check-exn exn:fail? (lambda () (text-blob-runs blob)))
         (check-exn exn:fail? (lambda () (text-blob-intercepts blob -10 0))))))
   (test-case "native intercepts include default horizontal and XY runs"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2) #:origin '(10 40))
         (text-blob-builder-add-horizontal-run! b f '(2) '(30) #:y 40)
         (text-blob-builder-add-positioned-run! b f '(2) '((50 40)))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (define hits (text-blob-intercepts blob 30 35))
           (check-true (immutable? hits)) (check-equal? (vector-length hits) 3)
           (for ([pair (in-vector hits)] [expected '((10 18) (30 38) (50 58))]) (near pair expected))
           (check-equal? (text-blob-intercepts blob 100 110) #())))))
   (test-case "RSXform intercepts reject instead of silently omitting transformed runs"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-run! b f '(2))
         (text-blob-builder-add-transformed-run! b f '(3) '((1 0 40 40)))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-exn #rx"ignores RSXform" (lambda () (text-blob-intercepts blob -5 0)))))))
   (test-case "intercepts respect output budget and closed paint errors"
     (with-fixture (f face)
       (with-skia ([blob (one-blob f)] [paint (make-paint)])
         (parameterize ([current-skia-byte-limit 1])
           (check-exn exn:fail? (lambda () (text-blob-intercepts blob 30 35))))
         (skia-close! paint)
         (check-exn exn:fail? (lambda () (text-blob-intercepts blob 100 110 #:paint paint))))))
   (test-case "positioned outline utility uses glyph byte length and explicit XY positions"
     (with-fixture (f face)
       (with-skia ([path (positioned-glyphs->path f '(2 3) '((10 40) (30 40)))]
                   [blob (one-blob f)] [reference (text-blob->path blob)])
         (near (rectangle path) (rectangle reference))
         (check-equal? (path-point-count path) (path-point-count reference)))))
   (test-case "empty positioned outlines are owned and still validate closed source fonts"
     (with-fixture (f face)
       (with-skia ([path (positioned-glyphs->path f #() #())])
         (check-equal? (path-point-count path) 0) (skia-close! f)
         (check-equal? (path-point-count path) 0)
         (check-exn exn:fail? (lambda () (positioned-glyphs->path f #() #()))))))
   (test-case "transformed outlines apply RSXform placement, not only translation"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-transformed-run! b f '(2) '((0 1 30 40)))
         (with-skia ([blob (text-blob-builder-finish! b)] [path (text-blob->path blob)])
           ;; A is an 8x14 block above its baseline; +90 degrees gives 14x8.
           (near (rectangle path) '(30 40 14 8))))))
   (test-case "zero-scale transforms are legal and render no ink"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-transformed-run! b f '(2) '((0 0 30 40)))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-equal? (render blob) (make-bytes (* 192 128 4) 255))))))
   (test-case "atlas-transform values are accepted as glyph RSXforms"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-transformed-run! b f '(2) (list (make-atlas-transform 30 40 #:rotation 90)))
         (with-skia ([blob (text-blob-builder-finish! b)] [path (text-blob->path blob)])
           (near (rectangle path) '(30 40 14 8))))))
   (test-case "reallocation and native run coalescing do not corrupt earlier buffers"
     (with-fixture (f face)
       (with-skia ([b (make-text-blob-builder)])
         (for ([i (in-range 80)]) (text-blob-builder-add-positioned-run! b f '(2) (list (list i 40))))
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-equal? (text-blob-run-count blob) 80)
           (for ([info (in-vector (text-blob-runs blob))] [i (in-naturals)])
             (near (vector-ref (text-run-info-positions info) 0) (list i 40)))
           (check-true (bytes? (render blob)))))))
   (test-case "a real procedural fi ligature keeps one glyph and the original UTF-8 cluster"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "fi" #:features '("liga=1")))
       (check-equal? (shaped-run-glyph-count run) 1)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-shaped-run! b sh run #:origin '(10 40) #:text "fi")
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-equal? (text-run-info-glyphs (one-info blob)) '#(2))
           (check-equal? (text-run-info-utf8 (one-info blob)) #"fi")
           (check-equal? (text-run-info-clusters (one-info blob)) '#(0))))))
   (test-case "combining marks keep the shaper's positions and shared clusters"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "A\u0301"))
       (check-equal? (shaped-run-glyph-count run) 2)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-shaped-run! b sh run #:text "A\u0301")
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-equal? (text-run-info-clusters (one-info blob)) (list->vector (shaped-run-clusters run)))
           (for ([p (in-vector (text-run-info-positions (one-info blob)))] [q (in-list (shaped-run-positions run))])
             (near p q))))))
   (test-case "RTL glyph order and descending clusters are preserved without reversal"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "אב" #:direction 'rtl #:features '("liga=0")))
       (check-equal? (shaped-run-glyph-count run) 2)
       (with-skia ([b (make-text-blob-builder)])
         (text-blob-builder-add-shaped-run! b sh run #:text "אב")
         (with-skia ([blob (text-blob-builder-finish! b)])
           (check-equal? (text-run-info-glyphs (one-info blob)) (list->vector (shaped-run-glyphs run)))
           (check-equal? (text-run-info-clusters (one-info blob)) '#(2 0))))))
   (test-case "straight path placement keeps shaped advances and normal offsets"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "AV" #:features '("liga=0")))
       (with-skia ([path (make-path '((move 10 50) (line 180 50)))]
                   [blob (shaped-run->text-blob/on-path sh run path #:start-offset 5 #:normal-offset 3)])
         (for ([cs (in-vector (text-run-info-transforms (one-info blob)))] [p (in-list (shaped-run-positions run))])
           (near cs (list 1 0 (+ 15 (car p)) (+ 53 (cadr p)))))
         (skia-close! path) (skia-close! sh) (skia-close! f)
         (check-true (bytes? (render blob 'outline))))))
   (test-case "vertical path placement rotates the baseline and positive normal"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "A"))
       (with-skia ([path (make-path '((move 50 20) (line 50 100)))]
                   [blob (shaped-run->text-blob/on-path sh run path #:start-offset 5 #:normal-offset 3)])
         (near (vector-ref (text-run-info-transforms (one-info blob)) 0) '(0 1 47 25)))))
   (test-case "text-on-path selects a contour explicitly and never clamps an overrun"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "AV" #:features '("liga=0")))
       (with-skia ([path (make-path '((move 0 20) (line 2 20) (move 10 50) (line 180 50)))])
         (check-exn exn:fail? (lambda () (shaped-run->text-blob/on-path sh run path)))
         (check-exn exn:fail? (lambda () (shaped-run->text-blob/on-path sh run path #:contour 2)))
         (with-skia ([blob (shaped-run->text-blob/on-path sh run path #:contour 1)])
           (near (take (vector-ref (text-run-info-transforms (one-info blob)) 0) 2) '(1 0))))))
   (test-case "degenerate paths reject nonempty text but empty shaped runs yield false"
     (with-layout-fixture (f sh)
       (with-skia ([path (make-path)])
         (check-exn exn:fail? (lambda () (shaped-run->text-blob/on-path sh (shape-text sh "A") path)))
         (check-false (shaped-run->text-blob/on-path sh (shape-text sh "") path)))))
   (test-case "path text with a ligature follows shaped glyph count rather than character count"
     (with-layout-fixture (f sh)
       (define run (shape-text sh "fi"))
       (with-skia ([path (make-path '((move 10 50) (line 180 50)))]
                   [blob (shaped-run->text-blob/on-path sh run path #:text "fi")])
         (check-equal? (vector-length (text-run-info-transforms (one-info blob))) 1)
         (check-equal? (text-run-info-clusters (one-info blob)) '#(0)))))
))
