#lang scribble/manual

@title{Reusable Drawings — Record and Replay a Picture}

@(require "eval.rkt"
          (for-label racket
                     skia))

@section{The Finished Pattern Sheet}

@(pictures-finished-pict #:scale 0.63)

This tutorial builds the pattern sheet shown above. Each flower-shaped emblem
comes from the same recorded drawing. The copies have different positions,
sizes, and rotations.

The image is generated by the @racket[draw-pattern-sheet] function in
@filepath{pattern-sheet.rkt} during the documentation build. It is not a
separately prepared illustration.

The main idea is:

@centered{@bold{A picture records drawing operations once so the same drawing
can be replayed on other canvases.}}

@section{Draw One Emblem}

Start with a small drawing, 120 by 120 units. We already know the drawing
functions and canvas transforms needed for a flower-like emblem:

@pictures-racketblock+eval[
(define emblem-size 120)

(define (draw-emblem canvas)
  (define blue (make-paint #:color "#326BC4"))
  (define teal (make-paint #:color "#1EA7A0"))
  (define amber (make-paint #:color "#F0AA55"))
  (define ink
    (make-paint #:color "#24405E"
                #:style 'stroke
                #:stroke-width 2))
  (define highlight (make-paint #:color 'white))
  (with-canvas-state canvas
    (canvas-translate! canvas 60 60)
    (for ([petal-index (in-range 8)])
      (with-canvas-state canvas
        (canvas-rotate! canvas (* 45 petal-index))
        (draw-oval canvas -12 -49 24 36
                   (cond
                     [(zero? petal-index) amber]
                     [(even? petal-index) blue]
                     [else teal]))))
    (draw-circle canvas 0 0 19 amber)
    (draw-circle canvas 0 0 19 ink)
    (draw-circle canvas 0 -8 5 highlight)))
]

The @racket[draw-emblem] function receives a canvas and draws eight petals
around a common center. Seven petals alternate between blue and teal. The one
amber petal points upward in the emblem's local coordinates, making rotation
easy to see. The white dot is a highlight on the center.

@pictures-image[
(pictures-render-pict
 160 160
 (lambda (canvas)
   (with-canvas-state canvas
     (canvas-translate! canvas 20 20)
     (draw-emblem canvas)))
 #:scale 1.1)
]

Each call to this function executes the loop and issues the drawing operations
again. That is useful while creating the emblem, but we can also record the
operations and reuse them.

@section{Record a Picture}

The @racket[call-with-picture] function supplies a recording canvas to a
drawing function and returns a @racket[picture?] value:

@pictures-racketblock+eval[
(define (record-emblem)
  (call-with-picture emblem-size emblem-size draw-emblem))

(define emblem-picture (record-emblem))
]

The recording uses the same local coordinates as the original drawing. The
size arguments describe the nominal drawing region; they do not allocate a
120-by-120 raster image. A picture stores native drawing operations, not a
copy of the finished pixels.

The following queries inspect the recorded result:

@pictures-interaction[
(picture? emblem-picture)
(picture-width emblem-picture)
(picture-height emblem-picture)
]

To draw the picture, use @racket[draw-picture] rather than calling the
original drawing function:

@pictures-racketblock+eval[
(define (draw-one-replay canvas)
  (draw-picture canvas emblem-picture #:x 35 #:y 35))
]

@pictures-image[
(pictures-render-pict 190 190 draw-one-replay #:scale 0.95)
]

The recording callback has finished before this picture is replayed. The
picture is an immutable, owned Skia resource that keeps its recorded drawing
usable; the recording canvas itself is no longer valid after recording ends.

@section{Replay the Same Drawing}

The same picture can be drawn at several positions without calling
@racket[draw-emblem] again:

@pictures-racketblock+eval[
(define (draw-three-replays canvas)
  (draw-picture canvas emblem-picture #:x 28 #:y 24)
  (draw-picture canvas emblem-picture #:x 178 #:y 24)
  (draw-picture canvas emblem-picture #:x 328 #:y 24))
]

@pictures-image[
(pictures-render-pict 476 170 draw-three-replays #:scale 0.95)
]

The @racket[#:x] and @racket[#:y] arguments place the picture's recording
origin on the destination canvas. The recorded colors and shapes do not
change. Skia replays the same operations at each new position.

@section{Change the Size}

A picture can also be replayed at a different size. Supply both
@racket[#:width] and @racket[#:height] to specify the destination dimensions:

@pictures-racketblock+eval[
(define (draw-scaled-replays canvas)
  (draw-picture canvas emblem-picture
                #:x 44 #:y 83 #:width 82 #:height 82)
  (draw-picture canvas emblem-picture
                #:x 185 #:y 57 #:width 135 #:height 135)
  (draw-picture canvas emblem-picture
                #:x 374 #:y 27 #:width 190 #:height 190))
]

@pictures-image[
(pictures-render-pict 604 250 draw-scaled-replays #:scale 0.88)
]

Each copy uses the same recorded operations. Changing the destination size
scales the drawing as it is replayed; it does not enlarge a previously stored
bitmap. Supplying only one of the two size keywords is an error.

@section{Rotate the Replay}

Canvas transforms work with pictures just as they do with ordinary shapes.
Move the local origin to the picture's intended center, rotate the coordinate
system, and draw the picture around that origin:

@pictures-racketblock+eval[
(define (draw-placed-emblem canvas picture center-x center-y size angle)
  (with-canvas-state canvas
    (canvas-translate! canvas center-x center-y)
    (canvas-rotate! canvas angle)
    (draw-picture canvas picture
                  #:x (- (/ size 2))
                  #:y (- (/ size 2))
                  #:width size
                  #:height size)))

(define (draw-rotated-replays canvas)
  (define label-font (make-font #:size 20))
  (define label-paint (make-paint #:color "#24405E"))
  (for ([center-x '(115 305 495)]
        [angle '(0 24 -32)]
        [caption '("0°" "24°" "−32°")])
    (draw-simple-text canvas caption
                      (- center-x (/ (measure-simple-text label-font caption) 2))
                      52 label-font label-paint)
    (draw-placed-emblem canvas emblem-picture center-x 150 128 angle)))
]

@pictures-image[
(pictures-render-pict 610 250 draw-rotated-replays #:scale 0.9)
]

The @racket[draw-placed-emblem] function centers a scaled replay at a chosen
point. The captions give the rotation angles. The amber petal points up at 0°,
turns to the right at 24°, and turns to the left at −32°. Positive angles rotate
clockwise in the default canvas coordinates, where y increases downward.

The @racket[with-canvas-state] form restores the previous transform after
every copy. Without that scope, translations and rotations would accumulate
across successive placements.

@section{A Picture Is Not an Image}

A picture stores drawing operations. An image stores raster pixels. The
@racket[picture->image] function explicitly rasterizes a picture to an
immutable image with a chosen pixel size.

Create a small 48-by-48 image from our recorded emblem:

@pictures-racketblock+eval[
(define small-image
  (picture->image emblem-picture 48 48))
]

Now display the original picture and that actual image at the same size:

@pictures-racketblock+eval[
(define (draw-picture-image-comparison canvas)
  (define font (make-font #:size 17))
  (define ink (make-paint #:color "#24405E"))
  (draw-simple-text canvas "PICTURE REPLAY" 60 38 font ink)
  (draw-simple-text canvas "48 x 48 IMAGE AT 4x" 352 38 font ink)
  (draw-picture canvas emblem-picture
                #:x 60 #:y 65 #:width 192 #:height 192)
  (draw-image-rect canvas small-image 360 65 192 192
                   #:sampling 'nearest))
]

@pictures-image[
(pictures-render-pict 620 285 draw-picture-image-comparison #:scale 0.95)
]

The left copy is replayed from drawing operations at 192 by 192 pixels. The
right copy comes from the 48-by-48 image, displayed at exactly four times its
natural width and height with nearest-neighbor sampling. The larger pixel
blocks on the right show the difference between replay and raster enlargement.

The image is not a second drawing of the emblem. It comes directly from
@racket[picture->image] applied to the recorded picture.

@section{Build the Pattern Sheet}

The finished sheet creates one picture, then replays it in a grid. The position
comes from the row and column. A small variation in size and angle gives the
repeated drawing some rhythm.

Set up the page dimensions and its background:

@pictures-racketblock+eval[
(define sheet-width 1000)
(define sheet-height 760)
(define sheet-background "#EDF2F7")
]

The complete drawing function combines a heading, the repeated emblems, and
a caption. Only the loop places the pictures; it does not record another
picture for each cell.

@pictures-racketblock+eval[
(define (draw-pattern-sheet canvas)
  (define picture (record-emblem))
  (define paper (make-paint #:color "#FFFFFF"))
  (define ink (make-paint #:color "#24405E"))
  (define blue (make-paint #:color "#326BC4"))
  (define muted (make-paint #:color "#667A8D"))
  (define rule (make-paint #:color "#D4DEE9"))
  (define label-font (make-font #:size 16))
  (define title-font (make-font #:size 46))
  (define caption-font (make-font #:size 18))
  (define footer-font (make-font #:size 14))

  (draw-rounded-rect canvas 42 35 916 690 24 24 paper)
  (draw-simple-text canvas "SKIA / RECORDING STUDY" 82 94 label-font blue)
  (draw-simple-text canvas "A pattern of pictures" 79 161 title-font ink)
  (draw-simple-text canvas "One recording, many placements." 82 193
                    caption-font muted)
  (draw-rect canvas 82 216 836 2 rule)

  (for* ([row (in-range 3)]
         [column (in-range 5)])
    (define size (+ 72 (* 12 (modulo (+ (* 2 row) column) 4))))
    (define angle (* 13 (+ row (* 2 column))))
    (define center-x (+ 148 (* column 176)))
    (define center-y (+ 301 (* row 139)))
    (draw-placed-emblem canvas picture center-x center-y size angle))

  (draw-rect canvas 82 650 836 2 rule)
  (draw-simple-text canvas "REPLAY  /  RESIZE  /  ROTATE" 82 690 footer-font muted)
  (draw-simple-text canvas "11" 895 690 footer-font blue))
]

The drawing function records the emblem once for each sheet. Its fifteen
placements all reuse that picture. The recorded picture stays available until
all of the calls to @racket[draw-picture] have finished.

The final figure below comes from the exact same @racket[draw-pattern-sheet]
function as the standalone example:

@(pictures-finished-pict #:scale 0.63)

@section{Save the Pattern Sheet}

A complete raster program creates a surface, uses its canvas, and saves the
result as PNG:

@racketblock[
(define surface
  (make-surface sheet-width sheet-height
                #:background sheet-background))
(draw-pattern-sheet (surface-canvas surface))
(save-png surface "pattern-sheet.png" #:exists 'replace)
]

Run @filepath{pattern-sheet.rkt} with Racket to create
@filepath{pattern-sheet.png} in the current directory. For ordinary CPU
resources such as surfaces, paints, and pictures, normal Racket bindings are
appropriate when exact release time does not matter. Use deterministic cleanup
when prompt release is important.

@section{Try It}

Try changing the number of columns or rows in the pattern. Adjust the spacing
so all the emblems stay inside the page.

Try setting every angle to zero, then changing the rotation increment. The
single amber petal helps you see the orientation of each recorded emblem.

Try making the raster image 24 by 24 instead of 48 by 48 in the comparison.
Keep its displayed size unchanged and predict how the nearest-neighbor result
will change.

@section{Where to Go From Here}

This tutorial introduced recording one drawing, replaying pictures, changing
placement and scale, using transforms with recorded drawings, and explicitly
converting a picture into pixels.

The Guide will cover lower-level picture recorders, serialization to SKP,
trusted file loading, optional spatial indexes, and picture shaders. The next
tutorial will explore which drawing operations remain vectors in PDF and SVG,
and which ones need raster fallbacks.

The complete @filepath{pattern-sheet.rkt} example contains the finished
program from this tutorial.
