#lang racket/base
(require racket/class racket/list (prefix-in rd: racket/draw))
(provide draw-dc-compat-oracle draw-dc-text-sample)
(define (pattern w h [backing 1])
  (define bm (rd:make-bitmap w h #t #:backing-scale backing))
  (define pw (* w backing)) (define ph (* h backing))
  (define pixels (make-bytes (* 4 pw ph)))
  (for* ([y (in-range ph)] [x (in-range pw)])
    (define i (* 4 (+ x (* pw y))))
    (bytes-set! pixels i 255)
    (bytes-set! pixels (+ i 1) (+ 30 (* 40 (quotient x backing))))
    (bytes-set! pixels (+ i 2) (+ 20 (* 40 (quotient y backing))))
    (bytes-set! pixels (+ i 3) 70))
  (send bm set-argb-pixels 0 0 pw ph pixels #f #f #:unscaled? #t)
  bm)
(define (draw-dc-compat-oracle dc)
  (send dc set-smoothing 'unsmoothed)
  (send dc set-background (make-object rd:color% 20 30 40)) (send dc clear)
  (define source (pattern 4 4))
  (send dc draw-bitmap source 2 2)
  (define mask (rd:make-bitmap 4 4 #t))
  (define mp (make-bytes 64))
  (for* ([y (in-range 4)] [x (in-range 4)])
    (bytes-set! mp (* 4 (+ x (* 4 y))) (if (< x 2) 255 0)))
  (send mask set-argb-pixels 0 0 4 4 mp)
  (send dc draw-bitmap source 8 2 'solid (make-object rd:color% 0 0 0) mask)
  (send dc copy 2 2 4 4 14 2)
  (send dc draw-bitmap (pattern 4 4 2) 44 2)
  (define mono (rd:make-monochrome-bitmap 2 2))
  (send mono set-argb-pixels 0 0 2 2
        (bytes 255 0 0 0 255 255 255 255 255 255 255 255 255 0 0 0))
  (send dc set-background (make-object rd:color% 0 128 0))
  (send dc draw-bitmap mono 20 2 'opaque (make-object rd:color% 255 0 0))
  (define path (new rd:dc-path%))
  (send path rectangle 2 12 12 12) (send path rectangle 6 16 4 4)
  (define hole (new rd:region%)) (send hole set-path path 0 0 'odd-even)
  (send dc set-clipping-region hole)
  (send dc set-background (make-object rd:color% 240 120 20)) (send dc clear)
  (define a (new rd:region%)) (define b (new rd:region%))
  (send a set-rectangle 20 12 10 10) (send b set-rectangle 25 15 10 10) (send a intersect b)
  (send dc set-clipping-region a)
  (send dc set-background (make-object rd:color% 130 30 190)) (send dc clear)
  (define unassociated (new rd:region%)) (send unassociated set-rectangle 0 0 6 8)
  (send dc set-origin 35 12) (send dc set-clipping-region unassociated)
  (send dc set-origin 0 0) (send dc set-background (make-object rd:color% 255 230 0)) (send dc clear)
  (send dc set-clipping-region #f)
  (define strip (rd:make-bitmap 8 4 #t))
  (define pixels (make-bytes 128))
  (for* ([y (in-range 4)] [x (in-range 8)])
    (define i (* 4 (+ x (* 8 y))))
    (bytes-set! pixels i 255) (bytes-set! pixels (+ i 1) (* x 30))
    (bytes-set! pixels (+ i 2) 80) (bytes-set! pixels (+ i 3) 160))
  (send strip set-argb-pixels 0 0 8 4 pixels)
  (send dc draw-bitmap strip 2 32)
  (send dc set-alpha 0.0) ; copy must still use source replacement
  (send dc copy 2 32 6 4 4 32)
  (send dc set-alpha 1.0)
  (void))
(define (draw-dc-text-sample dc)
  (send dc set-background "white") (send dc clear)
  (send dc set-font (rd:make-font #:size 19 #:size-in-pixels? #t #:hinting 'unaligned))
  (send dc set-text-foreground "blue") (send dc draw-text "Skia: office AV á" 8 7 #t)
  (send dc set-text-foreground "red") (send dc draw-text "Racket שלום العربية" 8 37 #t)
  (send dc set-font (rd:make-font #:size 16 #:size-in-pixels? #t #:underlined? #t))
  (send dc set-text-foreground "black") (send dc draw-text "Characters / graphemes" 8 70 'grapheme)
  (void))
