#lang racket/base
(require racket/class racket/cmdline racket/file racket/math
         (prefix-in rd: racket/draw) "../dc.rkt")
(provide draw-dc-primitives draw-dc-oracle)
;; Both procedures consume the PUBLIC dc<%> API, not Skia drawing functions.
;; Deliberately no text or bitmap input: these belong to stage 0.54.
(define (draw-dc-oracle dc)
  (send dc set-smoothing 'unsmoothed)
  (send dc set-pen "black" 1 'transparent)
  (send dc set-background "white") (send dc clear)
  (for ([r (in-list '((0 0 (255 0 0)) (12 0 (0 200 0)) (0 10 (0 0 255)) (12 10 (255 255 0))))])
    (send dc set-brush (apply make-object rd:color% (caddr r)) 'solid) (send dc draw-rectangle (car r) (cadr r) 12 10))
  (send dc set-clipping-rect 4 5 3 4)
  (send dc set-origin 50 50)
  (send dc set-background (make-object rd:color% 120 30 200)) (send dc clear)
  (send dc set-origin 0 0)
  (send dc set-clipping-rect 18 15 4 3) (send dc erase)
  (send dc set-clipping-region #f))
(define (draw-dc-primitives dc)
  (send dc set-smoothing 'smoothed)
  (send dc set-background "white") (send dc clear)
  (send dc set-pen (rd:make-pen #:color "navy" #:width 3 #:join 'round))
  (send dc set-brush "lightblue" 'solid)
  (send dc draw-rounded-rectangle 18 18 122 92 14)
  (send dc set-brush "orange" 'solid) (send dc draw-ellipse 170 22 94 78)
  (send dc set-brush "gold" 'solid) (send dc draw-arc 300 18 130 90 0 (* 1.6 pi))
  (send dc set-brush "transparent" 'transparent)
  (send dc set-pen (rd:make-pen #:color "firebrick" #:width 4 #:style 'dot-dash #:cap 'butt))
  (send dc draw-line 22 138 438 138)
  (define p (new rd:dc-path%))
  (send p move-to 20 225) (send p curve-to 65 130 125 260 150 180)
  (send dc set-pen "navy" 3 'solid) (send dc draw-path p)
  (send dc set-pen "seagreen" 4 'solid) (send dc draw-spline 170 218 214 150 258 218)
  (send dc set-brush "coral" 'solid)
  (send dc draw-polygon '((295 . 205) (330 . 155) (380 . 180) (365 . 225)))
  (define t (send dc get-transformation))
  (send dc translate 95 282) (send dc rotate 0.4)
  (send dc set-pen "navy" 2 'solid) (send dc set-brush "lightblue" 'solid)
  (send dc draw-rectangle -52 -18 104 36)
  (send dc set-transformation t)
  (send dc set-clipping-rect 195 250 70 48)
  (send dc set-brush "purple" 'solid) (send dc set-alpha 0.5)
  (send dc draw-ellipse 178 234 110 80)
  (send dc set-clipping-region #f) (send dc set-alpha 1)
  (define ring (new rd:dc-path%))
  (send ring ellipse 320 248 95 55) (send ring ellipse 345 260 42 30)
  (send dc set-brush "lightblue" 'solid) (send dc draw-path ring 0 0 'odd-even))
(module+ main
  (define destination "dc-primitives.png")
  (command-line #:program "dc-primitives.rkt" #:args ([file "dc-primitives.png"])
                (set! destination file))
  (define dc (new skia-dc% [width 460] [height 320] [backing-scale 2]))
  (dynamic-wind void
    (lambda ()
      (draw-dc-primitives dc)
      (call-with-output-file destination
        (lambda (out) (write-bytes (send dc get-png-bytes) out)) #:mode 'binary #:exists 'replace))
    (lambda () (send dc close))))
