#lang racket/base
;; Shared recording corpus and independent-oracle scene. No GUI or GPU.
(require racket/class (prefix-in rd: racket/draw))
(provide make-dc-recording draw-dc-replay-oracle draw-dc-replay-scene)
(define (make-dc-recording draw)
  (define recorder (new rd:record-dc% [width 96] [height 72]))
  (draw recorder)
  (values (send recorder get-recorded-procedure)
          (rd:recorded-datum->procedure (send recorder get-recorded-datum))))
(define (fill dc color x y w h)
  (send dc set-brush color 'solid) (send dc draw-rectangle x y w h))
(define (draw-dc-replay-oracle dc)
  ;; No erase inside a recording: record-dc% may prune commands before erase.
  (send dc set-smoothing 'smoothed)
  (send dc set-pen "black" 1 'transparent)
  (send dc set-background "white") (send dc clear)
  (send dc start-alpha 0.5)
  (fill dc "red" 4 4 12 10) (fill dc "blue" 10 4 12 10)
  (send dc end-alpha)
  (send dc start-alpha 0.5)
  (fill dc "red" 4 20 16 8)
  (send dc start-alpha 0.5)
  (fill dc "blue" 10 18 14 10)
  (send dc end-alpha) (send dc end-alpha)
  (send dc set-alpha 0.25)
  (send dc start-alpha 0.5)
  (fill dc (make-object rd:color% 0 255 0) 34 20 10 8)
  (send dc end-alpha) (send dc set-alpha 1)
  ;; Clipping saved on the parent is applied once to the merged group.
  (send dc set-clipping-rect 30 4 5 8)
  (send dc start-alpha 0.5)
  (fill dc "red" 30 4 10 8)
  (send dc set-clipping-rect 32 4 8 8)
  (fill dc "blue" 32 4 8 8)
  (send dc end-alpha) (send dc set-clipping-region #f)
  (fill dc (make-object rd:color% 10 20 30) 0 0 2 2)
  (fill dc (make-object rd:color% 20 200 70) 46 30 2 2))
(define (draw-dc-replay-scene dc)
  (send dc set-smoothing 'smoothed)
  (send dc set-pen "black" 1 'transparent)
  (send dc set-background "white") (send dc clear)
  (send dc translate 3 4)
  (define region (new rd:region% [dc dc]))
  (send region set-rectangle 1 1 84 58)
  (send dc set-clipping-region region)
  (send dc start-alpha 0.75)
  (fill dc "orange" 1 1 52 25)
  (send dc start-alpha 0.5)
  (fill dc "blue" 24 5 42 25)
  (send dc end-alpha)
  (define bitmap (rd:make-bitmap 2 2 #t))
  (send bitmap set-argb-pixels 0 0 2 2
        (bytes 255 230 0 20 255 0 180 20 255 0 20 220 255 240 200 10))
  (send dc draw-bitmap bitmap 70 10)
  (send dc set-font (rd:make-font #:face "Arial" #:size 16 #:size-in-pixels? #t))
  (send dc set-text-foreground "navy")
  (send dc draw-text "Replay" 6 34 #t)
  (send dc end-alpha)
  (send dc set-clipping-region #f))
