#lang racket/base
(require racket/cmdline racket/file racket/path racket/string "../main.rkt")

(define ink "#20344e")
(define teal "#10988e")
(define blue "#3269d5")
(define orange "#efa02b")
(define pale "#edf0f4")
(define docs-uri "https://docs.racket-lang.org/")
(define (label c text x y [size 11] [color ink])
  (with-skia ([f (make-font #:size size #:linear-metrics? #t #:subpixel? #t #:hinting 'none)]
              [p (make-paint #:color color)])
    (draw-simple-text c text x y f p)))
(define (line c x0 y0 x1 y1 [color teal] [width 2])
  (with-skia ([p (make-paint #:color color #:stroke-width width)])
    (draw-line c x0 y0 x1 y1 p)))
(define (button c x y w h text [color blue] [size 16])
  (with-skia ([p (make-paint #:color color)])
    (draw-rounded-rect c x y w h 8 8 p))
  (label c text (+ x 12) (+ y (/ h 2) (* size 0.35)) size 'white))
(define (page draw title subtitle number)
  (make-output-page
   720 500
   (lambda (c)
     (line c 0 0 34 0 teal 3)
     (label c title 0 30 23)
     (label c subtitle 0 51 10.5)
     (draw c)
     (label c "RACKET / SKIA   |   LINKS AND DOCUMENT ANNOTATIONS" 0 437 9)
     (label c (number->string number) 652 437 9))
   #:margins 24 #:background 'white))

(define (escape-html s)
  (for/fold ([s s]) ([entry '(("&" . "&amp;") ("<" . "&lt;") (">" . "&gt;") ("\"" . "&quot;"))])
    (string-replace s (car entry) (cdr entry))))
(define (file-name s) (path->string (file-name-from-path s)))
(define (file-uri s)
  ;; Encode a single filename, not an entire URI. No extra package or network.
  (define out (open-output-string))
  (define digits "0123456789ABCDEF")
  (for ([b (in-bytes (string->bytes/utf-8 (file-name s)))])
    (if (or (<= 65 b 90) (<= 97 b 122) (<= 48 b 57) (memv b '(45 46 95 126)))
        (write-char (integer->char b) out)
        (begin (write-char #\% out)
               (write-char (string-ref digits (quotient b 16)) out)
               (write-char (string-ref digits (remainder b 16)) out))))
  (get-output-string out))

(define (make-registry prefix)
  (define (name suffix) (string-append prefix suffix))
  (define companion (string-append (file-uri (name ".companion.html")) "#note"))
  (define (cross-link c x y w h destination stem)
    (if (eq? (canvas-annotation-backend c) 'svg)
        (canvas-annotate-url!
         c x y w h
         (string-append (file-uri (name (string-append "." stem ".svg"))) "#"
                        (svg-destination-id destination #:id-prefix stem)))
        (canvas-link-destination! c x y w h destination)))
  (define links
    (page
     (lambda (c)
       (canvas-define-destination! c "overview" 0 0)
       (button c 0 78 302 44 "Racket documentation")
       (canvas-annotate-url! c 0 78 302 44 docs-uri)
       (button c 336 78 312 44 "Jump to the note" teal)
       (canvas-link-destination! c 336 78 312 44 "overview-note")
       (label c "An ordinary HTTPS link, added independently of text." 0 143 10)
       (label c "A forward destination in this document." 336 143 10)
       (button c 0 176 302 44 "Go to page 3")
       (cross-link c 0 176 302 44 "details" "destinations")
       (button c 336 176 312 44 "Open the local companion" teal 15)
       (canvas-annotate-url! c 336 176 312 44 companion)
       (label c "PDF: named destination. SVG: linked SVG file." 0 240 10)
       (label c "The runner creates this HTML file alongside the probes." 336 240 10)
       (canvas-define-destination! c "overview-note" 0 285)
       (with-skia ([p (make-paint #:color pale)]) (draw-rounded-rect c 0 280 648 103 8 8 p))
       (label c "This is the same-page destination." 15 305 16)
       (label c "Annotations are invisible. The button artwork is ordinary canvas drawing." 15 330 11)
       (label c "SVG fragments select predefined views; PDF links navigate to named points." 15 352 11)
       (label c "Use the actual PDF or interactive SVG, not the PNG, to test clicking." 0 411 11))
     "A drawing can also be a document" "URL regions, same-document destinations, and links across exported files." 1))
  (define transforms
    (page
     (lambda (c)
       (canvas-define-destination! c "transformed" 0 0)
       (label c "01  A rotated URL region" 0 81 12)
       (with-canvas-state c
         (canvas-translate! c 130 140)
         (canvas-rotate! c 20)
         (button c -70 -22 140 44 "Rotated link" orange 15)
         (canvas-annotate-url! c -70 -22 140 44 docs-uri))
       (label c "Native annotations use an axis-aligned hit rectangle." 0 207 10)
       (label c "02  A clipped URL region" 344 81 12)
       (with-canvas-state c
         (canvas-translate! c 344 106)
         (canvas-clip-rect! c 10 10 190 54)
         (button c 0 0 240 84 "Clipped link" teal 16)
         (canvas-annotate-url! c 0 0 240 84 docs-uri))
       (label c "Only the clipped rectangle remains clickable." 344 207 10)
       (label c "03  A recorded URL, replayed twice" 0 246 12)
       (with-skia ([pic
                    (call-with-picture 150 52
                     (lambda (pc)
                       (button pc 0 0 150 52 "Recorded URL" blue 14)
                       (canvas-annotate-url! pc 0 0 150 52 docs-uri)))])
         (draw-picture c pic #:x 10 #:y 272)
         (draw-picture c pic #:x 210 #:y 260 #:width 225 #:height 78))
       (button c 484 278 164 48 "Back to page 1" teal 14)
       (cross-link c 484 278 164 48 "overview" "links")
       (label c "Recorded URLs follow replay transforms. Named destinations are authored after replay." 0 365 10.5)
       (label c "Links survive vector output; rasterization discards interactivity." 0 405 11))
     "Links follow canvas coordinates" "Translation, rotation, scaling, clipping, and ordinary picture replay." 2))
  (define destinations
    (page
     (lambda (c)
       (canvas-define-destination! c "details" 0 0)
       (button c 0 78 302 44 "Back to the overview")
       (cross-link c 0 78 302 44 "overview" "links")
       (button c 336 78 312 44 "Jump to a Unicode name" teal 15)
       (canvas-link-destination! c 336 78 312 44 "α-section")
       (label c "This target was referenced before page 3 was drawn." 0 143 10)
       (label c "Names are copied, case-sensitive Unicode strings." 336 143 10)
       (button c 0 176 302 36 "Query-string escaping" blue 14)
       (canvas-annotate-url! c 0 176 302 36
         (string-append (file-uri (name ".companion.html")) "?one=1&two=2#note"))
       (button c 336 176 312 36 "Back to this page's top" teal 14)
       (canvas-link-destination! c 336 176 312 36 "details")
       (canvas-define-destination! c "α-section" 0 242)
       (with-skia ([p (make-paint #:color pale)]) (draw-rounded-rect c 0 235 648 142 8 8 p))
       (label c "Named point destination" 15 264 17)
       (label c "Destination names become deterministic ASCII IDs, without losing distinctions." 15 290 11)
       (label c "Duplicate definitions and unresolved references raise errors before publication." 15 313 11)
       (label c "A PDF may resolve a forward link on a later page. Each SVG has its own scope." 15 336 11)
       (label c "These are links and destinations, not PDF comments, forms, or bookmarks." 15 359 11)
       (label c "The companion link also checks XML escaping of an ampersand in the URI." 0 407 11))
     "Names, not page-number guesses" "Forward references, document scope, and stable SVG fragment identifiers." 3))
  (list (cons "links" links) (cons "transforms" transforms) (cons "destinations" destinations)))

(module+ main
  (define prefix
    (command-line #:program "document-links.rkt" #:args ([prefix "document-links-0.27"]) prefix))
  (define (name suffix) (string-append prefix suffix))
  (make-parent-directory* (name ".pdf"))
  (define registry (make-registry prefix))
  (save-output (map cdr registry) (name ".pdf") 'pdf #:exists 'replace
               #:title "Document links and destinations" #:raster-dpi 144)
  (for ([entry (in-list registry)])
    (define stem (string-append "." (car entry)))
    (save-output (cdr entry) (name (string-append stem ".svg")) 'svg #:exists 'replace
                 #:id-prefix (car entry) #:title (string-append "Document links: " (car entry)))
    (with-skia ([image (output-page->image (cdr entry) #:dpi 144)])
      (save-image image (name (string-append stem ".reference.png")) 'png #:exists 'replace)))
  (call-with-output-file (name ".companion.html")
    (lambda (p)
      (display "<!doctype html><html lang=\"en\"><meta charset=\"utf-8\"><title>Link target</title><h1 id=\"note\">The local link worked.</h1><p>This is a static test destination. No scripts or network requests are needed.</p></html>" p))
    #:exists 'replace)
  (call-with-output-file (name ".review.html")
    (lambda (p)
      (display "<!doctype html><html lang=\"en\"><meta charset=\"utf-8\"><title>Document link review</title><style>body{font:16px system-ui;margin:24px;color:#20344e;background:#edf0f4}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:16px 0 32px}figure{margin:0}object,img{display:block;width:100%;aspect-ratio:720/500;height:auto;background:white}figcaption{margin:8px 0}@media(max-width:900px){.pair{grid-template-columns:1fr}}</style><h1>Links and document annotations</h1>" p)
      (fprintf p "<p><a href=\"~a\">Open the actual three-page PDF</a>. Test its buttons and cross-page links in a PDF viewer.</p>" (escape-html (file-uri (name ".pdf"))))
      (display "<p>Left: an interactive SVG document, embedded with object, not img. Right: a separately drawn raster reference. PNGs have no links and are not PDF/SVG rasterizations. Opening an SVG by itself is the clearest way to test fragment navigation. Refresh to restore a navigated preview.</p>" p)
      (for ([entry (in-list registry)])
        (define stem (string-append "." (car entry)))
        (define svg (escape-html (file-uri (name (string-append stem ".svg")))))
        (define png (escape-html (file-uri (name (string-append stem ".reference.png")))))
        (fprintf p "<h2>~a</h2><p><a href=\"~a\">Open this SVG as a standalone document</a></p><section class=\"pair\"><figure><figcaption>Actual SVG: click the buttons</figcaption><object type=\"image/svg+xml\" data=\"~a\" aria-label=\"Interactive SVG\"><a href=\"~a\">Open SVG</a></object></figure><figure><figcaption>Independent raster reference: not interactive</figcaption><img src=\"~a\" alt=\"Raster reference\"></figure></section>"
                 (car entry) svg svg svg png))
      (display "</html>" p)) #:exists 'replace)
  (printf "Wrote ~a.pdf; 3 interactive SVGs; 3 independent raster references; companion HTML; ~a.review.html\n" prefix prefix))
