#lang racket/base
(require racket/file racket/path json "../main.rkt")
(define blue (rgb 48 103 211))
(define teal (rgb 14 149 142))
(define orange (rgb 239 161 37))
(define ink (rgb 32 52 78))
(define (label c text x y [size 12])
  (with-skia ([f (make-font #:size size #:linear-metrics? #t #:subpixel? #t #:hinting 'none)]
              [p (make-paint #:color ink)]) (draw-simple-text c text x y f p)))
(define (heading c title subtitle)
  (with-skia ([p (make-paint #:color teal)]) (draw-rect c 0 0 34 2 p))
  (label c title 0 33 24) (label c subtitle 0 57 11))
(define (footer c)
  (label c "RACKET / SKIA   |   OUTPUT CAPABILITY AND FALLBACK AUDIT" 0 444 9))
(define (plain-panel c)
  (with-skia ([gradient (make-linear-gradient-shader 0 0 300 0 (list blue teal orange))]
              [p (make-paint #:shader gradient)] [stroke (make-paint #:color ink #:style 'stroke #:stroke-width 2)])
    (draw-rounded-rect c 0 5 300 155 12 12 p)
    (draw-circle c 70 82 32 stroke)))
(define sksl
  "uniform float phase; half4 main(float2 p) {
     float t = .5+.5*sin(p.x*.05+p.y*.02+phase);
     return half4(mix(float3(.19,.40,.83),float3(.94,.63,.15),t),1);
   }")
(define (wave-panel c)
  (with-skia ([e (make-runtime-effect sksl)]
              [s (runtime-effect->shader e #:uniforms (hash 'phase .5))]
              [p (make-paint #:shader s)]) (draw-rect c 0 0 300 170 p)))
(define (shadow-panel c)
  (with-skia ([f (make-drop-shadow-image-filter 5 5 3 3 (rgba 0 0 0 110))]
              [p (make-paint #:color blue #:image-filter f)] [q (make-paint #:color orange)])
    (draw-rounded-rect c 14 16 228 112 14 14 p)
    (draw-circle c 245 118 37 q)))
(define (translated c x y f)
  (with-canvas-state c (canvas-translate! c x y) (f c)))
(define (page1 c)
  (heading c "Know what remains vector" "The drawing API is unchanged. Audited exports add a separate, immutable report.")
  (label c "01  Native geometry and a linear gradient" 0 89)
  (label c "02  An explicitly rasterized runtime shader" 352 89)
  (with-output-label "native-vector" (translated c 0 112 plain-panel))
  (with-output-label "runtime-fallback" (draw-rasterized c 352 112 300 170 wave-panel #:scale 2))
  (label c "Vector operations remain vector-only in the report." 0 322)
  (label c "The runtime panel is reported as a bounded 600 x 340 image." 0 350)
  (label c "No automatic rasterization or visual-equivalence claim is made by the auditor." 0 392 11)
  (footer c))
(define (page2 c)
  (heading c "Backend expansion is not vector preservation" "PDF receives an image filter; SVG uses a declared raster boundary around the same drawing.")
  (label c "01  A paint with a shadow image filter" 0 89)
  (label c "02  The same filtered drawing, explicit group" 352 89)
  (with-output-label "backend-filter"
    (if (eq? (canvas-annotation-backend c) 'svg)
        (draw-rasterized c 0 112 300 170 shadow-panel #:scale 2 #:padding 6)
        (translated c 0 112 shadow-panel)))
  (with-output-label "explicit-filter"
    (draw-rasterized c 352 112 300 170 shadow-panel #:scale 2 #:padding 6))
  (label c "PDF: native-expansion. SVG: explicit rasterization, then embedded image." 0 322 11)
  (label c "Padding is part of the report: each explicit panel is 624 x 364 pixels." 0 350 11)
  (label c "The audit reports conservative backend policy; inspect the exported files too." 0 392 11)
  (footer c))
(define (recorded-page picture)
  (lambda (c)
    (heading c "Recording does not erase resource provenance" "A picture recorded before auditing keeps a compact snapshot of the features it uses.")
    (label c "01  Recorded runtime content in a raster group" 0 89)
    (label c "02  A normal vector panel and an outer link" 352 89)
    (with-output-label "recorded-fallback"
      (draw-rasterized c 0 112 300 170 (lambda (rc) (draw-picture rc picture)) #:scale 2))
    (with-output-label "vector-and-link"
      (translated c 352 112 plain-panel)
      (canvas-annotate-url! c 352 112 300 170 "https://docs.racket-lang.org/"))
    (label c "The clickable region is on the document canvas, outside the rasterized group." 0 322 11)
    (label c "Placing an annotation inside a raster group is reported as semantic loss." 0 350 11)
    (label c "The unsafe preflight JSON demonstrates issues without emitting an unsafe SVG." 0 392 11)
    (footer c)))
(define (unsafe-page c)
  (with-output-label "unhandled-runtime" (wave-panel c))
  (with-output-label "unhandled-filter" (shadow-panel c)))
(define (write-json-file path value)
  (call-with-output-file path (lambda (o) (write-json value o) (newline o)) #:exists 'replace))
(module+ main
  (define argv (current-command-line-arguments))
  (when (> (vector-length argv) 1) (error 'output-audit "expected an optional output prefix"))
  (define prefix (if (zero? (vector-length argv)) "output/output-audit-0.29" (vector-ref argv 0)))
  (define (file suffix) (string-append prefix suffix))
  (make-directory* (or (path-only (string->path prefix)) (current-directory)))
  ;; Record before beginning either audit; the snapshot must still carry SkSL.
  (with-skia ([recorded (call-with-picture 300 170 wave-panel)])
    (define registry (list (cons "vector" page1) (cons "filters" page2)
                           (cons "recorded" (recorded-page recorded))))
    (define pages (map (lambda (entry) (make-output-page 720 500 (cdr entry) #:margins 24 #:background 'white)) registry))
    (define report
      (save-output/audit pages (file ".pdf") 'pdf #:exists 'replace #:policy 'error
                         #:title "Output capability audit"))
    (write-json-file (file ".pdf.audit.json") (output-audit-report->jsexpr report))
    (for ([entry (in-list registry)] [p (in-list pages)])
      (define stem (string-append "." (car entry)))
      (define report
        (save-output/audit p (file (string-append stem ".svg")) 'svg #:exists 'replace
                           #:policy 'error #:id-prefix (car entry)))
      (write-json-file (file (string-append stem ".audit.json")) (output-audit-report->jsexpr report))
      (with-skia ([im (output-page->image p #:dpi 144)])
        (save-image im (file (string-append stem ".reference.png")) 'png #:exists 'replace)))
    (write-json-file (file ".unsafe.audit.json")
      (output-audit-report->jsexpr (analyze-output-page (make-output-page 720 500 unsafe-page) 'svg)))
    (define base (path->string (file-name-from-path prefix)))
    (call-with-output-file (file ".review.html")
      (lambda (o)
        (display "<!doctype html><meta charset=\"utf-8\"><title>Output audit review</title><style>body{font:16px system-ui;margin:24px;background:#edf0f4;color:#20344e}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:12px 0 32px}img{width:100%;background:white}figure{margin:0}@media(max-width:900px){.pair{grid-template-columns:1fr}}</style><h1>Output capability and fallback audit</h1>" o)
        (fprintf o "<p><a href=\"~a.pdf\">Actual PDF</a> | <a href=\"~a.pdf.audit.json\">PDF report</a> | <a href=\"~a.unsafe.audit.json\">Unsafe preflight report (no SVG generated)</a></p>" base base base)
        (display "<p>Left: actual SVG. Right: separate raster reference, not a PDF/SVG rendering. Reports describe observed operations and known risks, not visual certification.</p>" o)
        (for ([entry (in-list registry)])
          (define tag (car entry))
          (fprintf o "<h2>~a</h2><p><a href=\"~a.~a.audit.json\">Audit report</a></p><div class=\"pair\"><figure><figcaption>Actual SVG</figcaption><img src=\"~a.~a.svg\"></figure><figure><figcaption>Independent raster reference</figcaption><img src=\"~a.~a.reference.png\"></figure></div>" tag base tag base tag base tag)))
      #:exists 'replace))
  (printf "Wrote ~a.pdf, 3 SVGs/references, 5 audit reports, and review HTML\n" prefix))
