#lang racket/base
(require racket/file racket/path racket/list racket/string json "../main.rkt")
(define blue (rgb 48 103 211))
(define teal (rgb 14 149 142))
(define orange (rgb 239 161 37))
(define ink (rgb 32 52 78))
(define (label c text x y [size 11])
  (with-skia ([font (make-font #:size size #:linear-metrics? #t #:subpixel? #t #:hinting 'none)]
              [paint (make-paint #:color ink)])
    (draw-simple-text c text x y font paint)))
(define (heading c title subtitle)
  (with-skia ([p (make-paint #:color teal)]) (draw-rect c 0 0 34 2 p))
  (label c title 0 32 23) (label c subtitle 0 56 10))
(define (footer c n)
  (label c "RACKET / SKIA   |   PERSISTENT PICTURES AND PICTURE SHADERS" 0 444 9)
  (label c (number->string n) 652 444 9))
(define (at c x y draw)
  (with-canvas-state c (canvas-translate! c x y) (draw c)))
(define (checker c x y)
  (with-skia ([a (make-paint #:color (rgb 240 243 247))]
              [b (make-paint #:color (rgb 224 230 238))])
    (draw-rect c x y 300 180 a)
    (for* ([row (in-range 12)] [col (in-range 19)] #:when (odd? (+ row col)))
      (draw-rect c (+ x (* col 16)) (+ y (* row 16))
                 (min 16 (- 300 (* col 16))) (min 16 (- 180 (* row 16))) b))))
(define (badge c)
  (with-skia ([gradient (make-linear-gradient-shader 0 0 240 0 (list blue teal))]
              [fill (make-paint #:shader gradient)]
              [accent (make-paint #:color orange)]
              [stroke (make-paint #:color ink #:style 'stroke #:stroke-width 3)])
    (draw-rounded-rect c 0 0 240 140 18 18 fill)
    (draw-circle c 70 70 33 accent)
    (draw-line c 125 45 208 45 stroke)
    (draw-line c 125 70 191 70 stroke)
    (draw-line c 125 95 208 95 stroke)))
(define (indexed-art c)
  (with-skia ([a (make-paint #:color blue)] [b (make-paint #:color teal)]
              [dot (make-paint #:color orange)])
    (for* ([row (in-range 6)] [col (in-range 12)])
      (define x (+ 20 (* col 48))) (define y (+ 20 (* row 48)))
      (draw-rounded-rect c x y 38 38 7 7 (if (even? (+ row col)) a b))
      (draw-circle c (+ x 19) (+ y 19) 7 dot))))
(define (tile-art c)
  (with-skia ([a (make-paint #:color teal)] [b (make-paint #:color blue)]
              [dot (make-paint #:color orange)])
    (draw-rect c 0 0 32 48 a) (draw-rect c 32 0 32 48 b)
    (draw-circle c 18 24 10 dot)))
(define (roundtrip-page original loaded)
  (lambda (c)
    (heading c "A drawing can outlive its recording session"
               "Left: the original picture. Right: native replay after saving and loading its SKP stream.")
    (label c "01  Live recording: known provenance" 0 92)
    (label c "02  Loaded stream: unknown provenance" 352 92)
    (checker c 0 110) (checker c 352 110)
    (with-output-label "live-recording" (draw-picture c original #:x 30 #:y 130))
    (with-output-label "loaded-stream" (draw-picture c loaded #:x 382 #:y 130))
    (label c "The native stream contains drawing commands and resources, not a screenshot." 0 320)
    (label c "This page deliberately uses report policy: an opaque imported picture is not certified as vector." 0 348 10)
    (label c "The validator also decodes this cache in a fresh Racket process and compares raw RGBA bytes." 0 380 10)
    (label c "Loading requires #:trusted? #t. A native SKP may contain SkSL; it is not a safe interchange format." 0 407 10)
    (footer c 1)))
(define (indexed-page picture)
  (lambda (c)
    (heading c "An index changes replay work, not the drawing"
               "A single R-tree-backed picture, replayed through two explicit clipping windows.")
    (label c "01  First window" 0 92) (label c "02  A translated window into the same picture" 352 92)
    (for ([x '(0 352)] [shift '(0 -230)])
      (checker c x 110)
      (with-output-label "indexed-window"
        (with-canvas-state c
          (canvas-translate! c x 110)
          (canvas-clip-rect! c 0 0 300 180)
          (draw-picture c picture #:x shift #:y -20))))
    (label c "Cull bounds are a drawing promise, not an exact painted-bounds or clipping query." 0 320)
    (label c "R-tree construction can tighten the native cull rectangle; the Racket nominal size stays unchanged." 0 348 10)
    (label c "SKP stores the native cull rectangle. Loading does not restore the in-memory R-tree." 0 380 10)
    (label c "Operation and byte counts are estimates. These panels establish correctness, not a speedup claim." 0 407 10)
    (footer c 2)))
(define (shader-panel c x paint)
  (checker c x 110)
  (define (draw r) (draw-rect r 0 0 300 180 paint))
  (if (memq (canvas-annotation-backend c) '(pdf svg))
      (draw-rasterized c x 110 300 180 draw #:scale 2)
      (at c x 110 draw)))
(define (shaders-page repeat-paint mirror-paint)
  (lambda (c)
    (heading c "A picture can become a sampled paint source"
               "The original tile picture is already closed. Both shaders retain the native drawing they need.")
    (label c "01  Repeated tile" 0 92) (label c "02  Mirrored tile, rotated local coordinates" 352 92)
    (with-output-label "repeat-shader" (shader-panel c 0 repeat-paint))
    (with-output-label "mirror-shader" (shader-panel c 352 mirror-paint))
    (label c "Tile bounds are picture coordinates. The shader matrix changes sampling, not the destination shape." 0 320 10)
    (label c "Each document panel is explicitly rasterized at 600 x 360; labels and checkerboards remain vector." 0 348 10)
    (label c "Sampling does not preserve recorded links. Add annotations to the receiving document canvas." 0 380 10)
    (label c "Native object IDs are process-local; neither IDs nor operation counts are persistent cache keys." 0 407 10)
    (footer c 3)))
(define (metadata name picture)
  (hasheq 'name name 'width (picture-width picture) 'height (picture-height picture)
          'cull_bounds (vector->list (picture-cull-bounds picture))
          'unique_id (picture-unique-id picture)
          'operations (picture-approximate-op-count picture)
          'nested_operations (picture-approximate-op-count picture #:nested? #t)
          'approximate_bytes (picture-approximate-bytes-used picture)))
(define (write-json-file path data)
  (call-with-output-file path (lambda (out) (write-json data out) (newline out)) #:exists 'replace))
(define (html-escape s)
  (for/fold ([text s]) ([p (in-list '(("&" . "&amp;") ("<" . "&lt;") (">" . "&gt;") ("\"" . "&quot;")))])
    (string-replace text (car p) (cdr p))))
(module+ main
  (define args (current-command-line-arguments))
  (when (> (vector-length args) 1) (error 'persistent-pictures "expected optional output prefix"))
  (define prefix (if (zero? (vector-length args)) "output/persistent-pictures-0.33" (vector-ref args 0)))
  (define (file suffix) (string-append prefix suffix))
  (make-directory* (or (path-only (string->path prefix)) (current-directory)))
  (with-skia ([original (call-with-picture 240 140 badge)]
              [indexed (call-with-picture 640 360 indexed-art #:spatial-index 'rtree)]
              [tile (call-with-picture 64 48 tile-art)]
              [repeat-shader (make-picture-shader tile #:tile-x 'repeat #:tile-y 'repeat #:sampling 'linear)]
              [mirror-shader (make-picture-shader tile #:tile-x 'mirror #:tile-y 'mirror #:sampling 'linear
                                                  #:local-matrix (matrix-rotate-degrees 20))]
              [repeat-paint (make-paint #:shader repeat-shader)] [mirror-paint (make-paint #:shader mirror-shader)])
    (save-picture original (file ".cache.skp") #:exists 'replace)
    (with-skia ([loaded (picture-from-file (file ".cache.skp") #:trusted? #t)]
                [expected (picture->image original 240 140)])
      (call-with-output-file (file ".expected.rgba")
        (lambda (out) (write-bytes (image->rgba-bytes expected) out)) #:mode 'binary #:exists 'replace)
      (write-json-file (file ".pictures.json")
        (list (metadata "original" original) (metadata "loaded" loaded)
              (metadata "indexed" indexed) (metadata "tile" tile)))
      (skia-close! tile)
      (define registry
        (list (cons "roundtrip" (roundtrip-page original loaded))
              (cons "indexed" (indexed-page indexed))
              (cons "shaders" (shaders-page repeat-paint mirror-paint))))
      (define pages (map (lambda (p) (make-output-page 720 500 (cdr p) #:margins 24 #:background 'white)) registry))
      ;; The known probe stream is drawn despite unknown provenance. This is an
      ;; explicit report-policy experiment, not a strict-export workaround.
      (define report (save-output/audit pages (file ".pdf") 'pdf #:policy 'report #:exists 'replace
                                        #:title "Persistent pictures and picture shaders"))
      (write-json-file (file ".pdf.audit.json") (output-audit-report->jsexpr report))
      (for ([entry (in-list registry)] [page (in-list pages)] [policy '(report vector-only error)])
        (define stem (string-append "." (car entry)))
        (define r (save-output/audit page (file (string-append stem ".svg")) 'svg #:policy policy
                                    #:exists 'replace #:id-prefix (car entry)))
        (write-json-file (file (string-append stem ".audit.json")) (output-audit-report->jsexpr r))
        (with-skia ([im (output-page->image page #:dpi 144)])
          (save-image im (file (string-append stem ".reference.png")) 'png #:exists 'replace)))
      (write-json-file (file ".opaque.audit.json")
        (for*/list ([backend '(pdf svg)] [raster? '(#f #t)])
          (define page
            (make-output-page 240 140
              (lambda (c)
                (if raster?
                    (draw-rasterized c 0 0 240 140 (lambda (r) (draw-picture r loaded)))
                    (draw-picture c loaded)))))
          (hasheq 'raster_group raster?
                  'report (output-audit-report->jsexpr (analyze-output-page page backend)))))
      (define base (html-escape (path->string (file-name-from-path prefix))))
      (call-with-output-file (file ".review.html")
        (lambda (out)
          (display "<!doctype html><meta charset=\"utf-8\"><title>Persistent pictures review</title><style>body{font:16px system-ui;margin:24px;background:#edf0f4;color:#20344e}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:32px}img{width:100%;background:white}figure{margin:0}@media(max-width:850px){.pair{grid-template-columns:1fr}}</style><h1>Persistent pictures and picture shaders</h1>" out)
          (fprintf out "<p><a href=\"~a.pdf\">Actual PDF</a> | <a href=\"~a.pictures.json\">Picture metadata</a> | <a href=\"~a.opaque.audit.json\">Opaque preflight reports</a> | <a href=\"~a.fresh.png\">Fresh-process cache replay</a></p>" base base base base)
          (display "<p>Left: actual SVG. Right: independent raster drawing, not a PDF/SVG rasterization. The roundtrip page deliberately uses report policy and retains a blocking unknown-provenance finding.</p>" out)
          (for ([entry (in-list registry)])
            (define name (car entry))
            (fprintf out "<h2>~a</h2><div class=\"pair\"><figure><figcaption>Actual SVG</figcaption><img src=\"~a.~a.svg\"></figure><figure><figcaption>Independent raster reference</figcaption><img src=\"~a.~a.reference.png\"></figure></div>" name base name base name)))
        #:exists 'replace)))
  (printf "Wrote ~a.pdf; 3 SVGs/references; 4 export audits; opaque preflights; SKP cache, RGBA expectation and metadata; review HTML\n" prefix))
