#lang racket/base
(require racket/file racket/path racket/list racket/string json "../main.rkt")
(define blue (rgb 48 103 211))
(define teal (rgb 14 149 142))
(define orange (rgb 239 161 37))
(define ink (rgb 32 52 78))
(define current-decisions (make-parameter #f))
(define (label c text x y [size 11])
  (with-skia ([font (make-font #:size size #:linear-metrics? #t #:subpixel? #t #:hinting 'none)]
              [paint (make-paint #:color ink)])
    (draw-simple-text c text x y font paint)))
(define (heading c title subtitle)
  (with-skia ([paint (make-paint #:color teal)]) (draw-rect c 0 0 34 2 paint))
  (label c title 0 32 22) (label c subtitle 0 55 10))
(define (footer c n)
  (label c "RACKET / SKIA   |   PORTABLE GEOMETRY AND IMAGE PLACEMENTS" 0 444 9)
  (label c (number->string n) 652 444 9))
(define (checker c x y width height)
  (with-skia ([a (make-paint #:color (rgb 242 245 248) #:antialias? #f)]
              [b (make-paint #:color (rgb 225 232 240) #:antialias? #f)])
    (draw-rect c x y width height a)
    (for* ([row (in-range (inexact->exact (ceiling (/ height 16))))]
           [column (in-range (inexact->exact (ceiling (/ width 16))))]
           #:when (odd? (+ row column)))
      (draw-rect c (+ x (* column 16)) (+ y (* row 16))
                 (min 16 (- width (* column 16))) (min 16 (- height (* row 16))) b))))
(define (group c page name x y width height draw)
  (define r (draw-output-group c x y width height draw #:label name))
  (when (current-decisions)
    (set-box! (current-decisions)
              (cons (cons page (output-group-report->jsexpr r)) (unbox (current-decisions)))))
  (void))
(define points (for/list ([x '(28 76 124 172 220 268)]) (list x 27)))
(define (markers c)
  (heading c "Markers stay ordinary vector geometry"
             "Explicit sizes, fill or stroke paints, ordered overlap, and a shared gradient coordinate system.")
  (label c "01  Filled circles and squares" 0 92)
  (label c "02  The paint can also stroke" 352 92)
  (checker c 0 110 300 96) (checker c 352 110 300 96)
  (group c "markers" "filled-markers" 0 110 300 96
    (lambda (local)
      (with-skia ([a (make-paint #:color blue)] [b (make-paint #:color teal)])
        (draw-markers local points 18 a)
        (draw-markers local (map (lambda (p) (list (car p) 69)) points) 18 b #:shape 'square))))
  (group c "markers" "outlined-markers" 352 110 300 96
    (lambda (local)
      (with-skia ([a (make-paint #:color blue #:style 'stroke #:stroke-width 3)]
                  [b (make-paint #:color orange #:style 'stroke #:stroke-width 3)])
        (draw-markers local points 24 a)
        (draw-markers local (map (lambda (p) (list (car p) 69)) points) 24 b #:shape 'square))))
  (label c "Size describes geometry, not the native point stroke width." 0 226 9)
  (label c "Stroke width is independent of marker diameter." 352 226 9)
  (label c "03  Overlap follows drawing order" 0 266)
  (label c "04  Gradient coordinates stay shared" 352 266)
  (checker c 0 284 300 96) (checker c 352 284 300 96)
  (group c "markers" "alpha-markers" 0 284 300 96
    (lambda (local)
      (with-skia ([p (make-paint #:color (rgba 48 103 211 120))])
        (draw-markers local '((82 48) (124 48) (166 48) (208 48)) 76 p))))
  (group c "markers" "gradient-markers" 352 284 300 96
    (lambda (local)
      (with-skia ([shader (make-linear-gradient-shader 0 0 300 0 (list blue teal orange))]
                  [p (make-paint #:shader shader)])
        (draw-markers local (map (lambda (p) (list (car p) 48)) points) 38 p))))
  (label c "All four groups replay natively. This page contains no embedded images." 0 410 10)
  (footer c 1))

(define (make-grid-source)
  (with-skia ([s (make-surface 30 24)] [a (make-paint #:color blue)]
              [b (make-paint #:color teal #:antialias? #f)]
              [dot (make-paint #:color orange)])
    (define c (surface-canvas s))
    (draw-rounded-rect c 0 0 30 24 4 4 a)
    (draw-rect c 6 5 17 12 b)
    (draw-circle c 3 12 1.5 dot)
    (surface-snapshot s)))
(define lattice
  (make-image-lattice '(6 23) '(5 17)
    #:cell-types '(default fixed-color default default transparent default default default default)
    #:colors (list 'black orange 'black 'black 'black 'black 'black 'black 'black)))
(define (grids source)
  (lambda (c)
    (heading c "Image grids do not need a panel bitmap"
               "Source pixels are cropped without resampling; their independent placements remain document elements.")
    (label c "01  Nine-patch: fixed borders, stretched center" 0 92)
    (label c "02  Lattice: color cell and transparent center" 352 92)
    (checker c 0 110 300 170) (checker c 352 110 300 170)
    (group c "grids" "nine-patch" 0 110 300 170
      (lambda (local) (draw-image-nine/portable local source '(6 5 17 12) 0 0 300 170)))
    (group c "grids" "mixed-lattice" 352 110 300 170
      (lambda (local) (draw-image-lattice/portable local source lattice 0 0 300 170 #:alpha 230)))
    (label c "Only the original crop-sized images are embedded; there is no 600 x 340 fallback panel." 0 320 10)
    (label c "The fixed-color cell is ordinary geometry. The transparent cell draws nothing." 0 347 10)
    (label c "Small destinations shrink fixed spans and collapse the stretch spans; plans expose every cell." 0 378 10)
    (label c "These are still raster source images, not vector artwork. A vector-only policy correctly rejects them." 0 409 10)
    (footer c 2)))

(define atlas-boxes '((0 0 24 24) (28 0 20 28) (52 0 20 20)))
(define (make-atlas-source)
  (with-skia ([s (make-surface 72 28)] [a (make-paint #:color blue)]
              [b (make-paint #:color teal)] [dot (make-paint #:color orange)])
    (define c (surface-canvas s))
    (draw-rounded-rect c 0 0 24 24 4 4 a) (draw-circle c 12 12 6 dot)
    (draw-rounded-rect c 28 0 20 28 4 4 b) (draw-rect c 33 8 10 12 dot)
    (draw-rounded-rect c 52 0 20 20 4 4 a) (draw-circle c 62 10 5 dot)
    (surface-snapshot s)))
(define placements
  (list (make-atlas-transform 64 84 #:scale 2.2 #:rotation -20 #:anchor '(12 12))
        (make-atlas-transform 188 84 #:scale 3 #:anchor '(10 14))
        (make-atlas-transform 314 84 #:scale 2.7 #:rotation 25 #:anchor '(10 10))
        (make-atlas-transform 440 84 #:scale 3.2 #:rotation -30 #:anchor '(12 12))
        (make-atlas-transform 568 84 #:scale 2.5 #:rotation 15 #:anchor '(10 14))))
(define placed-boxes (list (car atlas-boxes) (cadr atlas-boxes) (caddr atlas-boxes)
                           (car atlas-boxes) (cadr atlas-boxes)))
(define (sprites source)
  (lambda (c)
    (heading c "Atlas sprites stay individual image placements"
               "Integer source crops, local anchors, affine transforms, and reusable retained image resources.")
    (label c "01  Five placements from three cropped source images" 0 92)
    (checker c 0 110 652 170)
    (group c "atlas" "portable-sprites" 0 110 652 170
      (lambda (local) (draw-atlas/portable local source placements placed-boxes #:alpha 220)))
    (label c "A repeated crop shares its image resource; each sprite still has its own placement transform." 0 320 10)
    (label c "Alpha applies per sprite, not once to the completed group. No per-sprite tint is silently approximated." 0 347 10)
    (label c "The native draw-atlas API remains available for tint, effects, and fractional source regions." 0 378 10)
    (label c "Filtering and edge antialiasing remain renderer-dependent; this is not a pixel-identical batch promise." 0 409 10)
    (footer c 3)))

(define (write-json-file path data)
  (call-with-output-file path (lambda (out) (write-json data out) (newline out)) #:exists 'replace))
(define (html-escape s)
  (for/fold ([text s]) ([p (in-list '(("&" . "&amp;") ("<" . "&lt;") (">" . "&gt;") ("\"" . "&quot;")))])
    (string-replace text (car p) (cdr p))))
(define names '("markers" "grids" "atlas"))
(define (decision-rows entries)
  (for/list ([name (in-list names)])
    (hasheq 'page name 'groups (for/list ([entry (in-list entries)] #:when (equal? (car entry) name)) (cdr entry)))))
(module+ main
  (define args (current-command-line-arguments))
  (when (> (vector-length args) 1) (error 'portable-drawing "expected optional output prefix"))
  (define prefix (if (zero? (vector-length args)) "output/portable-drawing-0.35" (vector-ref args 0)))
  (define (file suffix) (string-append prefix suffix))
  (make-directory* (or (path-only (string->path prefix)) (current-directory)))
  (with-skia ([grid-source (make-grid-source)] [atlas-source (make-atlas-source)])
    (save-image grid-source (file ".grid-source.png") 'png #:exists 'replace)
    (save-image atlas-source (file ".atlas-source.png") 'png #:exists 'replace)
    (write-json-file (file ".plans.json")
      (hasheq 'nine (image-grid-plan->jsexpr (image-nine-plan 30 24 '(6 5 17 12) 0 0 300 170))
              'lattice (image-grid-plan->jsexpr (image-lattice-plan 30 24 lattice 0 0 300 170))
              'atlas (for/list ([t (in-list placements)] [b (in-list placed-boxes)])
                       (hasheq 'source b 'matrix (vector->list (atlas-transform-coefficients t))))))
    (define draws (list markers (grids grid-source) (sprites atlas-source)))
    (define pages (map (lambda (draw) (make-output-page 720 500 draw #:margins 24 #:background 'white)) draws))
    (define pdf-decisions (box '())) (define svg-decisions (box '()))
    (define pdf-report
      (parameterize ([current-decisions pdf-decisions])
        (save-output/audit pages (file ".pdf") 'pdf #:policy 'error #:exists 'replace
                           #:title "Portable geometry and image placements")))
    (write-json-file (file ".pdf.audit.json") (output-audit-report->jsexpr pdf-report))
    (for ([name (in-list names)] [page (in-list pages)])
      (define report
        (parameterize ([current-decisions svg-decisions])
          (save-output/audit page (file (string-append "." name ".svg")) 'svg
                             #:policy (if (equal? name "markers") 'vector-only 'error)
                             #:id-prefix name #:exists 'replace)))
      (write-json-file (file (string-append "." name ".audit.json")) (output-audit-report->jsexpr report))
      (with-skia ([im (output-page->image page #:dpi 144)])
        (save-image im (file (string-append "." name ".reference.png")) 'png #:exists 'replace)))
    (write-json-file (file ".decisions.json")
      (hasheq 'pdf (decision-rows (reverse (unbox pdf-decisions)))
              'svg (decision-rows (reverse (unbox svg-decisions)))))
    (define base (html-escape (path->string (file-name-from-path prefix))))
    (call-with-output-file (file ".review.html")
      (lambda (out)
        (display "<!doctype html><meta charset=\"utf-8\"><title>Portable drawing review</title><style>body{font:16px system-ui;margin:24px;background:#edf0f4;color:#20344e}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:32px}img{width:100%;background:white}figure{margin:0}@media(max-width:850px){.pair{grid-template-columns:1fr}}</style><h1>Portable geometry and image placements</h1>" out)
        (fprintf out "<p><a href=\"~a.pdf\">Actual PDF</a> | <a href=\"~a.plans.json\">Source/destination plans</a> | <a href=\"~a.decisions.json\">Group decisions</a> | <a href=\"~a.inspection.json\">Structural inspection</a></p>" base base base base)
        (display "<p>Left: actual SVG. Right: independent raster reference, not a PDF/SVG rasterization. Inspect edges at several zoom levels: separate image crops retain source pixels, not identical renderer filtering.</p>" out)
        (for ([name (in-list names)])
          (fprintf out "<h2>~a</h2><div class=\"pair\"><figure><figcaption>Actual SVG</figcaption><img src=\"~a.~a.svg\"></figure><figure><figcaption>Independent raster reference</figcaption><img src=\"~a.~a.reference.png\"></figure></div>" name base name base name)))
      #:exists 'replace))
  (printf "Wrote ~a.pdf; 3 SVGs/references; 4 audits; crop plans, source images, decisions, and review HTML\n" prefix))
