#lang racket/base
(require racket/runtime-path (only-in ffi/unsafe void/reference-sink)
         "gpu-context.rkt" "gpu-domain.rkt" "gpu-io-trace.rkt"
         "gpu-images.rkt" "core.rkt" "lifetime.rkt"
         (submod "core.rkt" gpu-surface-internals)
         (submod "core.rkt" gpu-image-internals))
(provide gpu-flush-surface! gpu-flush-image! gpu-context-release-and-abandon!)
(define-runtime-path native-module "gpu-context-control-native.rkt")
(define current-context-control-dispatch (make-parameter #f))
(module* testing #f (provide current-context-control-dispatch))
(define (dispatch)
  (or (current-context-control-dispatch)
      (dynamic-require native-module 'context-control-dispatch/native)))
(define (targeted-flush who context resource surface-target?)
  (unless ((if surface-target? gpu-surface? gpu-image?) resource)
    (raise-argument-error who (if surface-target? "gpu-surface?" "gpu-image?") resource))
  (define domain (context-domain who context))
  (define handle ((if surface-target? surface-h image-h) who resource))
  (unless (eq? domain (owned-gpu-domain handle))
    (error who "resources belong to different GPU contexts"))
  (define cp (domain-pointer domain))
  (define rp (resource-pointer handle))
  (when (and surface-target? (not (= 1 (canvas-save-count (surface-canvas resource)))))
    (error who "targeted surface flush requires a balanced canvas save/layer stack"))
  (define call (dispatch))
  (when (call 'abandoned? cp)
    (domain-request-shutdown! domain)
    (error who "native context is lost or abandoned; abandon/close the execution domain"))
  (record-gpu-io! (hasheq 'kind "flush" 'target (if surface-target? "surface" "image")
                        'context_generation (domain-generation domain)
                        'submission_requested #f 'completion_guaranteed #f))
  (call (if surface-target? 'flush-surface 'flush-image) cp rp)
  (void/reference-sink context resource)
  (void))
(define (gpu-flush-surface! context surface)
  (targeted-flush 'gpu-flush-surface! context surface #t))
(define (gpu-flush-image! context image)
  (targeted-flush 'gpu-flush-image! context image #f))
(define (gpu-context-release-and-abandon! context)
  (define domain (context-domain 'gpu-context-release-and-abandon! context))
  (domain-release-and-abandon! domain
    (lambda (cp)
      (define call (dispatch))
      (record-gpu-io! (hasheq 'kind "context-release-and-abandon"
                            'context_generation (domain-generation domain)
                            'completion_guaranteed #f 'readback #f))
      (call 'release-and-abandon cp)
      (unless (call 'abandoned? cp)
        (error 'gpu-context-release-and-abandon! "native context did not report abandonment"))))
  (void/reference-sink context)
  (void))
