#lang racket/base
;; Native ownership state machine, with private operations injected for tests.
(require "gpu-metal-interop-policy.rkt")
(provide (struct-out metal-interop-ops) make-metal-session
         metal-session-description metal-session-texture metal-session-info
         metal-session-begin! metal-session-complete! metal-session-close!
         metal-session-quarantine! metal-session-rethrow!)
(struct metal-interop-ops (inspect retain release status error new-tail commit))
(struct session (ops owner texture producer description timeout
                     [texture-owned? #:mutable] [producer-owned? #:mutable]
                     [tail #:mutable] [state #:mutable] [waits #:mutable] [error #:mutable] [failure #:mutable]))
;; Indeterminate native references remain reachable, even if construction fails.
(define quarantined (make-hasheq))
(define (owner! s)
  (unless (eq? (session-owner s) (current-thread))
    (error 'metal-interop "native session belongs to another execution owner")))
(define (metal-session-quarantine! s e)
  (owner! s)
  (set-session-state! s 'quarantined)
  (unless (session-error s)
    (set-session-error! s (string->immutable-string
      (if (exn? e) (exn-message e) "non-exception native failure")))
    (set-session-failure! s (box e)))
  (hash-set! quarantined s #t)
  (void))
(define (metal-session-rethrow! s)
  (owner! s)
  (when (session-failure s) (raise (unbox (session-failure s)))))
(define (guard s thunk)
  (with-handlers ([(lambda (_) #t)
                   (lambda (e) (metal-session-quarantine! s e) (raise e))])
    (thunk)))
(define (make-metal-session ops texture producer timeout)
  (metal-timeout! timeout)
  (unless (metal-interop-ops? ops) (raise-argument-error 'make-metal-session "private Metal operations" ops))
  (define d ((metal-interop-ops-inspect ops) texture producer))
  (metal-check-texture! d)
  (define status ((metal-interop-ops-status ops) producer))
  (unless (memv status '(2 3 4))
    (metal-interop-fail 'uncommitted "producer must be committed and not failed; status ~a" status))
  (define s (session ops (current-thread) texture producer d timeout #f #f #f 'ready '() #f #f))
  (with-handlers ([(lambda (_) #t)
                   (lambda (e) (guard s (lambda () (metal-session-close! s))) (raise e))])
    (parameterize-break #f
      ((metal-interop-ops-retain ops) texture) (set-session-texture-owned?! s #t)
      ((metal-interop-ops-retain ops) producer) (set-session-producer-owned?! s #t))
    s))
(define (metal-session-description s) (owner! s) (session-description s))
(define (metal-session-texture s)
  (owner! s)
  (unless (and (session-texture-owned? s) (memq (session-state s) '(ready active completed)))
    (error 'metal-interop "texture is not available"))
  (session-texture s))
(define (wait! s command phase)
  (define ops (session-ops s))
  (define result (metal-wait-completed!
                 (lambda () ((metal-interop-ops-status ops) command))
                 (lambda () ((metal-interop-ops-error ops) command)) (session-timeout s)))
  (set-session-waits! s (cons (hash-set result 'phase phase) (session-waits s))))
(define (metal-session-begin! s)
  (owner! s)
  (unless (eq? (session-state s) 'ready) (error 'metal-interop "native handoff is not ready"))
  (set-session-state! s 'active)
  (guard s (lambda () (wait! s (session-producer s) "producer"))))
(define (metal-session-complete! s)
  (owner! s)
  (unless (eq? (session-state s) 'active) (error 'metal-interop "native handoff is not active"))
  (guard s
    (lambda ()
      (define ops (session-ops s))
      ;; new-tail returns an owned, uncommitted command buffer. Register it
      ;; before commit so every ambiguous failure can retain it safely.
      (parameterize-break #f
        (define tail ((metal-interop-ops-new-tail ops)))
        (unless tail (metal-interop-fail 'allocation "Metal completion buffer allocation failed"))
        (set-session-tail! s tail)
        ((metal-interop-ops-commit ops) tail))
      (wait! s (session-tail s) "ganesh-queue-tail")
      (parameterize-break #f
        (define tail (session-tail s))
        (set-session-tail! s #f) ; never retry a destructor
        ((metal-interop-ops-release ops) tail)
        (set-session-state! s 'completed)))))
(define (metal-session-close! s)
  (owner! s)
  (unless (eq? (session-state s) 'closed)
    (unless (memq (session-state s) '(ready completed))
      (error 'metal-interop "cannot release a ~a session" (session-state s)))
    (guard s
      (lambda ()
        (parameterize-break #f
          (set-session-state! s 'closing)
          (define release (metal-interop-ops-release (session-ops s)))
          (when (session-producer-owned? s)
            (set-session-producer-owned?! s #f) (release (session-producer s)))
          (when (session-texture-owned? s)
            (set-session-texture-owned?! s #f) (release (session-texture s)))
          (set-session-state! s 'closed)))))
  (void))
(define (metal-session-info s)
  (owner! s)
  (hasheq 'state (symbol->string (session-state s))
          'quarantined (eq? (session-state s) 'quarantined) 'error (session-error s)
          'error_reason (and (session-failure s)
            (let ([e (unbox (session-failure s))])
              (if (exn:fail:metal-interop? e) (symbol->string (exn:fail:metal-interop-reason e)) "native-failure")))
          'retained_texture (session-texture-owned? s)
          'retained_producer (session-producer-owned? s)
          'retained_completion_buffer (and (session-tail s) #t)
          'timeout_ms (session-timeout s) 'waits (reverse (session-waits s))))
