#lang racket/base
(require ffi/unsafe ffi/unsafe/atomic
         "core.rkt" "types.rkt" "check.rkt" "lifetime.rkt"
         "gpu-domain.rkt" "gpu-context.rkt" "gpu-surfaces.rkt"
         "gpu-image-native.rkt" "gpu-io-trace.rkt"
         (submod "core.rkt" gpu-image-internals)
         (submod "core.rkt" gpu-surface-internals)
         (only-in "gpu-native.rkt" gr_direct_context_is_abandoned)
         (only-in "../raster-buffers.rkt" raster-buffer? raster-buffer-width raster-buffer-height))
(provide gpu-image? image-residency skia-resource-gpu-context
         gpu-upload-image gpu-surface-snapshot gpu-image-subset gpu-image-info
         gpu-image->rgba-bytes gpu-image->raster-image gpu-image-read-raster-buffer!)

(define (gpu-image? v)
  ;; Classification is by ownership, not an incidental cached GPU copy of an
  ;; ordinary lazy/encoded image. It remains a predicate after explicit close.
  (and (image? v) (domain-resource? (image-h 'gpu-image? v))))
(define (image-residency im)
  (define h (image-h 'image-residency im))
  (when (owned-closed? h) (error 'image-residency "image is closed"))
  (if (gpu-image? im) 'gpu 'cpu))
(define (skia-resource-gpu-context resource)
  (define h (resource-handle 'skia-resource-gpu-context resource))
  (when (owned-closed? h) (error 'skia-resource-gpu-context "resource is closed"))
  (owned-gpu-context h))
(define (context-pointer who context)
  (define d (context-domain who context))
  (define p (domain-pointer d))
  (when (gr_direct_context_is_abandoned p)
    (domain-request-shutdown! d 'native-context-lost)
    (error who "native GPU context is lost or abandoned"))
  p)
(define (gpu-h who im)
  (unless (gpu-image? im) (raise-argument-error who "gpu-image?" im))
  (define h (image-h who im))
  (resource-pointer h)
  h)
(define (adopt-image who context w h create)
  (define d (context-domain who context))
  (define cp (context-pointer who context))
  (gpu-image-native-check!)
  (define handle (new-gpu-owned who 'image d context create image-unref/native))
  (with-handlers ([(lambda (_) #t)
                   (lambda (e) (domain-resource-close! handle) (raise e))])
    (define ip (resource-pointer handle))
    (unless (and (texture-backed?/native ip) (valid-image?/native ip cp))
      (error who "native result is not a valid texture-backed image for this context; no CPU fallback"))
    (make-image-record handle w h)))

(define (gpu-upload-image context im #:mipmapped? [mipmapped? #f] #:budgeted? [budgeted? #t])
  (define who 'gpu-upload-image)
  (boolean who mipmapped?) (boolean who budgeted?)
  (define ih (image-h who im))
  (define d (context-domain who context))
  (define cp (context-pointer who context))
  (when (and (owned-gpu-domain ih) (not (eq? d (owned-gpu-domain ih))))
    (error who "image belongs to another GPU context; detach before uploading to a different context"))
  (define w (image-width im)) (define h (image-height im))
  (check-dimensions who w h)
  (define maximum (hash-ref (domain-info d) 'max_texture_size #f))
  (unless (and (exact-positive-integer? maximum) (<= w maximum) (<= h maximum))
    (error who "image exceeds the context's reported texture size limit: ~a" maximum))
  (gpu-image-native-check!)
  (call-with-owned who (list ih)
    (lambda (ip)
      (define out
        (adopt-image who context w h
          (lambda () (texture-image/native ip cp mipmapped? budgeted?))))
      (record-gpu-io!
       (hasheq 'kind (if (gpu-image? im) "gpu-image-reuse" "upload")
               'width w 'height h 'mipmapped_requested mipmapped? 'budgeted_requested budgeted?))
      out)))
(define (gpu-surface-snapshot s)
  (define who 'gpu-surface-snapshot)
  (unless (gpu-surface? s) (raise-argument-error who "gpu-surface?" s))
  (define context (gpu-surface-context s))
  (context-pointer who context)
  (unless (= 1 (canvas-save-count (surface-canvas s)))
    (error who "snapshot requires a balanced canvas save/layer stack"))
  (gpu-image-native-check!)
  (call-with-owned who (list (surface-h who s))
    (lambda (sp)
      (define im (adopt-image who context (surface-width s) (surface-height s)
                   (lambda () (snapshot/native sp))))
      (record-gpu-io! (hasheq 'kind "gpu-snapshot" 'width (image-width im) 'height (image-height im)))
      im)))
(define (gpu-image-subset im x y width height)
  (define who 'gpu-image-subset)
  (define ih (gpu-h who im))
  (unless (and (exact-nonnegative-integer? x) (exact-nonnegative-integer? y)
               (exact-positive-integer? width) (exact-positive-integer? height)
               (<= (+ x width) (image-width im)) (<= (+ y height) (image-height im)))
    (raise-arguments-error who "subset must be a nonempty integer rectangle inside the image"
                           "x" x "y" y "width" width "height" height))
  (check-dimensions who width height)
  (define context (owned-gpu-context ih))
  (define cp (context-pointer who context))
  (gpu-image-native-check!)
  (define rect (make-sk-irect x y (+ x width) (+ y height)))
  (call-with-owned who (list ih)
    (lambda (ip)
      (begin0
        (adopt-image who context width height (lambda () (subset/native ip cp rect)))
        (record-gpu-io! (hasheq 'kind "gpu-subset" 'x x 'y y 'width width 'height height))
        (void/reference-sink rect)))))
(define (gpu-image-info im)
  (define who 'gpu-image-info)
  (define ih (gpu-h who im))
  (define d (owned-gpu-domain ih))
  (define cp (context-pointer who (owned-gpu-context ih)))
  (gpu-image-native-check!)
  (call-with-owned who (list ih)
    (lambda (ip)
      (define valid? (valid-image?/native ip cp))
      (define texture? (texture-backed?/native ip))
      (unless (and valid? texture?) (error who "native texture is invalid or no longer GPU-backed"))
      (hasheq 'storage "gpu" 'backend (symbol->string (domain-backend d))
              'width (image-width im) 'height (image-height im)
              'context_generation (domain-generation d)
              'context_matches valid? 'texture_backed texture?
              'unique_id (image-id/native ip)
              'readback_path "GPU staging surface; explicit synchronous transfer"))))

;; m119's C sk_image_read_pixels and make_raster_image omit GrDirectContext.
;; Never pretend they provide a context-aware texture download. Instead draw
;; the image 1:1 with Src into a same-context/same-space staging GPU surface,
;; then use 0.39's explicit surface readback. No texture pointer is exposed.
(define (call-with-image-staging who im proc)
  (define ih (gpu-h who im))
  (define context (owned-gpu-context ih))
  (context-pointer who context)
  (define space (image-color-space im))
  (dynamic-wind
    void
    (lambda ()
      (with-skia ([s (make-gpu-surface context (image-width im) (image-height im)
                                      #:color-space space)]
                  [paint (make-paint #:blend-mode 'src #:antialias? #f)])
        (draw-image (surface-canvas s) im 0 0 #:sampling 'nearest #:paint paint)
        (proc s)))
    (lambda () (when space (skia-close! space)))))
(define (gpu-image->rgba-bytes im #:premultiplied? [premultiplied? #f] #:color-space [space #f])
  (define who 'gpu-image->rgba-bytes)
  (boolean who premultiplied?)
  (when space (call-with-owned who (list (color-space-h who space)) void))
  (call-with-image-staging who im
    (lambda (s) (gpu-surface->rgba-bytes s #:premultiplied? premultiplied? #:color-space space))))
(define (gpu-image->raster-image im)
  (call-with-image-staging 'gpu-image->raster-image im gpu-surface->raster-image))
(define (gpu-image-read-raster-buffer! im buffer)
  (define who 'gpu-image-read-raster-buffer!)
  (gpu-h who im)
  (unless (raster-buffer? buffer) (raise-argument-error who "raster-buffer?" buffer))
  (unless (and (= (image-width im) (raster-buffer-width buffer))
               (= (image-height im) (raster-buffer-height buffer)))
    (error who "source image and destination buffer dimensions must match"))
  (call-with-image-staging who im
    (lambda (s) (gpu-surface-read-raster-buffer! s buffer))))

(module* image-operation-internals #f
  (provide gpu-h context-pointer))
