#lang racket/base
;; macOS GUI-only native adapter. Dynamically loaded by skia/gpu-gui, never by
;; CPU/offscreen imports. Raw objects remain private and creator-thread checked.
(require ffi/unsafe "gpu-native-scope.rkt" "gpu-metal-handles.rkt" "gpu-provider.rkt"
         (submod "gpu-presenter.rkt" adapter-internals))
(provide make-metal-layer-host
         metal-layer-measure metal-layer-acquire! metal-layer-present! metal-layer-release!
         metal-layer-finish! metal-layer-close! metal-layer-info metal-drawable-texture metal-drawable-info)
(define-cstruct _ca-size ([width _double] [height _double]))
(define-cstruct _ca-rect ([x _double] [y _double] [width _double] [height _double]))
(struct metal-layer-host
  (owner scope view [layer #:mutable] queue [space #:mutable] identity ops
         [live #:mutable] [presents #:mutable] [last-buffer #:mutable]))
(struct metal-drawable (host [pointer #:mutable] texture info [presented? #:mutable]))
;; Procedures in ops are short synchronous callouts; user rendering never runs
;; with a Cocoa autorelease pool pushed. Method IMPs returning CGRect use the
;; platform's normal C ABI (including x86_64 struct-return conventions).
(define (make-metal-layer-host context view)
  (unless (and (eq? (system-type 'os) 'macosx) (= (ctype-sizeof _pointer) 8))
    (gpu-unavailable 'metal-presentation-platform "Metal presentation requires 64-bit macOS"))
  (define objc (ffi-lib "/usr/lib/libobjc.A.dylib"))
  (define quartz (ffi-lib "/System/Library/Frameworks/QuartzCore.framework/QuartzCore"))
  (define cg (ffi-lib "/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics"))
  (define main? (get-ffi-obj "pthread_main_np" #f (_fun -> _int)))
  (unless (= (main?) 1)
    (error 'gpu-presenter "AppKit/Metal layer access requires the macOS main OS thread"))
  (define sel (get-ffi-obj "sel_registerName" objc (_fun _string/utf-8 -> _pointer)))
  (define cls (get-ffi-obj "objc_getClass" objc (_fun _string/utf-8 -> _pointer)))
  (define obj-cls (get-ffi-obj "object_getClass" objc (_fun _pointer -> _pointer)))
  (define method-imp (get-ffi-obj "class_getMethodImplementation" objc (_fun _pointer _pointer -> _pointer)))
  (define ptr0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _pointer)))
  (define void0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _void)))
  (define ptr1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _pointer -> _void)))
  (define bool0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _int8)))
  (define bool1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _int8 -> _void)))
  (define uint0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _uintptr)))
  (define uint1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _uintptr -> _void)))
  (define double0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _double)))
  (define double1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _double -> _void)))
  (define responds (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _pointer -> _int8)))
  (define size1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _ca-size -> _void)))
  (define rect1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _ca-rect -> _void)))
  (define push (get-ffi-obj "objc_autoreleasePoolPush" objc (_fun -> _pointer)))
  (define pop (get-ffi-obj "objc_autoreleasePoolPop" objc (_fun _pointer -> _void)))
  (define create-space (get-ffi-obj "CGColorSpaceCreateWithName" cg (_fun _pointer -> _pointer)))
  (define release-space (get-ffi-obj "CGColorSpaceRelease" cg (_fun _pointer -> _void)))
  (define srgb (get-ffi-obj "kCGColorSpaceSRGB" cg _pointer))
  (define scope (make-gpu-native-scope push pop))
  (define (get p name) (ptr0 p (sel name)))
  (define (act p name) (void0 p (sel name)))
  (define (put p name arg) (ptr1 p (sel name) arg))
  (define (has? p name) (not (zero? (responds p (sel "respondsToSelector:") (sel name)))))
  (define (rect-get p name)
    (define s (sel name))
    ((cast (method-imp (obj-cls p) s) _pointer (_fun _pointer _pointer -> _ca-rect)) p s))
  (define (backing-rect p rectangle)
    (define s (sel "convertRectToBacking:"))
    ((cast (method-imp (obj-cls p) s) _pointer (_fun _pointer _pointer _ca-rect -> _ca-rect)) p s rectangle))
  (define transaction (cls "CATransaction"))
  (define layer-class (cls "CAMetalLayer"))
  (unless (and transaction layer-class view) (gpu-unavailable 'metal-layer "Cocoa layer classes/view unavailable"))
  (define (without-animation thunk)
    (dynamic-wind (lambda () (act transaction "begin"))
      (lambda () (bool1 transaction (sel "setDisableActions:") 1) (thunk))
      (lambda () (act transaction "commit"))))
  (define (measure h)
    (define bounds (rect-get view "bounds"))
    (define pixels (backing-rect view bounds))
    (define window (get view "window"))
    (define visible?
      (and window (zero? (bool0 view (sel "isHiddenOrHasHiddenAncestor")))
           (not (zero? (bool0 window (sel "isVisible"))))
           (zero? (bool0 window (sel "isMiniaturized")))))
    (presentation-metrics
     (max 0 (inexact->exact (round (ca-rect-width pixels))))
     (max 0 (inexact->exact (round (ca-rect-height pixels))))
     (ca-rect-width bounds) (ca-rect-height bounds) #:visible? (and visible? #t)))
  (define (resize h m)
    (without-animation
     (lambda ()
       (define layer (metal-layer-host-layer h))
       (define bounds (rect-get view "bounds"))
       (rect1 layer (sel "setFrame:") bounds)
       (define window (get view "window"))
       (define scale (if window (double0 window (sel "backingScaleFactor")) 1.0))
       (double1 layer (sel "setContentsScale:") scale)
       (size1 layer (sel "setDrawableSize:")
              (make-ca-size (exact->inexact (hash-ref m 'pixel_width))
                            (exact->inexact (hash-ref m 'pixel_height)))))))
  (define (acquire h m)
    (resize h m)
    (define layer (metal-layer-host-layer h))
    ;; nextDrawable can block for drawable-pool backpressure. This is not an
    ;; explicit GPU-completion wait, nor a promise of nonblocking acquisition.
    (define drawable (get layer "nextDrawable"))
    (and drawable
         (let ()
           (get drawable "retain")
           (with-handlers ([(lambda (_) #t) (lambda (e) (act drawable "release") (raise e))])
             (define texture (get drawable "texture"))
             (unless texture (error 'gpu-presenter "Metal drawable has no texture"))
             (unless (not (zero? (bool0 layer (sel "framebufferOnly"))))
               (error 'gpu-presenter "Metal layer is not framebuffer-only"))
             (define w (uint0 texture (sel "width")))
             (define ht (uint0 texture (sel "height")))
             (unless (and (= w (hash-ref m 'pixel_width)) (= ht (hash-ref m 'pixel_height))
                          (= (uint0 texture (sel "pixelFormat")) 80)
                          (= (uint0 texture (sel "sampleCount")) 1))
               (error 'gpu-presenter "drawable extent, BGRA8 format or sample count disagrees with layer"))
             (set-metal-layer-host-live! h (add1 (metal-layer-host-live h)))
             (metal-drawable h drawable texture
               (hasheq 'width w 'height ht 'pixel_format "BGRA8Unorm" 'metal_pixel_format 80
                       'framebuffer_only #t 'color_space "sRGB" 'texture_sample_count 1
                       'origin "top-left" 'backend "metal" 'target_identity (metal-layer-host-identity h)
                       'presentation_path "CAMetalLayer/same-Ganesh-queue"
                       'acquisition_may_block #t)
               #f)))))
  (define (present h token)
    (define drawable (metal-drawable-pointer token))
    (unless (and drawable (not (metal-drawable-presented? token)))
      (error 'gpu-presenter "drawable is retired or already presented"))
    (define command (get (metal-layer-host-queue h) "commandBuffer"))
    (unless command (error 'gpu-presenter "Metal presentation command buffer creation failed"))
    ;; Ganesh has already flush/submit'ed to THIS exact MTLCommandQueue. Its
    ;; rendering and this presentation buffer are ordered without a CPU fence.
    (set-metal-drawable-presented?! token #t)
    (put command "presentDrawable:" drawable)
    (act command "commit")
    ;; Keep one bounded completion reference for teardown. The previous
    ;; committed buffer is still owned by the native queue while executing.
    ;; This is not a per-frame wait or a public completion API.
    (get command "retain")
    (define previous (metal-layer-host-last-buffer h))
    (set-metal-layer-host-last-buffer! h command)
    (when previous (act previous "release"))
    (when (= (uint0 command (sel "status")) 5)
      (error 'gpu-presenter "Metal presentation command buffer reported an immediate error"))
    (set-metal-layer-host-presents! h (add1 (metal-layer-host-presents h)))
    (void))
  (define (release h token)
    (define p (metal-drawable-pointer token))
    (when p
      (set-metal-drawable-pointer! token #f)
      (set-metal-layer-host-live! h (sub1 (metal-layer-host-live h)))
      (act p "release")))
  (define (finish h)
    (define command (metal-layer-host-last-buffer h))
    (when command
      ;; Teardown, never the normal frame path. Ganesh's own destructor need
      ;; not track presentation buffers created by this adapter, so wait for
      ;; our last same-queue request before detaching the layer/queue owner.
      (act command "waitUntilCompleted")
      (when (= (uint0 command (sel "status")) 5)
        (error 'gpu-presenter-close! "Metal presentation buffer failed asynchronously"))
      (set-metal-layer-host-last-buffer! h #f)
      (act command "release")))
  (define (close h)
    (unless (zero? (metal-layer-host-live h)) (error 'gpu-presenter "live Metal drawable during layer teardown"))
    (finish h)
    (define p (metal-layer-host-layer h))
    (when p
      (set-metal-layer-host-layer! h #f)
      (without-animation (lambda () (act p "removeFromSuperlayer")))
      (act p "release")
      (act (metal-layer-host-view h) "release")
      (define space (metal-layer-host-space h))
      (set-metal-layer-host-space! h #f)
      (when space (release-space space))))
  (call-with-metal-handles context
   (lambda (device queue)
     (parameterize ([current-gpu-native-scope scope])
       (call-with-gpu-native-scope
        (lambda ()
          (define layer #f) (define space #f) (define retained-view? #f) (define ok? #f)
          (dynamic-wind
            void
            (lambda ()
              (get view "retain") (set! retained-view? #t)
              (set! layer (get (get layer-class "alloc") "init"))
              (unless layer (gpu-unavailable 'metal-layer "CAMetalLayer creation returned null"))
              (set! space (create-space srgb))
              (unless space (error 'gpu-presenter "sRGB layer color-space creation failed"))
              (put layer "setDevice:" device)
              (uint1 layer (sel "setPixelFormat:") 80)
              (put layer "setColorspace:" space)
              (bool1 layer (sel "setFramebufferOnly:") 1)
              (bool1 layer (sel "setOpaque:") 1)
              (bool1 layer (sel "setMasksToBounds:") 1)
              (when (has? layer "setAllowsNextDrawableTimeout:")
                (bool1 layer (sel "setAllowsNextDrawableTimeout:") 1))
              (when (has? layer "setMaximumDrawableCount:")
                (uint1 layer (sel "setMaximumDrawableCount:") 3))
              (bool1 view (sel "setWantsLayer:") 1)
              (define root (get view "layer"))
              (unless root (error 'gpu-presenter "Racket NSView has no backing layer"))
              ;; Do not replace Racket's layer/delegate. Our sublayer does not
              ;; intercept the widget's mouse/keyboard event delivery.
              (without-animation (lambda () (put root "addSublayer:" layer)))
              (define h (metal-layer-host (current-thread) scope view layer queue space
                          (symbol->string (gensym 'metal-layer))
                          (hasheq 'libraries (list objc quartz cg) 'main? main? 'measure measure 'acquire acquire
                                  'present present 'release release 'finish finish 'close close) 0 0 #f))
              (set! ok? #t) h)
            (lambda ()
              (unless ok?
                (when layer (act layer "removeFromSuperlayer") (act layer "release"))
                (when retained-view? (act view "release"))
                (when space (release-space space)))))))))))
(define (layer-call who h name . args)
  (unless (metal-layer-host? h) (raise-argument-error who "private Metal layer host" h))
  (unless (and (eq? (current-thread) (metal-layer-host-owner h))
               (= ((hash-ref (metal-layer-host-ops h) 'main?)) 1))
    (error who "Metal layer operations require their owner and the macOS main OS thread"))
  (unless (or (eq? name 'close) (metal-layer-host-layer h)) (error who "Metal layer is closed"))
  (parameterize ([current-gpu-native-scope (metal-layer-host-scope h)])
    (call-with-gpu-native-scope
     (lambda () (apply (hash-ref (metal-layer-host-ops h) name) h args)))))
(define (metal-layer-measure h) (layer-call 'gpu-presenter h 'measure))
(define (metal-layer-acquire! h m) (layer-call 'gpu-presenter h 'acquire m))
(define (metal-layer-present! h token)
  (unless (eq? h (metal-drawable-host token)) (error 'gpu-presenter "foreign Metal drawable"))
  (layer-call 'gpu-presenter h 'present token))
(define (metal-layer-release! h token)
  (unless (eq? h (metal-drawable-host token)) (error 'gpu-presenter "foreign Metal drawable"))
  (layer-call 'gpu-presenter h 'release token))
(define (metal-layer-finish! h) (layer-call 'gpu-presenter-close! h 'finish))
(define (metal-layer-close! h) (layer-call 'gpu-presenter-close! h 'close))
(define (metal-layer-info h)
  (hasheq 'layer_closed (not (metal-layer-host-layer h)) 'live_drawables (metal-layer-host-live h)
          'presents_requested (metal-layer-host-presents h)
          'pending_presentation_buffers (if (metal-layer-host-last-buffer h) 1 0)
          'presentation_path "CAMetalLayer/same-Ganesh-queue"
          'acquisition_may_block #t 'visible_pixels_verified #f))
