#lang racket/base
;; Unsafe ObjC calls stay private, lazy; swizzle uses a typed SDK-checked four-byte aggregate.
(require ffi/unsafe "gpu-provider.rkt" "gpu-native-scope.rkt"
         "gpu-metal-interop-session.rkt")
(provide load-metal-interop-ops)
(define-cstruct _mtl-swizzle ([red _uint8] [green _uint8] [blue _uint8] [alpha _uint8]))
(define (load-metal-interop-ops device queue)
  (unless (and (eq? (system-type 'os) 'macosx)
               (memq (system-type 'arch) '(aarch64 x86_64)) (= (ctype-sizeof _pointer) 8))
    (gpu-unavailable 'metal-interop-platform "Metal interop requires 64-bit macOS"))
  (define objc (ffi-lib "/usr/lib/libobjc.A.dylib"))
  (define sel (get-ffi-obj "sel_registerName" objc (_fun _string/utf-8 -> _pointer)))
  (define protocol (get-ffi-obj "objc_getProtocol" objc (_fun _string/utf-8 -> _pointer)))
  (define obj-class (get-ffi-obj "object_getClass" objc (_fun _pointer -> _pointer)))
  (define imp (get-ffi-obj "class_getMethodImplementation" objc (_fun _pointer _pointer -> _pointer)))
  (define p0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _pointer)))
  (define v0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _void)))
  (define u0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _uintptr)))
  (define b0 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer -> _int8)))
  (define b1 (get-ffi-obj "objc_msgSend" objc (_fun _pointer _pointer _pointer -> _int8)))
  (define push (get-ffi-obj "objc_autoreleasePoolPush" objc (_fun -> _pointer)))
  (define pop (get-ffi-obj "objc_autoreleasePoolPop" objc (_fun _pointer -> _void)))
  (define scope (make-gpu-native-scope push pop))
  (define (native thunk)
    (parameterize ([current-gpu-native-scope scope]) (call-with-gpu-native-scope thunk)))
  (define (get x name) (p0 x (sel name)))
  (define (uint x name) (u0 x (sel name)))
  (define (bool x name) (not (zero? (b0 x (sel name)))))
  (define (has? x name) (not (zero? (b1 x (sel "respondsToSelector:") (sel name)))))
  (define (framebuffer-only? x)
    (cond [(has? x "isFramebufferOnly") (bool x "isFramebufferOnly")]
          [(has? x "framebufferOnly") (bool x "framebufferOnly")]
          [else (gpu-unavailable 'metal-interop-api "MTLTexture has no framebuffer-only getter")]))
  (define (swizzle x)
    (define selector (sel "swizzle"))
    (define v ((cast (imp (obj-class x) selector) _pointer
                    (_fun _pointer _pointer -> _mtl-swizzle)) x selector))
    (list (mtl-swizzle-red v) (mtl-swizzle-green v) (mtl-swizzle-blue v) (mtl-swizzle-alpha v)))
  (define (act x name) (v0 x (sel name)))
  (define (nonnull who x)
    (unless (and x (cpointer? x)) (raise-argument-error who "live non-null Objective-C object pointer" x)))
  (define (conforms x name)
    (define p (protocol name))
    (unless (and p (not (zero? (b1 x (sel "conformsToProtocol:") p))))
      (error 'metal-interop "object does not conform to ~a" name)))
  (define (same? a b) (and a b (ptr-equal? a b)))
  (metal-interop-ops
   (lambda (texture producer)
     (nonnull 'make-metal-external-texture texture) (nonnull 'make-metal-external-texture producer)
     (native
      (lambda ()
        (conforms texture "MTLTexture") (conforms producer "MTLCommandBuffer")
        (for ([name '("hazardTrackingMode" "swizzle" "isShareable" "remoteStorageTexture")])
          (unless (has? texture name)
            (gpu-unavailable 'metal-interop-api "Metal interop requires the macOS 10.15+ texture API (~a)" name)))
        (define q (get producer "commandQueue"))
        (hasheq 'width (uint texture "width") 'height (uint texture "height")
                'depth (uint texture "depth") 'levels (uint texture "mipmapLevelCount")
                'array_length (uint texture "arrayLength") 'samples (uint texture "sampleCount")
                'format (uint texture "pixelFormat") 'texture_type (uint texture "textureType")
                'usage (uint texture "usage") 'storage_mode (uint texture "storageMode")
                'hazard_tracking_mode (uint texture "hazardTrackingMode")
                'framebuffer_only (framebuffer-only? texture)
                'swizzle (swizzle texture)
                'shareable (bool texture "isShareable")
                'has_remote_storage (and (get texture "remoteStorageTexture") #t)
                'has_parent (and (get texture "parentTexture") #t)
                'has_buffer (and (get texture "buffer") #t)
                'has_heap (and (get texture "heap") #t)
                'has_iosurface (and (get texture "iosurface") #t)
                'same_device (and (same? device (get texture "device")) q
                                  (same? device (get q "device")) #t)
                'producer_retained_references (bool producer "retainedReferences")))))
   (lambda (x) (native (lambda () (or (get x "retain") (error 'metal-interop "retain returned null")))))
   (lambda (x) (native (lambda () (act x "release"))))
   (lambda (x) (native (lambda () (uint x "status"))))
   (lambda (x)
     (native (lambda ()
       (define e (get x "error"))
       (define text (and e (get e "localizedDescription")))
       (define utf8 (and text (get text "UTF8String")))
       (if utf8 (string->immutable-string (cast utf8 _pointer _string/utf-8)) "no NSError description"))))
   (lambda ()
     (native (lambda ()
       (define command (get queue "commandBuffer"))
       (and command (get command "retain")))))
   (lambda (command) (native (lambda () (act command "commit"))))))
