#lang racket/base
(require racket/runtime-path (only-in ffi/unsafe void/reference-sink)
         "gpu-context.rkt" "gpu-domain.rkt" "gpu-cache-util.rkt" "gpu-io-trace.rkt")
(provide gpu-cache-info gpu-set-cache-limit! gpu-purge-unlocked! gpu-purge-bytes!
         gpu-perform-deferred-cleanup! gpu-free-resources!)
(define-runtime-path native-module "gpu-cache-native.rkt")
(define current-cache-dispatch (make-parameter #f))
(module* testing #f (provide current-cache-dispatch))
(define (with-cache who context proc)
  (define d (context-domain who context))
  (define p (domain-pointer d)) ; all owner/scope/external-GL checks precede loading
  (define dispatch (or (current-cache-dispatch) (dynamic-require native-module 'cache-dispatch/native)))
  (when (dispatch 'abandoned? p)
    (domain-request-shutdown! d 'native-context-lost)
    (error who "native context is lost or abandoned; abandon/close this execution domain"))
  (begin0 (proc d p dispatch) (void/reference-sink context)))
(define (gpu-cache-info context)
  (with-cache 'gpu-cache-info context
    (lambda (d p dispatch)
      (define-values (limit count bytes) (dispatch 'info p))
      (cache-snapshot (domain-backend d) (domain-generation d) limit count bytes))))
(define (mutate who context op args details)
  (with-cache who context
    (lambda (d p dispatch)
      ;; Requests are not proof of bytes freed or CPU completion. In particular
      ;; m119 freeGpuResources internally flushes/submits (without a CPU fence).
      (record-gpu-io! (hash-set* details 'kind "cache" 'operation (symbol->string op)
                      'context_generation (domain-generation d)
                      'native_may_submit (eq? op 'free-resources) 'completion_guaranteed #f))
      (apply dispatch op p args)
      (void))))
(define (gpu-set-cache-limit! context bytes)
  (cache-size 'gpu-set-cache-limit! bytes)
  (mutate 'gpu-set-cache-limit! context 'set-limit (list bytes) (hasheq 'limit_bytes bytes)))
(define (gpu-purge-unlocked! context #:scratch-only? [scratch-only? #f])
  (cache-boolean 'gpu-purge-unlocked! scratch-only?)
  (mutate 'gpu-purge-unlocked! context 'purge (list scratch-only?) (hasheq 'scratch_only scratch-only?)))
(define (gpu-purge-bytes! context bytes #:prefer-scratch? [prefer-scratch? #t])
  (cache-size 'gpu-purge-bytes! bytes) (cache-boolean 'gpu-purge-bytes! prefer-scratch?)
  (mutate 'gpu-purge-bytes! context 'purge-bytes (list bytes prefer-scratch?)
          (hasheq 'bytes_requested bytes 'prefer_scratch prefer-scratch?)))
(define (gpu-perform-deferred-cleanup! context milliseconds)
  (cache-age 'gpu-perform-deferred-cleanup! milliseconds)
  (mutate 'gpu-perform-deferred-cleanup! context 'deferred (list milliseconds)
          (hasheq 'unused_milliseconds milliseconds)))
(define (gpu-free-resources! context)
  (mutate 'gpu-free-resources! context 'free-resources '() (hasheq)))
