#lang racket/base
(require json racket/cmdline racket/file racket/list "../main.rkt"
         (only-in "../private/live-port-runtime.rkt" active-operation-count in-port-service?))
(define (generate directory token)
  (live-streams-check!) (make-directory* directory)
  (define (save name bytes)
    (call-with-output-file (build-path directory name) (lambda (out) (write-bytes bytes out)) #:mode 'binary #:exists 'error))
  (define raw (bytes 255 0 0 255 0 255 0 255 0 0 255 255 255 255 255 255))
  (define payload (list->bytes (for/list ([i (in-range 131079)]) (modulo i 251))))
  (define copied (open-output-bytes))
  (unless (= (copy-port/streaming (open-input-bytes payload) copied) (bytes-length payload)) (error 'doctor "copy count"))
  (save "copy.bin" (get-output-bytes copied))
  (define owner (current-thread)) (define calls 0)
  (with-skia ([image (rgba-bytes->image 2 2 raw)])
    (for ([encoding '(png jpeg webp)])
      (define collected (open-output-bytes))
      (define out (make-output-port 'observed always-evt
        (lambda (bytes start end _block? _break?)
          (unless (and (not (eq? owner (current-thread))) (in-port-service?))
            (error 'doctor "callback did not run on the protected Racket service thread"))
          (set! calls (add1 calls))
          (define n (min 7 (- end start))) (write-bytes bytes collected start (+ start n)) n) void))
      (image->port image out encoding #:quality 100 #:webp-lossless? #t)
      (define data (get-output-bytes collected)) (save (format "image.~a" encoding) data)
      (when (eq? encoding 'png)
        (with-skia ([again (image-from-port (open-input-bytes data) #:close? #t)])
          (save "decoded.rgba" (image->rgba-bytes again))))))
  (define (draw c)
    (with-skia ([red (make-paint #:color 'red #:antialias? #f)]
                [blue (make-paint #:color 'blue #:antialias? #f)])
      (draw-rect c 8 8 20 16 red) (draw-rect c 0 36 64 12 blue)
      (canvas-annotate-url! c 8 8 20 16 "https://example.test/live")))
  (define authors 0)
  (define page (make-output-page 64 48 (lambda (c) (set! authors (add1 authors)) (draw c)) #:background 'white))
  (for ([kind '(pdf svg)])
    (define out (open-output-bytes))
    (output->port (if (eq? kind 'pdf) (list page page) page) out kind)
    (save (format "document.~a" kind) (get-output-bytes out)))
  (with-skia ([pic (call-with-picture 64 48 draw)])
    (define out (open-output-bytes)) (picture->port pic out) (save "picture.skp" (get-output-bytes out))
    (with-skia ([again (picture-from-port (open-input-bytes (get-output-bytes out)) #:trusted? #t)])
      (unless (equal? (picture-cull-bounds pic) (picture-cull-bounds again)) (error 'doctor "picture extent"))))
  (unless (and (= authors 3) (positive? calls) (= (active-operation-count) 0)) (error 'doctor "incomplete execution"))
  (call-with-output-file (build-path directory "native.json")
    (lambda (out) (write-json (hasheq 'schema 1 'stage "0.75b" 'status "passed" 'run_token token
      'native_version (skia-native-version) 'racket_version (version) 'os (symbol->string (system-type 'os))
      'authoring_calls authors 'write_callbacks calls 'callbacks_on_service_thread #t 'compiler_required #f
      'active_jobs (active-operation-count) 'native_execution #t 'gpu_execution #f) out)) #:exists 'error))
(module+ main
  (define directory #f) (define token #f)
  (command-line #:once-each [("--directory") p "Fresh evidence directory" (set! directory p)]
                [("--token") t "Run identity" (set! token t)])
  (unless (and directory token) (error 'doctor "--directory and --token required"))
  (when (directory-exists? directory) (error 'doctor "directory already exists"))
  (generate directory token) (displayln "live-stream-evidence: passed"))
