#lang racket/base
(require ffi/unsafe "../main.rkt" "../private/types.rkt")
(provide path-matrix-doctor!)

(define (path-matrix-doctor!)
  (unless (and (= (ctype-sizeof _sk-matrix) 36) (= (ctype-sizeof _sk-m44) 64))
    (error 'doctor "incorrect matrix struct layout"))
  (with-skia ([s (make-surface 60 50)] [paint (make-paint #:color 'red #:antialias? #f)])
    (define c (surface-canvas s))
    ;; Verify native-read layout using an already-validated, independent setter.
    (canvas-translate! c 17 23)
    (unless (equal? (canvas-transform c) (matrix-translate 17 23))
      (error 'doctor "native M44 translate/readback has wrong order"))
    (canvas-set-transform! c (make-matrix 2 0 0 3 10 5))
    (draw-rect c 0 0 10 10 paint)
    (unless (equal? (surface-pixel s 15 10) (rgb 255 0 0))
      (error 'doctor "matrix setter raster placement failed")))
  (define p (make-path '((move 0 0) (line 10 0) (line 10 10) (close))))
  (define snapshot (in-path-segments p #:mode 'raw))
  (define segments (path-segments p))
  (unless (and (= (length segments) 5)
               (path-segment-closing-line? (list-ref segments 3)))
    (error 'doctor "normal iterator did not expose its closing line"))
  (with-skia ([m (make-path-measure p)])
    (skia-close! p)
    (unless (equal? (for/list ([s snapshot]) (path-segment-verb s)) '(move line line close))
      (error 'doctor "detached raw snapshot changed"))
    (define matrix (path-measure-matrix m 5))
    (unless (and matrix (< (abs (- (matrix-x0 matrix) 5)) 0.001)
                        (< (abs (matrix-y0 matrix)) 0.001))
      (error 'doctor "path-measure matrix failed")))
  (printf "Path/matrix passed: raw/normal snapshots, expired-source safety, affine canvas, measure frame; M33=36 M44=64\n"))
