#lang racket/base
(require "../main.rkt" "../private/picture-util.rkt")
(provide picture-doctor!)
(define (has? report feature status)
  (for/or ([e (in-list (output-audit-report-events report))])
    (and (eq? (output-audit-event-feature e) feature)
         (eq? (output-audit-event-status e) status))))
(define (picture-doctor!)
  (define (draw c)
    (with-skia ([a (make-paint #:color 'red #:antialias? #f)]
                [b (make-paint #:color 'blue #:antialias? #f)])
      (draw-rect c 0 0 16 24 a) (draw-rect c 16 0 16 24 b)))
  (with-skia ([original (call-with-picture 32 24 draw)]
              [indexed (call-with-picture 32 24 draw #:spatial-index 'rtree)])
    (define data (picture->bytes original))
    (define-values (version bounds) (picture-header 'doctor data))
    (unless (and (= version 103) (equal? bounds #(0.0 0.0 32.0 24.0)))
      (error 'doctor "unexpected pinned picture header"))
    (with-skia ([loaded (picture-from-bytes data #:trusted? #t)]
                [a (picture->image original 32 24)] [b (picture->image loaded 32 24)]
                [d (picture->image indexed 32 24)])
      (unless (and (bytes=? (image->rgba-bytes a) (image->rgba-bytes b))
                   (bytes=? (image->rgba-bytes a) (image->rgba-bytes d))
                   (positive? (picture-unique-id loaded))
                   (positive? (picture-approximate-op-count loaded))
                   (positive? (picture-approximate-bytes-used loaded)))
        (error 'doctor "picture roundtrip, R-tree, or metadata failed"))
      (for ([backend '(pdf svg)])
        (define report
          (analyze-output-page (make-output-page 40 30 (lambda (c) (draw-picture c loaded))) backend))
        (unless (and (output-audit-report-blocking? report)
                     (has? report 'deserialized-picture 'unknown))
          (error 'doctor "loaded picture incorrectly certified for ~a" backend))))
    (define shader (make-picture-shader original #:tile-x 'repeat #:tile-y 'repeat))
    (skia-close! original)
    (with-skia ([retained shader] [paint (make-paint #:shader retained)] [s (make-surface 64 24)])
      (draw-rect (surface-canvas s) 0 0 64 24 paint)
      (unless (equal? (surface-pixel s 36 12) (rgb 255 0 0))
        (error 'doctor "picture shader lost its closed source"))
      (for ([backend '(pdf svg)])
        (define-values (bs report)
          (output->bytes/audit
           (make-output-page 64 24
             (lambda (c) (draw-rasterized c 0 0 64 24 (lambda (r) (draw-rect r 0 0 64 24 paint)))))
           backend #:policy 'error))
        (unless (and (> (bytes-length bs) 0) (has? report 'picture-shader 'rasterized)
                     (not (output-audit-report-blocking? report)))
          (error 'doctor "picture shader fallback failed for ~a" backend)))))
  (printf "Persistent pictures passed: SKP v103 roundtrip, R-tree replay, metadata, retained picture shader, opaque-import audit; no new native layouts\n"))
