#lang racket/base
(require "../main.rkt")
(provide raster-buffer-doctor!)
(define (raster-buffer-doctor!)
  (with-skia ([b (make-raster-buffer 3 2 #:row-bytes 20)])
    (call-with-raster-buffer-canvas b (lambda (c) (canvas-clear! c 'blue)))
    (define old #f)
    (call-with-raster-buffer-pixmap b
      (lambda (v)
        (set! old (pixmap-subset v 1 1 1 1))
        (pixmap-fill! old 'red)
        (unless (= (pixmap-row-bytes old) 20) (error 'doctor "subset lost stride")))
      #:writable? #t)
    (define raw (raster-buffer->storage-bytes b))
    (unless (and (equal? (subbytes raw 24 28) (bytes 255 0 0 255))
                 (equal? (subbytes raw 12 20) (make-bytes 8))
                 (equal? (subbytes raw 32 40) (make-bytes 8)))
      (error 'doctor "incorrect row offset or overwritten padding"))
    (unless (with-handlers ([exn:fail? (lambda (_) #t)]) (pixmap-pixel old 0 0) #f)
      (error 'doctor "escaped pixmap did not expire"))
    (with-skia ([im (raster-buffer->image b)])
      (call-with-raster-buffer-canvas b (lambda (c) (canvas-clear! c 'white)))
      (skia-close! b)
      (unless (equal? (subbytes (image->rgba-bytes im) 16 20) (bytes 255 0 0 255))
        (error 'doctor "snapshot was not independent"))))
  (displayln "Raster buffers passed: padded RGBA storage, direct canvas, borrowed subset, retired view, detached image; no new native layouts"))
(module+ main (raster-buffer-doctor!))
