#lang racket/base
;; Run only on the cache generated by examples/persistent-pictures.rkt. This
;; command deliberately opts into native trusted SKP loading, including SkSL.
(require json racket/file "../main.rkt")
(module+ main
  (define args (current-command-line-arguments))
  (unless (= (vector-length args) 4)
    (error 'replay-picture-probe "expected trusted-cache.skp output-prefix width height"))
  (define source (vector-ref args 0))
  (define prefix (vector-ref args 1))
  (define width (string->number (vector-ref args 2)))
  (define height (string->number (vector-ref args 3)))
  (unless (and (exact-positive-integer? width) (exact-positive-integer? height))
    (error 'replay-picture-probe "width and height must be positive exact integers"))
  (define (out suffix data binary?)
    (call-with-output-file (string-append prefix suffix)
      (lambda (port) (if binary? (write-bytes data port) (begin (write-json data port) (newline port))))
      #:mode (if binary? 'binary 'text) #:exists 'replace))
  (with-skia ([picture (picture-from-file source #:trusted? #t #:width width #:height height)]
              [image (picture->image picture width height)])
    (save-image image (string-append prefix ".png") 'png #:exists 'replace)
    (out ".rgba" (image->rgba-bytes image) #t)
    (out ".json"
         (hasheq 'racket (version) 'native_package native-package-version
                 'width (picture-width picture) 'height (picture-height picture)
                 'cull_bounds (vector->list (picture-cull-bounds picture))
                 'unique_id (picture-unique-id picture)
                 'operations (picture-approximate-op-count picture)
                 'nested_operations (picture-approximate-op-count picture #:nested? #t)
                 'approximate_bytes (picture-approximate-bytes-used picture)) #f))
  (printf "Fresh-process replay wrote ~a.png/.rgba/.json from trusted cache ~a\n" prefix source))
